datastore/tasks/tasks.go
Output before:
`>` list
ID               Description Status5659313586569216 blar9   created 2016-04-04 21:30:07.840395 -0700 PDT
5634472569470976 blar8       created 2016-04-04 21:30:16.45611 -0700 PDT
Output after:
`>` list
ID               Description Status
5659313586569216 blar9       created 2016-04-04 21:30:07.840395 -0700 PDT
5634472569470976 blar8       created 2016-04-04 21:30:16.45611 -0700 PDT
=> Add missing newline in header when listing tasks.

.travis.yml
This has been removed (it moved into the main Go tree)
=> travis: remove 'go get golang.org/x/tools/cmd/vet'

getting-started/bookshelf/db_mysql.go, getting-started/bookshelf/db_test.go
* Use one connection to ensure database and table exists, then use a
new DSN for future connections.
* Fix db.Close() calling itself (would cause an infinite, recursive loop)
Fixes #55.
=> getting-started/bookshelf: handle MySQL connections better

bigquery/syncquery/syncquery.go, bigquery/syncquery/syncquery_test.go
@broady Please take a look.
I would have added an "asynchronous query" like https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/api/async_query.py but I couldn't figure out how to use the "jobs" API with the bigquery client. Filed: https://github.com/GoogleCloudPlatform/gcloud-golang/issues/327
Also, I wanted to support standard SQL syntax instead of or in addition to legacy SQL syntax (the default), but I couldn't find a parameter for it. Filed https://github.com/GoogleCloudPlatform/gcloud-golang/issues/326
=> bigquery: add synchronous query sample

docs/appengine/config/appconfig.txt
Fixing unnessesary scrolling and text that gets hidden in the large reference table caused by long comments: https://cloud.google.com/appengine/docs/go/config/appref#handlers_script
=> docs/appengine/config: wrap lines to prevent scrollbars in docs

bigquery/syncquery/syncquery.go
Change iterator to new methods.
Also, return nil instead of rows so far on error, to be idiomatic.
=> bigquery: update example for new bigquery client surface

docs/managed_vms/cloudsql/app.yaml
The TCP proxy is not bound to the loopback address. The FUSE proxy
works, though.
Add some other instructions on what the connection string should look
like and what the TCP proxy address should be when testing locally.
=> docs/managed_vms/cloudsql: use FUSE connection string

getting-started/bookshelf/app/app.go, getting-started/bookshelf/app/auth.go, getting-started/bookshelf/app/template.go, getting-started/bookshelf/app/templates/base.html
encoding/gob is used to serialize structs to the cookie, which means the
full type information is serialized. This was causing the cookie to
execeed the 4096 byte limit.
Fixes #137.
=> getting-started/bookshelf: use bare struct for profile

language/analyze/analyze.go, language/analyze/analyze_test.go
This has one significant change for Sentiment Analysis:
polarity is dropped and replaced by score.
=> language: update to v1 from v1beta1

endpoints/getting-started/Dockerfile.custom, endpoints/getting-started/container-engine.yaml
Need to switch ports of containers to match other languages.
`gcr.io/google-samples/echo-go:1.0` is updated and pushed to listen on 8080.
=> Update ports for endpoints sample.

bigquery/simpleapp/simpleapp.go
A breaking change was made in the client package:
https://code-review.googlesource.com/#/c/9331/
Update the sample to reflect this change.
=> bigquery: use int64 instead of int when reading values

internal/testutil/retry.go, internal/testutil/retry_test.go, logging/simplelog/simplelog_test.go, pubsub/subscriptions/main_test.go, pubsub/topics/main_test.go, storage/objects/main_test.go
Test output is only written for the final attempt.
A similar interface to *testing.T is provided to each attempt.
```
$ go test -v ./internal/testutil/
=== RUN   TestRetry
--- PASS: TestRetry (0.00s)
=== RUN   TestRetryAttempts
--- PASS: TestRetryAttempts (0.00s)
retry.go:29: Success after 5 attempts:
retry_test.go:24: This line should appear only once.
retry_test.go:25: attempt=5
PASS
ok      github.com/GoogleCloudPlatform/golang-samples/internal/testutil 0.023s
```
=> all: add retry support for flaky tests

docs/appengine/config/appconfig.txt, docs/appengine/config/cron.txt, docs/appengine/modules/converting.txt, docs/appengine/modules/index.txt, docs/appengine/modules/routing.txt, docs/appengine/tools/uploadingdata.txt
All the Go language docs for App Engine have been updated to use the new "gcloud" tool commands so these files (which are imported) also need to be updated. Changes include:
1. Removed the unsupported: "application:" and "version:" elements
2. Replaced all references of "module" with "service"
3. Replace use of "goapp" with "gcloud app deploy"
The following docs are affected:
https://cloud.google.com/appengine/docs/standard/go/tools/remoteapi/
https://cloud.google.com/appengine/docs/standard/go/config/appref
https://cloud.google.com/appengine/docs/standard/go/modules/converting
https://cloud.google.com/appengine/docs/standard/go/config/dispatchref
https://cloud.google.com/appengine/docs/standard/go/configuration-files
https://cloud.google.com/appengine/docs/standard/go/config/cron
=> Updated files for use with "gcloud app deploy"

docs/appengine/taskqueue/app.yaml
Updating code sample to align with docs and the support for "gcloud app deploy":
https://cloud.google.com/appengine/docs/standard/go/taskqueue/push/creating-handlers#securing_task_handler_urls
=> Removing "application:" & "version:"

bigtable/helloworld/README.md, bigtable/helloworld/main.go, bigtable/search/search.go, bigtable/usercounter/README.md, bigtable/usercounter/app.yaml, bigtable/usercounter/main.go
Move the bigtable examples to golang-samples as they are getting deleted from cloud.google.com/go. See https://code-review.googlesource.com/c/11656/.
=> bigtable: move bigtable examples to golang-samples

bigquery/snippets/snippet_test.go
This test takes a long time sometimes, and doesn't print any
intermediary output.
Print a log message very 5 minutes to work Travis's 10 minute timeout.
Move it to an E2E test, only run nightly.
=> bigquery/snippets: move ImportExport to an E2E test

internal/e2e/flexible_test.go
As of Go 1.8, NewRequest reads from the body. Instead of writing to the
body's buffer after the call to NewRequest, call NewRequest after
first preparing the multipart body.
FORCE_E2E=true
=> internal/e2e: prepare the body for POST request before http.Do

storage/objects/main.go
The prefix instructions for queries are incorrect in the Google Cloud Storage sample according to my testing. The `/` belongs at the end of the prefix to look up files in a directory, not at the beginning.
=> Update comments on Cloud Storage Go sample

speech/captionasync/captionasync.go, speech/captionasync/captionasync_test.go
"Inline audio is not allowed with LongRunningRecognize. Please use a GCS
URI."
=> speech/captionasync: use GCS URI, inline audio is not allowed

speech/captionasync/captionasync.go, speech/captionasync/captionasync_test.go
Reverts GoogleCloudPlatform/golang-samples#232
=> speech/captionasync: revert use GCS URI, inline audio is not allowed

speech/captionasync/captionasync.go
Wrong proto package was imported - github.com/gogo/proto over the
official github.com/golang/protobuf
Fixes #236.
=> speech/captionasync: change bad import of "proto" package

speech/caption/caption.go, speech/caption/caption_test.go, speech/captionasync/captionasync.go, speech/captionasync/captionasync_test.go, speech/livecaption/livecaption.go
For caption and captionasync, add samples using GCS URIs.
For livecaption, if the stream cannot be closed, exit the program.
=> speech: add GCS samples; fail hard on error in streaming sample

getting-started/bookshelf/gke_deployment/Dockerfile, getting-started/bookshelf/gke_deployment/bookshelf-frontend.yaml, getting-started/bookshelf/gke_deployment/bookshelf-worker.yaml
* use golang:alpine as base image
* consolidate both commands into one image
* "go get" from the Dockerfile (no need to use aedeploy)
=> getting-started/bookshelf: use golang:alpine to build for GKE

internal/e2e/flexible_test.go
x/time/rate requires the standard library context. We only run these
tests on Travis using Go 1.8.
=> e2e: only run on Go 1.7+

speech/livecaption/livecaption.go
This is a left over from the pre-autogenerated client days
where we were using a gRPC client to talk to the API.
=> speech/livecaption: remove the unused connection

docs/appengine/taskqueue/push/taskqueue_push.go
I found repeat is not working in GAE now. I got the following 500 error in the logging:
```
panic: template: handler:2: function "repeat" not defined
goroutine 1 [running]:
panic(0x1889980, 0xc0105813c0)
go/src/runtime/panic.go:481 +0x3e6
html/template.Must(0x0, 0x2b4c416f1028, 0xc0105813c0, 0x0)
go/src/html/template/template.go:340 +0x4b
main43625.init()
hello.go:62 +0xcd
main.init()
_go_main.go:34 +0x59
```
"range" works normally.
=> replace the "repeat" to "range"

vision/detect/detect.go, vision/detect/generated/gen.go, vision/detect/generated/sample-template.go, vision/label/label.go, vision/vision_quickstart/main.go
Remove the dependency to cloud.google.com/go/vision and use
the new autogenated helpers.
=> vision: switch to the generated surface

kms/crypter/crypter.go, kms/crypter/crypter_test.go
When dealing with encryption, "plaintext" and "ciphertext" are terms of art with
particular meaning. Plaintext is data used as input for encryption, whereas
ciphertext is the output of encryption. Plaintext need not be "plain text" -- it
could be an image, for example.
The example code for other languages are already cased/spelled correctly.
=> kms: fix casing of "plaintext" and "ciphertext" in variable names

appengine_flexible/pubsub/app.yaml, appengine_flexible/pubsub/pubsub.go, bigquery/simpleapp/simpleapp.go, bigquery/syncquery/syncquery.go, endpoints/getting-started-grpc/README.md
In order to provide more consistent examples, I have removed all instances of 'GCLOUD_PROJECT' and replaced them with 'GOOGLE_CLOUD_PROJECT'.
=> Replaced all env variables GCLOUD_PROJECT with GOOGLE_CLOUD_PROJECT

docs/appengine/taskqueue/app.yaml
The url in the handlers, `/tasks/process`, does not work for taskqueue_push.go, where we use `/` and `/worker`.
=> the url pattern is not working

getting-started/bookshelf/gce_deployment/startup-script.sh
Updates the calls to useradd and mkdir.
=> getting-started/bookshelf: make GCE startup script idempotent

speech/captionasync/captionasync.go, speech/captionasync/captionasync_test.go
speech/captionasync: enable WordTimeOffsets
This updates the captionasync example to show how the RecognitionConfig
can be updated to that the API response includes word-level time offsets.
=> speech/captionasync: enable WordTimeOffsets

speech/captionasync/captionasync_test.go
Seconds are int64, not a float. Format them with "%d".
=> speech/captionasync: fix vet warnings

errorreporting/errorreporting_quickstart/main.go
We deprecated package right after I merged the quickstart.
=> errorreporting: errors package is deprecated

storage/objects/main.go
I can't run with below command on Mac. 
So I fixed the source. 
command : GOOGLE_CLOUD_PROJECT=gcpproject bucket -o=bucket:notes write
=> storage/objects: fix args check

endpoints/getting-started-grpc/client/main.go
See https://github.com/grpc/grpc-go/commit/596a6acc87c73c3bc398a60ef0089976491ca060
And build failures: https://travis-ci.org/GoogleCloudPlatform/golang-samples
=> endpoints/getting-started-grpc/client: fix for grpc breaking metadata change

trace/trace_quickstart/main.go
1.6 travis failure:
```
trace/trace_quickstart/main.go:32: undefined: "cloud.google.com/go/trace".Transport
trace/trace_quickstart/main.go:40: req.WithContext undefined (type *"net/http".Request has no field or method WithContext)
trace/trace_quickstart/main.go:40: r.Context undefined (type *"net/http".Request has no field or method Context)
trace/trace_quickstart/main.go:47: traceClient.HTTPHandler undefined (type *"cloud.google.com/go/trace".Client has no field or method HTTPHandler)
```
=> only test trace samples on go1.7+

storage/gcsupload/README.md, storage/gcsupload/gcsupload.go, storage/gcsupload/gcsupload_test.go
This sample is a snippet of code with which you can create a CLI
that allows you to upload a file to your Google Cloud Storage bucket.
* Using it
```shell
upload -project-id orijtech-161805 -source ~/Desktop/birthdayPic.jpg
-bucket orijtech-gcs-test
```
which will give you a result like this
```shell
ObjectURL:
https://storage.googleapis.com/orijtech-gcs-test/birthdayPic.jpg
Size: 865096
MD5: W2x7Su2Dfo7Q+ZUFZKELMg==
```
=> storage: add gcsupload, an upload sample + tests

spanner/spanner_snippets/snippet.go
The proposal fixes the error handling in the Go sample code for Spanner.
In particular, the sample code contains code such as this:
`if err := op.Wait(); err == nil { print(ok) }; return err`
In cases such as this, errors from op.Wait will not be correctly propagated thus causing the program to always exit with "success".
=> spanner: fix error handling in snippet code

vision/detect/detect.go, vision/vision_quickstart/main.go
The path to the `cat.jpg` file is broken in the vision_quickstart demo. This pull request fixes it.
=> vision: fix broken demos

README.md, vision/README.md, vision/detect/README.md, vision/detect/detect.go, vision/detect/generated/sample-template.go
Related to issues #305 and #307. I'm sorry, but I was not aware of the generator and edited the `detect.go` source file directly. This commit provides the fix in the correct place (`generated/sample-template.go`).
I've also added a section to the README to help bringing awareness to necessity of using the generator to modify `detect.go`.
Finally, I've added an entry for the `vision/detect` example in the master table.
=> vision: fix detect.go generator

storage/gcsupload/gcsupload.go
Handles aren't valid once the client is closed.
See: https://code-review.googlesource.com/16950
=> storage/gcsupload: don't close client and return handles

appengine_flexible/cloudsql/cloudsql.go, appengine_flexible/cloudsql_postgres/README.md, appengine_flexible/cloudsql_postgres/app.yaml, appengine_flexible/cloudsql_postgres/cloudsql.go
Similar to the MySQL sample, except with a couple SQL syntax changes and
different connection strings.
=> appengine_flexible: add cloudsql_postgres sample

.travis.yml
Just doing this for consistency with other cloud clients (which i'm updating atm to add 1.9).
Feel free to reject if you disagree.
=> travis: test with most recent minor go version

appengine_flexible/helloworld/app.yaml
We've gotten reports of unexpected costs from users that left the hello world running and had two standard instances running for a month. This keeps the costs to a minimum to kick the tires.
=> Keeping user costs low

bigquery/simpleapp/simpleapp.go, bigquery/simpleapp/simpleapp_test.go
- Add additional region tags to support tutorial rewrite.
- Use nicer struct read for printing results.
- Use more relevant query from public datasets.
=> BigQuery: rewrite simple app tutorial.

endpoints/getting-started/deployment.yaml
For improved readability, let's use long option names for the ESP config. The doc is here: https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options
=> Use long options for ESP config

.travis.yml
go-sql-driver/mysql won't retain support for 1.6, and the only people using 1.6
are opted-in on GAE. (api_version: go1.6)
Pin the version to keep the tests running.
=> travis: pin go-sql-driver/mysql to v1.3 for 1.6 builds

.travis.yml
go get -u breaks if not on master.
=> travis: don't cache the pinned mysql library

bigquery/bigquery_datatransfer_quickstart/main.go
* License fails the license checker (license checker and headers should be
updated to work with Google LLC).
* Fix godoc strings (region tag was part of the godoc).
* Re-order imports to be prettier.
=> bigquery/bigquery_datatransfer_quickstart: fix license, nits

getting-started/bookshelf/pubsub_worker/worker.go
Pubsub Create funcs now return nil topic and subscription upon error,
necessating this fix to prevent segfault on subsequent runs.
=> Prevent nil deref when pubsub topic or sub already exists

opencensus/opencensus_spanner_quickstart/main.go
Fixes #396
The import path of the stats exporter in
OpenCensus changed from
"go.opencensus.io/stats"
to
"go.opencensus.io/stats/view"
=> Fix OpenCensus Spanner quickstart

getting-started/bookshelf/app/template.go
Fixes #404.
Without this change, the underlying template error is not printed when the template fails to Execute.
=> bookshelf: fix format of appErrorf call

spanner/spanner_quickstart/main.go, spanner/spanner_snippets/snippet.go
Related:
* ~~googleapis/nodejs-spanner#136~~ merged
* ~~GoogleCloudPlatform/ruby-docs-samples#244~~ merged
* ~~GoogleCloudPlatform/python-docs-samples#1376~~ merged
* ~~GoogleCloudPlatform/java-docs-samples#1045~~ merged
* GoogleCloudPlatform/dotnet-docs-samples#454
* ~~GoogleCloudPlatform/php-docs-samples#562~~ merged
=> Add Spanner region tags.

endpoints/getting-started-grpc/README.md, endpoints/getting-started-grpc/api_config_auth.yaml, endpoints/getting-started-grpc/client/main.go, endpoints/getting-started-grpc/server/main.go
- Add flag to configure the interface used by the server.
- Add flag to specify an authentication bearer token in the client.
- Add service configuration for authentication through Google service
account.
- Update client to optionally authenticate request using a JWT token
signed by a Google service account.
- Add documentation for service account authentication.
- `gcloud service-management` -> `gcloud endpoints services`
@p-buse @navinger Please take a look. This change adds an example of authentication of a request using a JWT token signed by a Google service account.
=> Endpoints example with JWT authentication.

datastore/snippets/snippet_test.go, datastore/tasks/tasks.go
datastore/snippets/snippet_test.go:30: ExampleNewIncompleteKey refers to unknown identifier: NewIncompleteKey
... (41 more)
Renamed functions in snippet_test to fix this class of vet errors:
sed -i -e 's/func Example/func Snippet/g' snippet_test.go
datastore/tasks/tasks.go:202: Println arg list ends with redundant newline
Changed to fmt.Print to silence this error.
=> datastore: fix vet errors for go1.10

appengine_flexible/redis/redis.go
=> appengine_flexible/redis: use new redigo dep path

speech/livecaption_from_file/README.md, speech/livecaption_from_file/livecaption_from_file.go
[This documentation](https://cloud.google.com/speech/docs/streaming-recognize) is missing a go sample for streaming Speech API requests from a local file.
Although I hope that we can eventually do away with that particular sample altogether (in *all* languages), this pull request is intended to fill the gap. It is a rather straightforward adaptation of the sample in [speech/livecaption](https://github.com/GoogleCloudPlatform/golang-samples/tree/master/speech/livecaption).
Some notes:
+ Given the relatively low value of this sample, I have not worried about supporting GCS reads.
+ Created a new directory to match the structure of the [corresponding Python samples](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming.py). Didn't …
=> speech: add sample for streaming transcription from file

speech/livecaption/README.md, speech/livecaption/livecaption.go
Fixes issue #246.
I've updated the example README to include a bit more information about the limits and usage. I've also updated the code to filter the errors 3 and 11 to print a more user friendly message regarding the 60 second limit.
=> speech: fix livecaption README and error message

README.md
I've made the modifications proposed by #309. I'm not sure if this is the best layout, because some examples seem to fit to more than one category.
I've added a `Getting Started` category to the proposal because I couldn't fit those samples to a single category. Also, there are no Networking examples available right now, but I've left the title there as a placeholder for when those are available.
=> readme: organize examples by category

appengine_flexible/cloudsql_postgres/cloudsql.go
https://github.com/lib/pq dropped support for Go versions < 1.8. See https://github.com/lib/pq/pull/729.
=> appengine_flexible/postgres: only build on Go 1.8+

appengine_flexible/mailjet/mailjet.go, docs/appengine/mail/mailjet/mailjet.go
Mailjet Send API v3.1 is being released, so updating the code samples to match the new Send API v3.1 configuration. Reference can be found [here](https://dev.mailjet.com/beta/).
=> updating Mailjet code samples for Send API v3.1

getting-started/bookshelf/app/app.yaml, getting-started/bookshelf/pubsub_worker/app.yaml
results in:
```
------------------------------------ STDERR ------------------------------------
2018/03/31 16:27:35 invalid api_version value 1
--------------------------------------------------------------------------------
```
otherwise
=> typo in app.yaml blocking deployment to app engine

endpoints/getting-started-grpc/README.md, endpoints/getting-started-grpc/deployment.yaml, endpoints/getting-started/app.yaml, endpoints/getting-started/deployment.yaml
We introduce a new feature where we can specify in YAML that service configuration for Endpoints is going to be managed. This means that the service will pull latest deployed service configuration automatically, rather than requiring customer to specify specific version of service configuration.
New flag:
**--rollout_strategy=managed**
Previously the only way to specify a version was using the following flag:
**--version=SERVICE_CONFIG_ID**
=> endpoints: add managed rollout

.kokoro/build.sh, .kokoro/system_tests.cfg
I'll expand this to get secrets and run tests after builds are working.
Part of #440.
=> kokoro: add basic config and build script

vision/detect/detect_test.go
"Zepra" is not always in the output. But, "Building" seems to be consistent. My local tests get a different result than (some projects in) Travis, so maybe there is a new model rolling out which changes the detect result.
=> vision: make detect test more robust

getting-started/bookshelf/app/app.yaml, getting-started/bookshelf/pubsub_worker/app.yaml, getting-started/helloworld/app.yaml
This is only used for GAE standard. This app is deployed on GAE flex.
=> getting-started: remove erroneous api_version field

firestore/firestore_snippets/query.go
The typo breaks the rendering of the corresponding code snippet in the "Simple queries" section of this page: https://firebase.google.com/docs/firestore/query-data/queries
=> Fix a typo in firestore snippet code marker

storage/buckets/main.go, storage/buckets/main_test.go
If two different projects happen to use the same bucket name, race
conditions may cause tests to fail.
This also deletes any buckets before using them for tests. If the
buckets already exist, they will cause TestCreate to fail and may have
the wrong permissions.
I don't particularly like using `TestMain`, but it seems like the cleanest way to delete the buckets before starting.
=> storage/buckets: use ProjectID for test buckets

testing/kokoro/go16.cfg, testing/kokoro/go18.cfg, testing/kokoro/go19.cfg
1.10 will be added later since it fails the gofmt check right now. Part of issue #440. See #406 for 1.10.
=> testing/kokoro: add builds for Go 1.6, 1.8, & 1.9

dlp/dlp_snippets/risk.go
Sometimes, GetDlpJob reads a stale version of the job DB. Sleeping for
half a second after receiving the job finished message should prevent
not getting any results. In particular, this should reduce test
flakiness.
=> dlp: sleep before getting jobs

pubsub/subscriptions/main.go
Fixes #402.
The mutex should prevent skipping over 10 and never calling `cancel()` and `return`.
=> pubsub/subscriptions: Ack all 10 messages

testing/kokoro/go19.cfg, testing/kokoro/system_tests.sh
Running `gofmt` and `go vet` on every version can lead to conflicts when the tools change. We should only run them for the latest version of Go.
See #406 and #440.
=> testing/kokoro: only run gofmt & go vet on Go 1.9

opencensus/opencensus_spanner_quickstart/main.go, trace/trace_quickstart/main.go
A follow up to:
https://github.com/census-instrumentation/opencensus-go/pull/724
=> trace, opencensus: import Stackdriver exporter from the new path

bigquery/simpleapp/simpleapp.go, bigquery/snippets/snippet.go, bigquery/snippets/snippet_test.go, bigquery/snippets/testdata/people.csv
A variety of BigQuery updates, mostly to cleanup bad region labels and align the examples with other language implementations.
Region updates:
update: bigquery_create_table to match others (build an explicit schema, not go type inference)
add: bigquery_create_table_without_schema
add: bigquery_update_table_description
add: bigquery_update_table_expiration
rename/update: bigquery_insert_stream -> bigquery_table_insert_rows
remove region tag: bigquery_list_rows (leave snippet)
rename/update: bigquery_async_query -> bigquery_query
remove region and impl: bigquery_import_from_gcs
add: bigquery_load_table_gcs_csv
rename/update: bigquery_import_from_file -> bigquery_load_from_file
remove region and impl: bigquery_export_gcs
add: bigquery_get_table (and a more complex variant not yet in a …
=>  BigQuery sample updates and region tag changes.

endpoints/getting-started/README.md
Highlight the requirement for `gcloud beta` for support of the rollout_strategy feature used in the example.
=> Add deployment instructions to README

bigquery/snippets/snippet.go, bigquery/snippets/snippet_test.go, profiler/hotapp/Dockerfile
Add new snippets and refactors some existing query snippets.  
Moves the logic common to many of the query examples to a shared method, and uses multiple region tag areas to stitch them together.
new regions:
[START bigquery_copy_table_multiple_source]
[START bigquery_query]
[START bigquery_query_batch]
[START bigquery_query_destination_table]
[START bigquery_query_dry_run]
[START bigquery_query_legacy]
[START bigquery_query_no_cache]
[START bigquery_query_params_arrays]
[START bigquery_query_params_named]
[START bigquery_query_params_positional]
[START bigquery_query_params_structs]
[START bigquery_query_params_timestamps]
[START bigquery_undelete_table]
=> BigQuery: additional snippets

auth/snippets.go
The snippets correspond to this page: https://cloud.google.com/docs/authentication/production.
I moved the tags out of the implicit function to match most of the other snippets on that page.
=> oauth: add explicit snippets

dlp/dlp_snippets/inspect_test.go
The jobs do not finish within 25 minutes.
Fixes #499.
=> dlp: skip flaky tests

bigquery/snippets/snippet_test.go
Travis was disabled, so periodic logging is no longer necessary.
Part of #501.
=> bigquery: remove unused Travis code

profiler/profiler_quickstart/main.go, profiler/snippets/snippets.go
I also mention `ProjectID` needs to be set when not running on GCP since
it was a surprise when I tried to run this. cc @jba - I wonder if we can
pull the project ID automatically to make this easier.
I didn't add a test because `ProjectID` needs to be set in the
`profiler.Config`, which would complicate the sample.
=> profiler: add Start sample

bigquery/snippets/snippet.go, bigquery/snippets/snippet_test.go
Adds snippets related to Labels functionality, as well as a snippet for bigquery.jobs.list.
Within the BQ API, only the Datasets collection supports the necessary label filtration at present, hence the lack of parity on labels snippets.
=> BigQuery: snippets related to Labels functionality.

testing/kokoro/system_tests.sh
The package imports "context" directly, so Go 1.6 fails during `go get`.
Fixes #514.
=> testing: manually clone go-sql-driver/mysql

datastore/snippets/snippet_test.go, datastore/tasks/tasks.go
These samples/region tags aren't used on cloud.google.com, hence I'm removing them here.
Related:
- GoogleCloudPlatform/python-docs-samples#1531
- googleapis/nodejs-datastore#110
- GoogleCloudPlatform/java-docs-samples#1138
- GoogleCloudPlatform/php-docs-samples#631
- GoogleCloudPlatform/ruby-docs-samples#292
- GoogleCloudPlatform/dotnet-docs-samples#569
=> Delete unused Datastore region tags / samples.

errorreporting/errorreporting_quickstart/main.go
Close now calls Flush, so remove the explicit call from the sample.
=> errorreporting: remove Flush call

testing/kokoro/system_tests.sh
Downloading dependencies is often the slowest part of a testing a PR. This PR changes the test script to only get dependencies needed to run tests in modified directories. `go vet` is also only run on modified directories since it requires the dependencies of what's being vetted.
This PR also simplifies the `git diff` command. From `man git-diff`:
```
"git diff A...B" is equivalent to "git diff $(git-merge-base A B) B".
```
=> testing: only get deps for modified directories

appengine_flexible/pubsub/app.yaml
The environment variable has been reserved for AppEngine use.
`gcloud app deploy` said:
```
ERROR: (gcloud.app.deploy) Error Response: [13] Environment variable(s) ['GOOGLE_CLOUD_PROJECT'] are reserved for App Engine use.
```
/cc @broady
=> appengine_flexible/pubsub: remove GOOGLE_CLOUD_PROJECT variable

speech/livecaption/livecaption.go, speech/livecaption_from_file/livecaption_from_file.go, testing/kokoro/system_tests.sh
The livecaption and livecaption_from_file samples were calling Read
incorrectly: it is possible to get n > 0 bytes along with an error, so
it is important to process the bytes before checking the error.
=> speech: fix calls to Reader.Read

testing/kokoro/system_tests.sh
Otherwise, PRs may not run the license check test.
Fixes #548.
=> testing: run top-level tests every time

monitoring/uptime/uptime.go, monitoring/uptime/uptime_test.go
Should we switch the samples to return `error` and possibly `(*monitoringpb.UptimeCheckConfig, error)`? Would simplify some of the testing and error handling (see the new `TestUpdate` -- `update` could very well return the updated config and `TestUpdate` wouldn't need to make the `get` request.)
Let me know what you think and I'll update.
**Edit**: I updated the functions to return configs and errors and I think it's better, especially because it's easier for users to copy & paste (since they probably won't want to `log.Fatal` in their application).
=> monitoring/uptime: add update sample

storage/buckets/main_test.go
Run the test setup for each test method, which allows selective test
running using Go's -run test flag.
=> storage/buckets: allow test skipping

firestore/firestore_snippets/save.go
I have no idea why I wrote this TODO, but everything seems to work,
tests pass, and this just confuses people reading the snippet in the
docs.
=> firestore: remove erroneous TODO comment

translate/snippets/snippet.go
I verified that this region tag is not used by cloud.google.com. Recommend removal to clean up sample tracking.
=> Remove unused region tag

container_registry/container_analysis/src/sample/samples.go, container_registry/container_analysis/src/sample/samples_test.go
Otherwise I get:
```
Step 3/4 : RUN go get -u github.com/GoogleCloudPlatform/golang-samples/...
---> Running in 145483839d84
runtime.main_main·f: function main is undeclared in the main package
runtime.main_main·f: function main is undeclared in the main package
```
=> Containeranalysis main

kms/asymmetric/samples.go, kms/asymmetric/samples_test.go
```
Step 3/4 : RUN go get -u github.com/GoogleCloudPlatform/golang-samples/...
---> Running in 145483839d84
runtime.main_main·f: function main is undeclared in the main package
runtime.main_main·f: function main is undeclared in the main package
```
=> kms: samples should not be a main package

bigquery/snippets/snippet.go, bigquery/snippets/snippet_test.go
Introduces a variety of sample snippets across the product.  ORC format, Parquet format, CMEK, schema manipulations.
Also, wraps common include block used by all samples in a no-op function, to ensure that samples have a consistent indent depth.
=> BigQuery: many new samples

pubsub/topics/main.go, pubsub/topics/main_test.go
The original publish example shows publishing a single message. 
The added function shows publishing multiple messages with error handling.
=> Publish that scales with asynchronous error handling

profiler/profiler_quickstart/main.go
This guarantees that the first profile collected is a CPU profile, since only CPU profiles will be collected. This is necessary for the profiler quickstart.
=> profiler: do not collect allocation profiles in profiler quickstart.

docs/appengine/taskqueue/push/defer.go, docs/appengine/taskqueue/push/taskqueue_push.go
This also deletes the URL_endpoints sample since it's not used.
=> docs/appengine: move defer sample to another file

appengine/go11x/cloudsql/cloudsql.go
Make the socket file overrideable for the CloudSQL sample to make local dev more flexible.
=> appengine/go11x/cloudsql: allow override of socket file

profiler/hotapp/main.go
This will allow non-empty Heap Alloc profiles to be collected on this app.
=> profiler: add function to hotapp which repeatedly allocates memory

bigquery/snippets/snippet.go, bigquery/snippets/snippet_test.go
Adds new snippets related to imports, view management, and addresses a test flake with table undeletion.
=> BigQuery: new snippets

kms/asymmetric/samples.go, kms/asymmetric/samples_test.go
Updated signAsymmetric and verifySignature* to return []byte instead of string
=> kms: return []byte instead of string

license_test.go
This switches the test to use `regexp` and check the year is 4 digits. There does not seem to be an impact on test speed.
=> license_test: update to allow Google LLC.

videointelligence/video_analyze/gen/template.go, videointelligence/video_analyze/video_analyze.go, videointelligence/video_analyze/video_analyze_gcs.go
Causing test failures due to the test/generation steps being slightly different. This was a doozy to find.
=> videointelligence: format imports in template

errorreporting/errorreporting_quickstart/main.go, profiler/snippets/snippets.go, trace/trace_quickstart/main.go, trace/trace_snippets/snippets.go
This also adds a new snippet that was previously inlined in docs.
~For posterity, the Stackdriver Exporter looks in application default credentials
for the project, so we don't need to specify the project manually.~ Uses `os.Getenv("GOOGLE_CLOUD_PROJECT")` to avoid auto-detection (makes it easier to test on multiple projects with a single service account, too).
=> stackdriver: update region tags

firestore/firestore_snippets/retrieve.go
I believe Washington D.C. would be a good location for a capital city in the United States.
Though this does change the output for the queries in `query.go`, I believe most people would agree with the change.  :-)
=> firestore: make Washington D.C. a capital city

monitoring/custommetric/custommetric_test.go
Custom metric test has been wrapped with retry handlers for some
methods, but not all.  In particular, recent test failures are
related to HTTP 500 backend errors for writing timeseries.
This change wraps writeTimeSeriesValues and deleteMetric 
with testutil.Retry to reduce flakiness.
=> Monitoring: make custom metric tests more resilient.

getting-started/bookshelf/app/app_test.go, internal/webtest/webtest.go
It appears there's test failures due to connection refused for
TestMainFunc, which invokes the application rather than the other
tests which render handlers.
On the suspicion something else is leaving the static port 8080 in
a temporarily unusuable state, this change picks a port randomly
and then passes it via the PORT environment variable which is used
by appengine.Main to override the serving port.
Also fixes a minor typo in internal/webtest.
=> gettingstarted/bookshelf/app: don't rely on port 8080 being open in tests

dlp/dlp_snippets/inspect_test.go, dlp/dlp_snippets/risk_test.go
DLP risk and inspect tests communicate changes via pubsub, and
specifying the topic and subscription names as literal strings.
=> DLP: Reduce use of repeated literal identifiers.

iot/manager/manager.go
- listRegistries command was missing from available commands (function existed)
- Type checking with `.Interface().(error)` fails if `reflect.Value` is `nil`. Checking with `isNil()` instead
=> iot: use isNil to check error with reflection and add missing command

docs/appengine/mail/mailjet/app.yaml
The app.yaml is not used in the documentation and the code snippet itself makes sufficient point about the environment variables.
=> appengine/mailjet: remove unused region tag

memorystore/redis/app.yaml
Replaced "127.0.0.1" with a variable to match other samples and make it more clear the user needs to replace that value in the docs.
=> memorystore/redis: update REDISHOST with user replaced variable

functions/helloworld/hello_pubsub_system_test.go, functions/tips/contexttip/context_tip.go
GOOGLE_CLOUD_PROJECT is not set automatically for Cloud Functions. GCP_PROJECT is set automatically.
=> functions: correct project ID environment variable

appengine/gophers/gophers-6/main.go, appengine_flexible/analytics/analytics.go, getting-started/bookshelf/app/app.go, getting-started/bookshelf/app/auth.go, jobs/v3/howto/howto_test.go
This updates the sample bookshelf app to use the community recommended gofrs uuid package.
go.uuid is effectively unmaintained and contained at least one critical security flaw which took half a year to be merged as the owner isn't active. See https://github.com/satori/go.uuid/pull/75
=> all: swap satori's uuid package to gofrs

spanner/spanner_quickstart/main.go
There is only one row that gets returned. But, in practice, you almost
always want to iterate.
b/66986253
=> spanner: iterate in quickstart

bigquery/bigquery_storage_quickstart/main.go, bigquery/bigquery_storage_quickstart/main_test.go, internal/testutil/runmain.go
This quickstart demonstrates usage of the bigquery storage api to
read the contents of a bigquery managed table.
=> bigquery: add bigquery storage quickstart

storage/gcsupload/gcsupload.go
The public flag in storage/gcsupload.go does not work due to using the fixed value.
So, the uploaded object can always be accessed from public.
=> storage/gcsupload: public flag does not work

endpoints/getting-started-grpc/client/main.go
Existing code is broken where it would attempt to create a context
inside a context as opposed to appending both keys to the context.
Therefore, when both api-key and token are specified, only token
would take effect and not api-key.
=> endpoints: fix sample when both api-key and token are specified

opencensus/metrics_quickstart/main.go, opencensus/opencensus_spanner_quickstart/main.go
Modify quick_start  example to use new metric interface from opencensus. The new interface supports receiving gauges and derived gauges.
=> opencensus: use metric exporter interface

run/authentication/auth.go, run/authentication/auth_test.go
Service to service authentication method sample for Cloud Run.
=> run: service-to-service auth snippet

functions/tips/lazy.go, functions/tips/scope.go
These two snippets are reused in the Cloud Run docs, wrapping in dedicated region tags to track usage/future evolution.
x-ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1254
=> functions/tips: add run region tags

appengine/go11x/tasks/handle_task/Dockerfile
Keeping builds reproducible but adaptive to bugfixes by specifying versions down to minor release.
=> appengine: add golang and alpine version to Dockerfile

spanner/spanner_snippets/snippet_test.go
Spanner tests use stable names for testing, rather than generating
random names on each test invocation.  This change issues a single
pessimistic delete at the start of the snippet test and logs the
output, to reduce flakiness of this approach.
=> spanner: check for database presence at test start

vision/product_search/add_product_to_product_set_test.go, vision/product_search/create_product_set_test.go, vision/product_search/create_product_test.go, vision/product_search/create_reference_image_test.go, vision/product_search/delete_product_set_test.go, vision/product_search/delete_product_test.go, vision/product_search/delete_reference_image_test.go, vision/product_search/import_product_sets_test.go, vision/product_search/remove_product_from_product_set_test.go, vision/product_search/update_product_labels_test.go
Another instance where many tests have implicit expectations on test
start dependent on cleanup from previous runs due to static identifiers.
This test adds explicit probe-and-delete behavior to the start of all
tests that want to create resources (products, product sets, reference
images).
=> vision/product_search: make testing more hermetic.

appengine_flexible/websockets/app.yaml, appengine_flexible/websockets/main.go, appengine_flexible/websockets/main_test.go, appengine_flexible/websockets/static/index.html
New sample to demonstrate GAE Flex Websockets support.
This is based on a [Python canonical sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/flexible/websockets/main_test.py)
=> appengine_flexible: websockets sample

endpoints/getting-started-grpc/README.md
Signed-off-by: Wayne Zhang <qiwzhang@google.com>
The current README is outdated.  Updated it to use container network bridge
=> Update the README to create a network bridge for GCE deployment

spanner/spanner_snippets/snippet.go, spanner/spanner_snippets/snippet_test.go
According to the [Cloud Spanner docs](https://cloud.google.com/spanner/docs/getting-started/go/), the `dmlwritetxn` snippet moves 100000 from Album1 to Album2. However, it was actually moving 200000, and that only worked if you ran the tests in a specific order.
The `writetransaction` snippet was also moving 200000, but in the opposite direction, and without confirming that the budget was actually available before making the transfer.
I cleaned up both snippets, made them consistent with one another, fixed the logic error in `writetransaction`, and updated the tests to make the results more predictable.
=> spanner: use correct/consistent logic to transfer budget

iot/mqttsnippets/gateway_send_data.go, iot/mqttsnippets/gateway_send_data_test.go, iot/mqttsnippets/subscribe_gateway_device_topic.go, iot/mqttsnippets/subscribe_gateway_device_topic_test.go
Issue was port 443 was failing inside GCE instances. Should be fixed, but switching to default port 8883 just in case.
Resolves issue #847
=> iot: change mqtt port to 8883

iam/quickstart/quickstart_test.go
There is a bunch of stuff printed by `log.Println` that is cluttering the
test output.
=> iam/quickstart: use testutil to test main

bigquery/snippets/snippet.go, bigquery/snippets/snippet_test.go
The current samples don't follow our normal sample format, but we can
update that in a future PR. Printing to io.Writers helps to avoid
unnecessary printing during tests.
=> bigquery: print to io.Writers

kms/asymmetric.go
Responding to user feedback, clarify that the returned signature value of kms_sign_asymmetric is base64 encoded.
=> kms: asymmetric - return value is base64 commented

texttospeech/quickstart/quickstart.go
Move region tag to encompass package declaration and imports in response to developer feedback asking for library imports.
=> texttospeech: quickstart include imports and package in region tag

vision/detect/detect.go, vision/detect/detect_test.go
Using parallel subtests for TestDetect saves about ~20 seconds per run
(~22 seconds -> ~2 seconds).
This PR also makes it so we don't need `time.Now().Unix()` to make a unique bucket name. Instead, it cleans and uses the same bucket every time.
Noticed by @alixhami in #569.
=> vision/detect: delete unused sample and add subtests

appengine_flexible/mailgun/mailgun.go, docs/appengine/mail/mailgun/mailgun.go, testing/kokoro/system_tests.sh
Go 1.9.7 and 1.10.3 have minimal support for semantic import versioning.
=> testing: remove special case for mailgun

dlp/dlp_snippets/deid_test.go, dlp/dlp_snippets/inspect_test.go, dlp/dlp_snippets/metadata_test.go, dlp/dlp_snippets/redact_test.go, dlp/dlp_snippets/risk_test.go
Running tests in parallel reduces test time by ~100 seconds.
=> dlp: use parallel subtests

appengine/go11x/helloworld/app.yaml
Changing go111->go112 and putting the go111 value in a comment.
=> appengine: change runtime to go112 and add comment for go111

getting-started/background/translate.go
I put them in the order they'll be shown in the doc. I put the cloud function (`Translate`) last so there won't be compile errors before the other helper functions are defined.
I'm open to splitting it up more or less, if you think that will be more clear.
=> getting-started/background: split Translate into smaller functions

testing/docker/README.md, testing/docker/go110/Dockerfile, testing/docker/go111/Dockerfile, testing/docker/go112/Dockerfile, testing/docker/go19/Dockerfile
Fixes #912.
I built and tagged these as the latest versions and tests pass (with no decline in speed due to not having any sort of dependency caching).
=> testing/docker: add Dockerfiles

pubsub/subscriptions/main.go, pubsub/topics/main.go
Setting PublishSettings individually is recommended over composite literal method. This is because forgetting to set values will default them to the zero value in scenarios where one might not necessarily want to override them.
Additionally, including `ReceiveSettings.Synchronous = true` to make `MaxOutstandingMessages` work. This has been confusing for users before based on current documentation:
```	
// If Synchronous is true, then no more than MaxOutstandingMessages will be in
// memory at one time. (In contrast, when Synchronous is false, more than
// MaxOutstandingMessages may have been received from the service and in memory
// before being processed.) MaxOutstandingBytes still refers to the total bytes
// processed, rather than in memory. NumGoroutines is ignored.
```
=> pubsub: set PublishSettings individually

bigquery/bigquery_storage_quickstart/main.go
The demonstrated strategy was more indicative of a unary RPC.  This changes the retry logic to be better aligned with a long running stream that may continue to consume results for minutes or hours.
This change also improves the printed output by replacing rather than appending elements into a slice.
=> bigquery: alter retry strategy for storage sample, improve output.

bigquery/snippets/snippet_test.go
internally: b/140294699
externally: https://github.com/GoogleCloudPlatform/golang-samples/issues/967
=> bigquery: disable CMEK table copy test which is failing due to backend

bigquery/snippets/snippet_test.go
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/967
(internal issue 140294699)
=> bigquery: re-enable CMEK snippet test

appengine/go11x/static/go.mod, internal/e2e/standard_test.go
Without the go.mod, App Engine can't find the templates.
Fixes #993.
cc @Deleplace.
=> appengine: add static go.mod and test

bigquery/snippets/snippet.go
A US multiregion dataset should use a multiregion keyring.
Internal issue 141554628
=> bigquery: update CMEK example to use multiregion keyring

spanner/spanner_leaderboard/leaderboard_test.go
This test takes 500-700 seconds. Removing some of the additional insertscores calls speeds it up ~300-400 seconds without sacrificing test quality.
I also switched this to be an E2E test, so it will run less often.
=> spanner: shorten leaderboard test and make it E2E

appengine_flexible/cloudsql/cloudsql.go, appengine_flexible/cloudsql_postgres/README.md, appengine_flexible/cloudsql_postgres/cloudsql.go
=> appengine_flexible: mask IPs and don't use appengine package for Cloud SQL

pubsub/pubsub_quickstart/main.go, pubsub/subscriptions/add_users.go, pubsub/subscriptions/async_pull.go, pubsub/subscriptions/create.go, pubsub/subscriptions/create_endpoint.go, pubsub/subscriptions/delete.go, pubsub/subscriptions/policy.go, pubsub/subscriptions/pull_error.go, pubsub/subscriptions/pull_settings.go, pubsub/subscriptions/subscription_test.go, pubsub/subscriptions/test_permissions.go, pubsub/subscriptions/update.go, pubsub/topics/topics_test.go
The current code sample references a Subscription by concatenating the project id with the subscription identifier:
```go
func pullMsgs(w io.Writer, projectID, subName string, topic *pubsub.Topic) error {
// projectID := "my-project-id"
// subName := projectID + "-example-sub"
...
```  
However, only the subscription `id` is needed, so that it can be used to form the fully qualified name. The following is from the pubsub [source code](https://github.com/googleapis/google-cloud-go/blob/master/pubsub/subscription.go#L61):
```go
// SubscriptionInProject creates a reference to a subscription in a given project.
func (c *Client) SubscriptionInProject(id, projectID string) *Subscription {
return &Subscription{
c:    c,
name: fmt.Sprintf("projects/%s/subscriptions/%s", projectID, id),
}
}
``` …
=> Pubsub: Correct subscription reference

go.mod, go.sum
We need the BucketPolicyOnly fix.
=> all: update cloud.google.com/go/storage

kms/asymmetric_test.go, kms/decrypt_rsa.go, kms/snippets_test.go
Also updates `TestMain` to check if the test context was successfully retrieved.
Fixes #1037.
=> kms: don't say to base64 encode when decrypting

testing/kokoro/system_tests.sh
- Don't run Go tests when we only change .md or .github files.
- Don't run tests on deleted files.
- Clean the cache in the trap. Before, a test timeout would cause cache
issues.
- Properly handle changes only in the root dir.
=> testing: don't test .md or deleted dirs

testing/kokoro/system_tests.sh, testing/kokoro/trampoline.sh
This reduces the test time of markdown-only changes by ~60 seconds (~62 seconds -> ~2 seconds). There is some extra time for Kokoro to start up and everything, though, so we won't see a 2 second status update on the PR.
=> testing: more logging, check changes before trampoline

pubsub/topics/publish.go, pubsub/topics/publish_single.go
The function argument and comment were not consistent, so this standardizes everything to use `topicID`.
internal tracking: 144785008
=> pubsub: fix inconsistent variable names

kms/sign.go
The bytes returned from the API are not base64-encoded.
=> kms: fix incorrect comment about base64 encoding

functions/helloworld/hello_cloud_storage.go
this will fix the following error
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: go: finding github.com/GoogleCloudPlatform/golang-samples/functions/helloworld v0.0.0
files/hello_cloud_storage.go:35:26: undefined: time
files/hello_cloud_storage.go:36:26: undefined: time
files/hello_cloud_storage.go:39:26: undefined: time
files/hello_cloud_storage.go:41:26: undefined: time
```
=> functions: import time in hello_cloud_storage.go

speech/snippets/auto_punctuation_test.go
Causing builds to fail right now.
Fixes #1107.
=> speech: use different check for auto punctuation

testing/kokoro/system_tests.sh
When running nightly tests, there are no changes. So, the egrep call
sets a non-zero exit code and the script stops executing.
=> testing: fix significant changes check

functions/firebase/upper/upper.go
See https://cloud.google.com/functions/docs/env-var#nodejs_6_nodejs_8_python_37_and_go_111
b/145818614
=> functions: use GOOGLE_CLOUD_PROJECT, not GCLOUD_PROJECT

videointelligence/annotate/object_tracking.go, videointelligence/annotate/object_tracking_gcs.go, videointelligence/annotate/text_detection.go, videointelligence/annotate/text_detection_gcs.go, videointelligence/video_analyze/video_analyze.go, videointelligence/video_analyze/video_analyze_gcs.go
Calls to `log.Fatal` stop tests before they can retry.
=> videointelligence: return annotated errors

translate/v3/translate_text_test.go
Causing flake with changes in the translated text.
Example failure: https://source.cloud.google.com/results/invocations/ba0264fd-892a-4c10-8890-caaccc5e0c94/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fsystem-tests%2Fgo111/log
=> translate: relax test condition

vision/detect/set_endpoint.go, vision/detect/set_endpoint_test.go
Adding code sample for vision to set a custom endpoint.
Python canonical: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2569
=> vision: add set_endpoint sample

testing/kokoro/system_tests.sh
This will automatically open/close issues for failing/passing tests ([example](https://github.com/GoogleCloudPlatform/golang-samples/issues/1146)). See https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop.
=> testing: publish test log to Build Cop Bot

testing/kokoro/system_tests.sh
We need gcloud for all system tests to be able to publish test results
to the Build Cop Bot.
=> testing: include gcloud on PATH

internal/cloudrunci/cloudrunci.go, run/grpc-ping/e2e_test.go
Adding an integration test option for deploying public Cloud Run services.
Also fixing unhandled errors and fatal errors in run/grpc-ping sample
that are relevant.
=> internal/cloudrunci: add AllowUnauthenticated

dataproc/create_cluster.go, dataproc/create_cluster_test.go, dataproc/quickstart/quickstart_test.go
I also updated some of the error messages and pass project IDs directly, rather than a test context.
=> dataproc: clean clusters before running tests

storage/buckets/get_bucket_metadata.go, storage/buckets/main.go, storage/objects/main.go, storage/s3_sdk/list_gcs_buckets.go, storage/service_account/hmac/activate.go, storage/service_account/hmac/create.go, storage/service_account/hmac/deactivate.go, storage/service_account/hmac/delete.go, storage/service_account/hmac/get.go, storage/service_account/hmac/list.go, storage/storage_quickstart/main.go
The storage client doesn't automatically include timeouts by default,
and users are expected to set their own. This should be included
in sample code.
=> storage: add timeouts to samples

appengine/go11x/tasks/create_task/create_task.go
While using golang create task example, I experienced there was a spike in memory since the client was not closed.
Added closure of client to allow go clean the memory and to avoid production memory spike.
Thanks.
=> appengine: added closure of client to avoid memory spike

go.mod, go.sum, run/logging-manual/main_test.go
Example `log.Writer()` failure: https://source.cloud.google.com/results/invocations/eaa8e2f4-93f2-45d0-87ba-70d8bbabe8a6/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fpresubmit%2Fgo112/log
=> all, run: go mod tidy, don't use log.Writer (added in Go 1.13)

run/image-processing/main.go, run/pubsub/main.go
Hi, just found these typo when checking tutorial of cloud run.
=> run: fix typo in samples

bigquery/snippets/table/bigquery_table_insert_rows.go
This snippet now demonstrates how to disable best effort deduplication,
which allows for higher quota/throughput in streaming insert usage.
=> bigquery: update streaming insert snippet

testing/kokoro/system_tests.sh
There are some incompatible `// indirect` changes between versions. So, we should only check `go mod tidy` with one version.
Blocking #1232.
=> testing: only check go mod tidy with vet version

testing/kokoro/buildcop.sh, testing/kokoro/system_tests.sh
The testing for this PR will be a no-op because the buildcop script is only called for system tests.
The goal of this is to simplify sending logs to the Build Cop Bot. For most repos, calling the script (as in this example) should be enough to enable it.
I already copied the script to the Trampoline directory. I included it in this PR so it could get a code review.
I'm not 100% sure about the markdown syntax in the `buildURL` field. But, I'm hoping it will be passed through properly.
=> testing/kokoro: use buildcop.sh script

securitycenter/notifications/create_notification_config.go, securitycenter/notifications/delete_notification_config.go, securitycenter/notifications/get_notification_config.go, securitycenter/notifications/list_notification_configs.go, securitycenter/notifications/notifications_test.go, securitycenter/notifications/receive_notifications.go, securitycenter/notifications/update_notification_config.go
Notification feature work has been merged into v1, so we need to update the samples to match the updated version.
=> docs: Update securitycenter notification samples to v1

securitycenter/notifications/create_notification_config.go, securitycenter/notifications/delete_notification_config.go, securitycenter/notifications/get_notification_config.go, securitycenter/notifications/list_notification_configs.go, securitycenter/notifications/notifications_test.go, securitycenter/notifications/receive_notifications.go, securitycenter/notifications/update_notification_config.go
This reverts commit cf26d989155ce16db093f3e338f1b09a75f26e4a.
This is breaking the build (`v1` has breaking changes). So, we need to fix the samples, then we can redo this change.
I sent #1281, which will hopefully prevent this in the future.
Fixes #1280.
cc @tdh911 (GH won't let me add as a reviewer).
=> Revert "docs: Update securitycenter notification samples to v1 (#1277)"

testing/kokoro/system_tests.sh, testing/kokoro/trampoline.sh
Changes in a directory that wasn't a submodule led to not running any
tests at all, or running goimports on them.
=> testing: run goimports from root, run tests not in a submodule

container_registry/container_analysis/create_note.go, container_registry/container_analysis/create_occurrence.go, container_registry/container_analysis/delete_note.go, container_registry/container_analysis/delete_occurrence.go, container_registry/container_analysis/filter_vulnerability_occurrences.go, container_registry/container_analysis/get_discovery_info.go, container_registry/container_analysis/get_note.go, container_registry/container_analysis/get_occurrence.go, container_registry/container_analysis/occurrences_for_image.go, container_registry/container_analysis/occurrences_for_note.go, container_registry/container_analysis/poll_discovery_finished.go, container_registry/container_analysis/samples_test.go, container_registry/container_analysis/subscriptions.go, container_registry/container_analysis/vulnerability_occurrences_for_image.go, storage/acl/acl_test.go, storage/objects/objects_test.go, storage/s3_sdk/list_gcs_buckets_test.go, storage/service_account/hmac/hmac_test.go
The container_analysis used package main, but didn't have a func main.
This should fix the build for #1267.
=> container_registry, storage: goimports, fix tests, and rename package main

license_test.go, profiler/shakesapp/main.go, profiler/shakesapp/shakesapp/client.go, profiler/shakesapp/shakesapp/server.go, profiler/shakesapp/shakesapp/shakesapp.proto, testing/kokoro/system_tests.sh
We weren't running the root tests for PRs. So, these incorrect license
headers were not caught before merging the PR.
=> all: fix licenses, always run license test for PRs

internal/testutil/testutil.go
I also made a couple small style fixes.
I ran `go build ./...` and it worked. So, I don't think we're using this anywhere (was necessary for `GOPATH` before modules).
It's possible we'll want something like this for E2E AppEngine testing in the future, but it's causing issues right now, so let's just remove it.
Fixes #1275.
=> internal/testutil: use os.Getwd to calculate Dir

testing/kokoro/system_tests.sh
This way, we run all tests and actually publish them to the Build Cop Bot.
=> testing: move set +e before running tests

go.mod, go.sum, secretmanager/access_secret_version.go, secretmanager/add_secret_version.go, secretmanager/create_secret.go, secretmanager/delete_secret.go, secretmanager/destroy_secret_version.go, secretmanager/disable_secret_version.go, secretmanager/enable_secret_version.go, secretmanager/get_secret.go, secretmanager/get_secret_version.go, secretmanager/iam_grant_access.go, secretmanager/iam_revoke_access.go, secretmanager/list_secret_versions.go, secretmanager/list_secrets.go, secretmanager/quickstart/quickstart.go, secretmanager/secretmanager_test.go, secretmanager/update_secret.go
Client lib has been updated: https://pkg.go.dev/cloud.google.com/go@v0.55.0/secretmanager/apiv1
=> secretmanager: update v1beta1->v1

datastore/snippets/snippet_test.go
Testing, this seems to need `.Name` not `.Namespace`
Fixes: #1330
=> datastore: fix namespace sample

functions/ci_cd/cloudbuild.yaml
**Motivation:** we're adding [Java](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2615) and [Python](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3324) versions of this sample.
Related bug: b/153295209
=> functions/ci_cd: make region tags consistent across languages

asset/quickstart/export-assets/main_test.go, dataproc/quickstart/quickstart_test.go, healthcare/fhir_test.go, internal/testutil/storage_cleaner.go, storage/acl/acl_test.go, storage/buckets/buckets_test.go, storage/buckets/set_bucket_default_kms_key.go, storage/gcsupload/gcsupload_test.go, storage/service_account/hmac/hmac_test.go, vision/detect/detect_test.go
We've copied this code around to several locations -- it's time to put
it in a shared location.
I chose testutil rather than a new package because it's only used for
tests.
We've been running into some flakiness recently with Storage quota
for creating and deleting buckets, so hopefully some retries will help.
Fixes #1309.
=> all: create testutil.CleanBucket, add storage retries

dlp/snippets/risk/categorical.go, dlp/snippets/risk/k_anonymity.go, dlp/snippets/risk/k_map.go, dlp/snippets/risk/l_diversity.go, dlp/snippets/risk/numerical.go, dlp/snippets/risk/risk_test.go
These have been timing out after 1 hour recently. Switch to only waiting
for one minute for the job to finish and only having the test check the
job was created.
Alternatively, we could pass a context.Context as an argument. But,
users have found that confusing. So, I'm not sure if it's better to do
that or to inline the deadline in the sample. I inlined with an
explanatory comment copied from Java but am open to other ideas.
Also, errors weren't checked before, so I added checks.
Fixes #1337.
=> dlp: only wait for 1 minute for risk jobs

storage/service_account/hmac/activate.go, storage/service_account/hmac/create.go, storage/service_account/hmac/deactivate.go, storage/service_account/hmac/delete.go, storage/service_account/hmac/get.go, storage/service_account/hmac/list.go
This is necessary in order to address flakiness in the tests for
these samples.
Fixes #1347
=> storage: extend timeouts for SA HMAC samples

securitycenter/notifications/create_notification_config.go, securitycenter/notifications/delete_notification_config.go, securitycenter/notifications/doc.go, securitycenter/notifications/get_notification_config.go, securitycenter/notifications/list_notification_configs.go, securitycenter/notifications/notifications_test.go, securitycenter/notifications/receive_notifications.go, securitycenter/notifications/update_notification_config.go
I also fixed the package name in the doc comment in doc.go and added a
newline between the license header & package declaration to avoid the
license being in the package commment.
Updates #1352, #1353, #1354, #1355, #1356.
cc @tdh911 
Planning to submit TBR to fix the build.
=> securitycenter/notifications: skip broken tests

kms/kms_test.go
=> kms: skip, don't fail, when GOLANG_SAMPLES_PROJECT_ID is unset

spanner/spanner_snippets/snippet.go
Being consistent with [docs](https://cloud.google.com/spanner/docs/dml-syntax#delete_examples).
=> fix: use DELETE FROM for consistency

datastore/snippets/snippet_test.go
I moved `taskKeys` into the snippet since it's referenced by the new `tasks` declaration.
Thanks to @rumsrami for finding & reporting this!
Fixes #1362.
=> datastore: make dst slice for GetMulti

.github/CODEOWNERS
@crwilcox requested teams for repo access across the board for SoDa teams. Adding a CODEOWNERS file with yoshi-go-admins as default and with the storage team.
=> .github: create CODEOWNERS

spanner/spanner_leaderboard/leaderboard_test.go
If there are different packages, "go test ./..." will run the tests in each package in parallel. This explains why there were double hyphens previously in `leaderboard_test.go`: https://github.com/GoogleCloudPlatform/golang-samples/commit/ea3d55341f40241bfaeccc9538df3fd4fa7286eb
I added a comment to explain the reason. 
Fixes #1387 & #1388
=> spanner: fix DBs conflict in different tests.

testing/sampletests/fakesamples/hello.go, testing/sampletests/fakesamples/hello_test.go, testing/sampletests/main.go, testing/sampletests/main_test.go
Results:
Directory | Before | After | Diff
------------ | --------- | ------ | -----
root | `547/1161` | `613/1162` | `+66ish`
`vision` | `26/53` | `49/53` | `+23`
`bigtable` | `11/44` | `34/44` | `+23`
The root denominator went up by 1 because I added a new (tested) region tag to test against.
Spanner stays the same.
Updates #1402.
=> testing/sampletests: work with function references

trace/trace_quickstart/main.go
Enables tracing of incoming requests
=> trace/trace_quickstart: use Google Cloud propagation in server

logging/simplelog/simplelog_test.go
`go test -count 10` passed locally.
Fixes #696.
=> logging/simplelog: enable test, increase retry pauses

.github/workflows/go.yaml, getting-started/devflowapp/deployment/sed_wrapper.sh, getting-started/gce/startup-script.sh, getting-started/gopher-run/cmd/training.sh, memorystore/redis/gce_deployment/deploy.sh, memorystore/redis/gce_deployment/startup-script.sh, testing/docker/bootstrap.sh, testing/kokoro/system_tests.sh, testing/kokoro/trampoline.sh
=> all: enable and fix issues from shellcheck

bigquery/bigquery_reservation_quickstart/main.go, bigquery/bigquery_reservation_quickstart/main_test.go
The BigQuery reservation API has the possibility to generate nontrivial
costs when creating resources, so this initial quickstart demonstrates
simple enumerations and does no resource creations.
=> bigquery: add reservation quickstart

testing/kokoro/mtls_smoketest.cfg
THis is so we can understand and track which APIs respond on their mTLS
hostname and which do not.
=> testing/kokoro: add mtls_smoketest config

appengine_flexible/helloworld/helloworld.go, appengine_flexible/websockets/main.go, appengine_flexible/websockets/main_test.go, getting-started/bookshelf/main.go, getting-started/devflowapp/devflowapp.go, getting-started/helloworld/helloworld.go
Legacy health checks migrated to split health checks, which are now the
default. Split health checks are not sent to apps by default, so these
handlers are not working as intended.
None of the app.yaml files have health checks configured, so I chose not
to add new split handlers & configuration. I'm open to adding them
if we decide we should.
Fixes #977.
=> all: remove legacy health check handlers

.config/blunderbuss.yml, badfiles_test.go, testing/kokoro/system_tests.sh, testing/kokoro/trampoline.sh
This starts with Storage and BigQuery, but we can add more later.
I updated the test scripts to make Kokoro fast for .config changes.
=> .config, testing: add Blunderbuss config

datastore/snippets/snippet_test.go
We recieved some feedback that the creating of keys should be put
in the sample. I looked at what other languages were doing and
updated samples where there was a quorum showing key creation.
Internal bug: b/156541617
=> datastore: put key creation in examples

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/spanner_create_clients.go, spanner/spanner_snippets/spanner/spanner_read_stale_data.go
Two changes are included: 
- add the create_clients sample
- fix a region tag issue in spanner_read_stale_data
=> spanner: add create_clients sample

firestore/firestore_snippets/collection_group_test.go, firestore/firestore_snippets/increment_test.go, firestore/firestore_snippets/save_test.go, firestore/firestore_snippets/solution_counters_test.go
This way, they only run on one project at a time. Also, we don't have to
make the sample more complicated by customizing the collection name.
Fixes #1492.
=> firestore: make tests EndToEnd

.github/blunderbuss.yml
Copied from https://github.com/googleapis/google-cloud-go/blob/master/.github/blunderbuss.yml.
=> .github: expand Blunderbuss config

dlp/quickstart/quickstart.go, dlp/snippets/deid/date_shift.go, dlp/snippets/deid/deid_fpe.go, dlp/snippets/deid/mask.go, dlp/snippets/deid/reid_fpe.go, dlp/snippets/inspect/inspect_bigquery.go, dlp/snippets/inspect/inspect_datastore.go, dlp/snippets/inspect/inspect_gcs.go, dlp/snippets/inspect/inspect_string.go, dlp/snippets/inspect/inspect_text_file.go, dlp/snippets/jobs/jobs_test.go, dlp/snippets/jobs/list.go, dlp/snippets/redact/redact.go, dlp/snippets/risk/categorical.go, dlp/snippets/risk/k_anonymity.go, dlp/snippets/risk/k_map.go, dlp/snippets/risk/l_diversity.go, dlp/snippets/risk/numerical.go, dlp/snippets/template/create.go, dlp/snippets/template/list.go, dlp/snippets/template/template_test.go, dlp/snippets/trigger/create.go, dlp/snippets/trigger/list.go, dlp/snippets/trigger/trigger_test.go
Update DLP samples to include "locations/global" in the parent field. This ensures that the job name returned by the API matches the job name used internally and (critically) in the pubsub message we match against. 
See internal bug b/158100365 for context.
=> dlp: update samples to include locations/global in parent field

firestore/firestore_snippets/collection_group_setup.go, firestore/firestore_snippets/collection_group_test.go, firestore/firestore_snippets/increment.go, firestore/firestore_snippets/increment_test.go
Tests in different packages can run in parallel. Also, E2E tests run in parallel.
There is at least one more use of `"cities"`, but it's hopefully OK as the only one using it. Those samples use `"cities"` extensively, so it's nice to keep it consistent.
=> firestore: use project-specific collection/doc names

.github/dependabot.yml, .github/renovate.json, badfiles_test.go
Dependabot cannot yet group updates into a single PR. Also, you have to
configure every go.mod you want to get updates for. I prototyped a
generator + test to make sure the config could stay up to date, but it
seems like too much hassle.
Also, it's hard to keep up with the individual PRs with only the root
go.mod receiving Dependabot updates. So, I don't want to imagine every
go.mod getting updates.
Renovate doesn't require a config for every go.mod and can be configured
to group all updates into a single PR.
Updates #1444.
=> .github: switch back to Renovate

internal/gomodversiontest/go.mod, internal/gomodversiontest/main.go, testing/kokoro/system_tests.sh
This allows newer language/toolchain features to be used.
Tests in that module are skipped if the installed Go version in Kokoro
is too old.
=> testing: skip modules with a newer version than toolchain

bigquery/bigquery_storage_quickstart/main_test.go, internal/mtls_smoketest/smoketest_test.go, internal/testutil/testutil.go, vision/detect/detect_test.go, vision/detect/set_endpoint_test.go, vision/product_search/mtls_smoketest_test.go
Adds a test that fails when these endpoints are ready to use and the
test skipping can be removed.
=> all: skip vision, bigquerystorage for mTLS (known bad)

internal/mtls_smoketest/smoketest_test.go, testing/kokoro/mtls_smoketest.bash, testing/kokoro/system_tests.sh
system_tests.sh is a bit over-aggressive (but rightly so) in deciding
which tests to run.
Skip them by deleting them at the beginning of the CI run.
Also adds functions/imagemagick to the skiplist.
=> testing: skip bad mtls by removing go files

internal/mtls_smoketest/smoketest_test.go, testing/kokoro/mtls_smoketest.bash
See build log:
https://source.cloud.google.com/results/invocations/e4580801-8601-491c-86ac-2921c9d0652c
=> testing: skip functions/ocr/app in mtls_smoketest

.github/blunderbuss.yml
Would auto-assign issues like https://github.com/GoogleCloudPlatform/golang-samples/issues/1569.
=> .github: assign dataproc issues to bradmiro

run/events_pubsub/go.mod, run/events_pubsub/main_test.go
After #1224 was resolved, we can now re-enable.
=> run/events_pubsub: re-enable test

profiler/shakesapp/shakesapp/client.go, profiler/shakesapp/shakesapp/server.go
TESTED= enabled heap profiler and compared profiles w/ and w/o fix. Profiles w/ fix showed less memory being used.
Since this application is run only for short intervals in Profiler's How-To, I don't think we need to retake screenshots there.
=> fix(profiler): close connections/clients in shakesapp to fix memory leak

run/events_pubsub/e2e_test.go, run/events_storage/e2e_test.go
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/1647
=> fix: use valid run service name for e2e test

run/events_storage/e2e_test.go
The events-storage test copied from events-pubsub, but where pubsub has validation in the request handler, storage does not. Changing the e2e test to check for OK status instead.
Note these are very shallow "healthcheck" grade tests, we want them to go deeper but this was a path to get tests in place for all the samples quickly.
Fixes #1647.
=> fix(run/events-storage): e2e test checking for invalid criteria

dataproc/quickstart/quickstart_test.go
I ran the test locally (with E2E enabled) and it passed. Hopefully this helps with some of the flakiness.
The error from today was:
```
quickstart_test.go:152: stderr: 2020/08/28 17:23:30 error submitting the cluster creation request: rpc error: code = AlreadyExists desc = Already exists: Failed to create cluster: Cluster projects/golang-samples-tests-8/regions/us-central1/clusters/go-qs-test-golang-samples-tests-8
```
So, it seems the previous retry created the cluster but didn't delete it. Then, the quickstart tried to create the cluster again and couldn't.
Fixes #1646.
=> test(dataproc): make quickstart test delete before retry and E2E

translate/v3/batch_translate_text_test.go
Failed in today's nightly build:
```
batch_translate_text_test.go:56: batchTranslateText: Wait: rpc error: code = PermissionDenied desc = Error: PERMISSION_DENIED. Job state: FAILED.
```
Seems to be a flake issue because it has worked otherwise and permissions haven't changed.
Updates #1572.
=> tests(translate): skip flaky TestBatchTranslateText

cloudsql/mysql/database-sql/cloudsql.go, cloudsql/postgres/database-sql/cloudsql.go, cloudsql/sqlserver/database-sql/cloudsql.go
Improves clarity of Cloud SQL samples by adding comments that provide example values of the environment variables being set
=> chore: added examples of environment variable values to Cloud SQL samples

storage/service_account/hmac/hmac_test.go
This can occasionally have transient failures due to eventual
consistency issues upon key creation. Add a retry similar to
what we have for TestListKeys (which has the same issue).
Fixes #1716
=> test(storage): add retry to hmac TestGetKey

docs/appengine/datastore/consistency/consistency.go
I updated all of the regions in this file to start with `gae_consistency`.
=> docs(appengine): remove master_slave region tags

storage/buckets/get_bucket_metadata.go
[The documentation ](https://cloud.google.com/storage/docs/configuring-cors#viewing-cors-bucket)says that CORS fields could be viewed in bucket's metadata response, but they were missing.
=> fix(storage): add viewing the CORS configuration

functions/console_snippets/http/http.go, functions/console_snippets/http/http_test.go
Fixes #1639 
1. Invalid JSON results in a BadRequest error.
2. No body / no message property results in default message.
This is a retry on #1642, in which I broke the branch. This version has further refinements, so should be preferred regardless.
=> fix(functions/console_snippets/http): error handling and unit tests

spanner/spanner_snippets/spanner/integration_test.go
Skipping this section of TestBackupSample test as there's a production issue that causes this to fail (specifically the `metadata.<fieldName>` filter). #1745 is used to track unskipping the test once the backend issue is resolved.
Fixes #1727
=> test(spanner): skip ListBackupOperations

functions/tips/contexttip/context_tip.go, functions/tips/contexttip/context_tip_test.go
Polishes the contexttip sample for use a third time across the functions docs.
By introducing a couple code patterns from the helloworld sample, I minimized adding length and increased focus on the use cases the sample is serving.
=> refactor(functions/tips/contexttip): contexttip sample for pubsub publish

spanner/spanner_leaderboard/leaderboard_test.go
The error happens with `insertScores` sample. By default, `txn.BatchUpdate > ExecuteBatchDml`'s timeout is 30s so that I update it to 60s. 
Fixes #1726
=> fix(spanner): fix flaky leaderboard test

bigquery/snippets/table/integration_test.go
Currently, table snippet tests mutate metadata for a table serially.
Recently, changes to how mutation pushback work in the backend are
causing intermittent failures.  The pushback is significant enough
that retries are insufficient to address this with the table snippet
tests.
This change addresses the problem by directing some of the mutation
examples to modify an additional BigQuery table.
Fixes: #1749
=> fix(bigquery):  minor refactor to avoid pushback failures

functions/log/process_log_entry.go, getting-started/bookshelf/bookshelf.go, logging/logging_quickstart/main.go, logging/stdlogging/main.go, run/hello-broken/main.go, run/logging-manual/main.go
Requested by product team, Stackdriver Logging was renamed to Cloud Logging and we shouldn't use "Stackdriver" as a brand name anymore. 
Update: Created a [CL](https://critique-ng.corp.google.com/cl/337147495) to update accompanying documentation to these samples
=> refactor(logging): debrand stackdriver logging in favor of cloud logging

eventarc/generic/Dockerfile, eventarc/generic/go.mod, eventarc/generic/main.go, eventarc/generic/main_test.go
- Simple Cloud Run service that logs and replies with the HTTP request (headers/body) received by the service.
- Tests event received string, header, body
- Does not log `Authorization` header.
- Includes test
- Very useful for debugging Eventarc systems in Go
- Adds a simple test to ensure the headers and body are appropriately logged.
- Tested locally
- Deployed to Cloud Run
- Example: https://helloworld123-q7vieseilq-uc.a.run.app/
=> feat: add eventarc generic snippet

spanner/spanner_leaderboard/leaderboard.go, spanner/spanner_leaderboard/leaderboard_test.go
Inserting 800 rows as a single Batch DML statement can take a long time, and the transaction can be aborted one or more times. The deadline used for such an operation therefore needs to be (very) long. It is now increased to 10 minutes.
Furthermore, the test case has been cleaned up a little bit:
* The multiple deferred functions for cleaning up have been combined into one.
* The database name is no longer fixed, allowing multiple instances of this test case to be executed at the same time.
* The generated player id's are now guaranteed to be unique. The previous version generated random id values that could overlap (although the probability was extremely low).
Fixes #1726
=> test(spanner): increase timeout and cleanup test

storage/s3_sdk/s3_gcs_test.go
This authentication error can occur as a transient error. Adding
a retry to see if this will fix the flakiness.
Fixes #1762
=> test(storage): add retry to s3sdk test

pubsub/topics/publish_resume_ordering.go
The comment was (I think) incorrect, and the prose was hard to parse.
=> fix(pubsub): correct comment in resume publish

logging/simplelog/simplelog.go, logging/simplelog/simplelog_test.go
fixes: #1559, #1800 
1. Flakiness context: DeleteLog itself creates an audit log entry which cannot be deleted by deleteLog(). This caused previous flakiness issues as the test was expecting only 2 logs even if the test was run/terminated many times (and had multiple audit logs). 
2. [Run time context](https://github.com/googleapis/google-cloud-go/issues/3088)
=> test(logging): remove TestSimpleLog flakiness and reduce test run time

CONTRIBUTING.md
The instructions tripped me up a bit because user accounts can run tests in client library repo, but in samples, it has to be a service account
=> docs: update running system tests instructions

spanner/spanner_snippets/snippet.go
If clients are not closed properly, this can lead to an issue that sessions are not properly deleted.
=> fix(spanner): clients are not properly closed

storage/buckets/buckets_test.go
Test projects are supposed to be exempt from bucket rate limits but
we've continued to see issues with the KMS test in particular. Adding
retries to get around this.
Fixes #1813
=> test(storage): unflake TestKMS

spanner/spanner_snippets/spanner/integration_test.go
The backend issue has been fixed and released so we can unskip the test. 
Fixes #1745
=> test(spanner): unskip list backup operations

dataproc/instantiate_inline_workflow_template_test.go, dlp/snippets/trigger/trigger_test.go, storage/objects/objects_test.go
Fixes #1408. I went through the failures in #1408 and improved where I could. It's possible we could add additional checks to make sure the API is enabled or the current service account has permission. But, that seems like more effort than it's worth.
=> test: switch dataproc test to E2E, improve dlp/storage error handling

spanner/spanner_leaderboard/leaderboard_test.go
The Spanner leaderboard test generates scores for random dates for the past 24 months. The test queried the scores for all records that were not older than 178 hours, which could return zero records if the random insert process did not happen to insert a record with a date no older than 178 hours. The query has now been changed to search for dates that are at least 24 months ago, to ensure that there will always be results.
Fixes #1820
=> test(spanner): fix leaderboard test

.github/renovate.json
The latest changes are incompatible with Go 1.11.
=> chore(.github): disable x/tools updates

bigquery/bigquery_storage_quickstart/main_test.go
The storage quickstart is flaky, but there's not enough diagnostic
information to implicate why.  This PR adds the stderr output to the log
when the test errors.
Related issue:
https://github.com/GoogleCloudPlatform/golang-samples/issues/1866
=> chore(bigquery): add verbose logging to flaky test

storage/buckets/buckets_test.go
We are apparently exempt from the rate limit for bucket
creation/deletion, but not from the one for bucket updates.
Fixes #1849
=> test(storage): unflake TestRequesterPays

bigquery/bigquery_storage_quickstart/main.go
Related: https://github.com/GoogleCloudPlatform/golang-samples/issues/1866
=> chore(bigquery): make flaky sample more verbose in implicating read session

media/transcoder/transcoder_test.go
This test gets the job state and checks that it succeeded. The test is
currently regularly failing because the job is still RUNNING and we stop
retrying. Let's double the number of retries and hope that fixes the
issue.
Fixes #1880.
=> test(media): increase number of retries

endpoints/getting-started-grpc/deployment.yaml
Deprecated APIs was removed from 1.16
=> fix(endpoints): update gke deployment apiVersion to apps/v1

logging/simplelog/simplelog.go
In this page: https://cloud.google.com/logging/docs/samples/logging-write-log-entry#logging_write_log_entry-go
The go example is mismatched. It should feature the structured-log sample, not the std/idiomatic log sample.
=> docs(logging): feature the correct write structured log sample

appengine/go11x/pubsub/authenicated_push/main.go, appengine_flexible/pubsub/pubsub.go
This adds two missing 'return' statements after calls to http.Error to avoid execution falling through into the 'success' code path.
In both cases, the calls to http.Error are reporting failed security checks, so if this example code was copied into a production system it would probably cause a security vulnerability.
=> fix: add missing return statements

internal/cloudrunci/cloudrunci.go, internal/cloudrunci/gcloud.go
Fixes #1934 
Fixes #1925
Fixes #1944
This iteration of improvement was discussed in #1934.
https://github.com/GoogleCloudPlatform/golang-samples/issues/1934#issuecomment-776279586 had my thoughts on a more complicated solution that would allow shorter retry delays.
=> testing(run): increase retry delay for builds to reduce flakiness

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/spanner_create_table_with_datatypes.go, spanner/spanner_snippets/spanner/spanner_drop_column.go
Adds the missing `NUMERIC` column to the sample table.
Fixes #1942
=> fix: add NUMERIC column to sample

spanner/spanner_snippets/spanner/spanner_create_backup.go
Using the local date/time as the version time of a backup can cause issues if there's a difference between the local time and the backend time. The backend will not accept any version time that is in the future, or that is before the earliest version time of a database. Using the earliest version time is therefore the safest option.
Fixes #1900
=> fix(spanner): use earliest version time for backups

bigquery/snippets/table/bigquery_create_table_from_template.go, bigquery/snippets/table/integration_test.go
For cases where users want to understand how to create a table with the same properties (schema, partitioning, clustering) as some prototypical table, without copying data.
=> feat(bigquery): add template table creation sample

eventarc/audit_storage/Dockerfile, eventarc/audit_storage/main.go
Updates region tags to use `audit_storage`, not `gcs`.
These aren't in the docs, please merge this when approved.
=> chore: update dockerfile regions

cloudsql/mysql/database-sql/Dockerfile, cloudsql/postgres/database-sql/Dockerfile, cloudsql/sqlserver/database-sql/Dockerfile, eventarc/audit_storage/Dockerfile, eventarc/generic/Dockerfile, eventarc/pubsub/Dockerfile, memorystore/redis/cloud_run_deployment/Dockerfile, run/grpc-ping/Dockerfile, run/hello-broken/Dockerfile, run/helloworld/Dockerfile, run/image-processing/Dockerfile, run/logging-manual/Dockerfile, run/markdown-preview/editor/Dockerfile, run/markdown-preview/renderer/Dockerfile, run/pubsub/Dockerfile, run/sigterm-handler/Dockerfile, run/system_package/Dockerfile
Uses default `-mod=readonly` behavior of Go 1.16.
Internal b/181980790
=> feat: use default -mod=readonly from Go 1.16

asset/quickstart/analyze-iam-policy-longrunning-bigquery/main_test.go, asset/quickstart/export-assets-bigquery/main_test.go, asset/quickstart/export-assets/main_test.go, asset/quickstart/search-all-resources/main_test.go, internal/testutil/storage_cleaner.go
There seem to be delays and inconsistent results with creating and deleting assets. So, much of this change is defensiveness in the various operations and responding to the various types of errors. I've run the tests many times locally and they're passing. But, CI might think differently.
Fixes #1897.
Fixes #2024.
Fixes #2025.
Fixes #2031.
=> chore(asset): try to reduce flakiness

spanner/spanner_snippets/spanner/integration_test.go
This change has two effects: 
* Make two tests to run daily (end-to-end tests) because they will take very long time to run. 
* Make them to run in sequential instead of in parallel to avoid a conflict due to the limit that an instance only allows max 1 restore db operation at any time. 
Fix #2033
=> fix(spanner): fix conflicting restore db operations

asset/quickstart/analyze-iam-policy-longrunning-bigquery/main_test.go
This passed `go test -v -count 10`.
Fixes #2025.
=> test(asset): increase BQ retries

testing/kokoro/system_tests.sh
If there are no `.go` files in the module root, `goVersionShouldSkip` fails.
Similarly, if it's a brand new module, the module can't be found and
`goVersionShouldSkip` wouldn't check the current directory.
These are both fixed by doing `go list [...] ./...` to list the current
directory.
Note that `grep` exits 0 if there is any match. So, `grep -v go$modVersion`
exits 0 if there is at least one line that does not contain the module
version. In other words, if the list of Go versions supported by the
current version of the `go` command does not contain `go$modVersion`,
skip testing this module.
For example:
$ go1.11.13 list -f "{{context.ReleaseTags}}" ./...
[go1.1 go1.2 go1.3 go1.4 go1.5 go1.6 go1.7 go1.8 go1.9 go1.10 go1.11]
That line does not include go1.12 (or 13, 14, ...), so `grep` …
=> testing: check mod version when no Go files in root

memorystore/redis/main.go
From the Redis docs: "Deprecated: Initialize the Pool directly as shown in the example." So I updated the file to use `redis.Pool` as shown in the example.
=> fix(memorystore): update main.go since redis.NewPool is deprecated

securitycenter/notifications/notifications_test.go
See https://github.com/GoogleCloudPlatform/golang-samples/issues/2057. The test is failing consistently locally, so I'm skipping it for now.
cc @tdh911
=> test(securitycenter): skip TestListNotificationConfigs

securitycenter/notifications/notifications_test.go
Underlying issue has been fixed. Passed locally with `-count 10`.
Fixes #2057.
=> test(securitycenter): unskip TestListNotificationConfigs

bigquery/snippets/table/bigquery_list_tables.go
Artifact of copy and pasting.  The tableID comment isn't needed for
table listing.
=> doc(bigquery): remove spurious comment

bigquery/bigquery_storage_quickstart/main.go
grpc-go sets 4MB as the default client receive size, so we still can't just remove this option entirely in the face of large row response messages.
=> chore: bump grpc message send limit to 128MB in sample

.github/renovate.json
Renovate consistently picks the wrong version. See https://github.com/renovatebot/renovate/issues/4589.
=> chore: disable Renovate for pubsublite

storage/service_account/hmac/hmac_test.go
Fixes the culprit for the panic (second time through the retry loop would have broken because `key` is overwritten by `nil` after an error happens the first time).
Also added some more cleanup for test resources and fixed some other potential causes of panics in other tests.
Fixes #2037
=> test(storage): HMAC test fixes

pubsub/subscriptions/subscription_test.go, pubsub/topics/publish_scale.go, pubsub/topics/topics_test.go
This takes the same resource creation/cleanup code from the Go pub/sub's e2e test and adds them here. Previously, tests were run with fixed topic/subscriptions with some cleanup, but if tests were run concurrently, this could lead to test failures, (e.g. #2082). Now, resources are unique for every invocation and includes a unix nano string that we can check for freshness. If resources are over 24 hours old, we'll delete them as part of the setup func.
Fixes #2082
=> refactor(pubsub): make test resources unique and improve cleanup

opentelemetry/trace/main.go
Synchronous export carries a very heavy performance penalty (added
latency for each request), whereas batching with default options only
adds a 5s delay before a given trace is exported.
With this change, we guide users towards the right starting point. If
they have more specialized needs that call for synchronous export, they
can learn more from the upstream OTel docs.
=> opentelemetry: export traces in batch rather than synchronously

opentelemetry/trace/main.go
According to internal chats, Shutdown() is not meant to be called by the user,
ForceFlush() is the right thing to do here.
Context: http://doc/1R82XXlE8dVt1C-kLYRH2gFLVCzSgKiRna0yroZTsjhs/edit?resourcekey=0-iYHnmYFHYuh8ltcMbPFxhw&disco=AAAAMyjSPL0
cc: @aabmass @punya
=> fix(opentelemetry): use the right flush method

.github/renovate.json
x/net now has a minimum version of Go 1.14.
Related: https://github.com/googleapis/google-api-go-client/pull/1016.
=> chore(.github): ignore x/net updates

spanner/spanner_snippets/spanner/integration_test.go
Unskip backup test now that each test uses its own instance (#2122). This should reduce the probability that a (backup) test times out.
Fixes #1900
=> test(spanner): unskip backup test

run/markdown-preview/editor/templates/index.html
Fixes #1924, my expectation is this problem faces all versions of this sample app.
It looks from the material-components-web repository that major releases with breaking changes have moved from "measured in years" to "measured in months": https://github.com/material-components/material-components-web/releases
This means all samples that use CDN inclusion of material-components-web should switch from `latest` to the most recent major release (e.g., `11.0.0`).
It appears that in June 2020, the fullwidth option used in the Markdown Preview Editor styling became unsupported in favor of recommending an explicit `width: 100%` attribute: https://github.com/material-components/material-components-web/commit/69a35e80ceadb5ef9ffae87345eefbd80b383f51
I have made these two changes in this PR, and …
=> fix(run/markdown-preview): narrow text input width in web UI

endpoints/getting-started/deployment.yaml
Deprecated APIs was removed from 1.16.
Similar changes made in #1893 need to be applied to this sample.
=> fix(endpoints): update sample deployment apiVersion to apps/v1

datastore/snippets/snippet_test.go
We received feedback that it was hard to understand what cursorStr was. This pulls the variable into the sample along with a doc string. Also adds a docstring to nextCursor
=> docs(firestore): incorporate a var to sample, improve docstrings

asset/quickstart/analyze-iam-policy-longrunning-bigquery/main_test.go, asset/quickstart/analyze-iam-policy-longrunning-gcs/main_test.go
There was recently an intentional breaking change in the way
asset LROs respond. Updaing the test to just check for a successful
completion.
Fixes: #2176
Fixes: #2182
=> fix(asset): fix tests

kms/verify_asymmetric_ec.go
Fixes error message in asymmetric public key check for ECDSA signature
verification example.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> fix(kms): asymmetric public key ec error message

datacatalog/datacatalog_quickstart/main_test.go
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/2200
=> fix(datacatalog): add small delay in quickstart test to avoid test flakes.

vision/product_search/get_similar_products_uri_test.go, vision/product_search/get_similar_products_uri_with_filter_test.go, vision/product_search/get_similar_products_with_filter_test.go
It appears some buckets/assests have disappeared. Skipping these
tests to unblock other work.
Updates: #2206
=> chore: skip some vision tests

pubsub/subscriptions/pull_concurrency.go, pubsub/subscriptions/subscription_test.go
The concurrency sample before didn't show how to configure the number of message handlers (`MaxOutstandingMessages`). This PR adds that and adds retries to reduce flakiness, as well as increasing the total pull time to 30 seconds to match the Java sample.
Fixes #2194
=> fix(pubsub): update concurrency sample

vision/product_search/get_similar_products_uri_test.go, vision/product_search/get_similar_products_uri_with_filter_test.go
After running these tests locally they do not seem to fail anymore.
Maybe assets were restored, I am not quite sure.
Fixes: #2206
=> test(vision): unskip tests

dialogflow/README.md
Theses samples seem like they used to be runable, but they are no
longer so. Simplify README to reflect this.
Fixes: #2289
=> chore(dialogflow): update readme

storage/s3_sdk/s3_gcs_test.go
Add retry for HMAC Key test creation. The client no longer retries
this operation automatically because it is non-idempotent.
Fixes #2292
=> test(storage): fix s3_sdk test flake

cloudsql/mysql/database-sql/cloudsql.go, cloudsql/postgres/database-sql/cloudsql.go, cloudsql/sqlserver/database-sql/cloudsql.go
Google Cloud recommends limiting a database connection's lifetime to 1800 seconds, but samples use a 1800 value for `time.Duration` which evaluates to 1800 nanoseconds.
Express the arguments to `SetConnMaxLifetime` as `time.Second`.
=> fix(cloudsql) database max connection lifetime

CONTRIBUTING.md
It's easy to miss this step and will cause hard-to-debug
build failures if you do.
=> docs: update CONTRIBUTING with go.sum info

spanner/spanner_snippets/spanner/integration_test.go, testing/cloudbuild/run.bash, testing/kokoro/system_tests.sh
* Unskip spanner sample tests
* Parse environment variable to read instanceConfigName for tests
* Update the default test instance config to `regional-us-west1`
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/2143
=> test(spanner): unskip flaky tests and add method to read instance config name from environment

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/spanner_list_backup_operations.go
TestCustomerManagedEncryptionKeys need encryption key in same region as test instance, and ListBackupOperation needs metadata.@type as first filter option similar issue in C++ https://github.com/googleapis/google-cloud-cpp/issues/7741.
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/2333 https://github.com/GoogleCloudPlatform/golang-samples/issues/2334
=> test(spanner): fix backup tests

opencensus/go.mod, opencensus/trace_exemplar.go, opencensus/trace_exemplar_test.go
The documentation for this is around trace exemplars, which requires a SpanContext attachment.
This is a common source of confusion when using Exemplars (the need to attach one of the documented types as an `Any`).
=> fix(opencensus): trace exemplar example to show how to use attachments

run/sigterm-handler/main.go, run/testing/sigterm_handler.e2e_test.go
Using a query param, request explicit termination, rather than waiting for
instance timeouts.
Fixes #2444
This PR also increases a client Timeout that was causing some flakiness (like
[this
one](https://source.cloud.google.com/results/invocations/a3483248-ddbc-44db-b4b8-e8a6f453a55b/targets/github%2Fgolang-samples%2Frun%2Ftesting/tests))
=> fix(run): deflake sigterm-handler by sigterm'ing explicitly

run/testing/grpc_server_streaming.e2e_test.go
=> fix(run/testing/grpc): de-flake by being less picky about receive times.

iam/snippets/service_accounts_test.go
Attempt to fix occasional test flakes apparently caused by eventual consistency of recently created Service Account with retry of `renameServiceAccount`.
closes: #2486
=> test(iam): Add Retry to TestServiceAccounts

bigquery/snippets/managedwriter/bigquerystorage_append_rows_pending.go
Adds example of client closure to the existing managedwriter sample.
=> chore(bigquery): defer client close

iam/snippets/service_accounts_test.go
Attempt to fix occasional test flakes apparently caused by eventual consistency of recently created Service Account with retry of renameServiceAccount.
Fixes: #2486
=> test(iam): Add Retry to TestServiceAccounts (2nd attempt)

cloudsql/mysql/database-sql/README.md, cloudsql/mysql/database-sql/cmd/app/app.flexible.yaml, cloudsql/mysql/database-sql/cmd/app/app.standard.yaml, cloudsql/postgres/database-sql/README.md, cloudsql/postgres/database-sql/cmd/app/app.flexible.yaml, cloudsql/postgres/database-sql/cmd/app/app.standard.yaml, cloudsql/sqlserver/database-sql/README.md, cloudsql/sqlserver/database-sql/cmd/app/app.standard.yaml
Making README's easier to follow for users by having all references to inputs for environment variables be consistent.
=> chore(cloudsql): update naming to be consistent

bigquery/snippets/querying/bigquery_query.go, bigquery/snippets/querying/bigquery_query_clustered_table.go, bigquery/snippets/querying/bigquery_query_destination_table.go, bigquery/snippets/querying/bigquery_query_destination_table_cmek.go, bigquery/snippets/querying/bigquery_query_legacy.go, bigquery/snippets/querying/bigquery_query_legacy_large_results.go, bigquery/snippets/querying/bigquery_query_no_cache.go, bigquery/snippets/querying/bigquery_query_params_arrays.go, bigquery/snippets/querying/bigquery_query_params_named.go, bigquery/snippets/querying/bigquery_query_params_positional.go, bigquery/snippets/querying/bigquery_query_params_structs.go, bigquery/snippets/querying/bigquery_query_params_timestamps.go, bigquery/snippets/querying/bigquery_query_partitioned_table.go
This updates the existing query snippets to demonstrate directly accessing the iterator.  Previously, these samples used the pattern of managing/monitoring the job directly via Run -> Wait -> Read.
This does two things:  simplifies the query samples, and potentially enables faster results access.
Samples that don't access query results were left unmodified (e.g. dry run, DML queries, etc).
=> chore(bigquery): switch bigquery query snippets to direct iterator

.github/renovate.json
Similar to googleapis/google-cloud-go#6050
> Switching the group name should make changes come from a new branch on the renovate fork I believe. This may fix the issue that we are no longer getting PRs from our current branch.
=> chore: try to get renovate working

storage/buckets/create_bucket.go, storage/buckets/create_bucket_class_location.go, storage/buckets/create_bucket_dual_region.go, storage/buckets/create_bucket_turbo_replication.go
bucket.Create is being retried appropriately by the client, but
we still hit a test flake due to 503s. This extends the timeout
to 30s.
Fixes #2606
=> storage: increase bucket create timeout

run/testing/sigterm_handler.e2e_test.go
the prior approach was being url escaped, so test is still flaky.
Fixes #2580
=> fix(run/sigterm): use query string for terminate

storage/buckets/buckets_test.go
This test is failing due to the rollout of a backend change.
It should be fixed and re-enabled in #2620.
Updates #2644
=> test(storage): Skip dual region test

storage/buckets/delete_bucket.go
This extends bucket delete timeout to 30s
Fixes #2670
=> test(storage): increase bucket delete timeout

run/pubsub/main.go
in sample browser, other languages have an explicit base64 decode. This adds some documentation so that folks don't file bugs on "missing a decode step" 
b/238760874
=> docs: clears up difference of go from other languages

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/pg_spanner_dml_delete_returning.go, spanner/spanner_snippets/spanner/pg_spanner_dml_insert_returning.go, spanner/spanner_snippets/spanner/pg_spanner_dml_update_returning.go, spanner/spanner_snippets/spanner/spanner_create_database.go, spanner/spanner_snippets/spanner/spanner_dml_delete_returning.go, spanner/spanner_snippets/spanner/spanner_dml_insert_returning.go, spanner/spanner_snippets/spanner/spanner_dml_update_returning.go
Samples are provided for INSERT, DELETE, and UPDATE in both GoogleSQL and PostgreSQL dialects. To provide a more compelling example for the INSERT case, a generated column has been added in the "create_database" example so that the generated value can be returned in the INSERT examples. This changed the number of mutations generated for inserts to the Artists table, and the commitStats test case was updated as a result.
=> feat: Add snippets for Spanner DML with returning clause

pubsub/subscriptions/pull_concurrency.go, pubsub/subscriptions/pull_settings.go
We deprecated `subscription.ReceiveSettings.Synchronous` a while back with the introduction of server side flow control. This PR updates the samples to no longer reference this and clarifies some behavior.
=> fix(pubsub): remove references to deprecated Synchronous field

pubsub/subscriptions/subscription_test.go
Sometimes, Pub/Sub pull samples can fail because resources are created ad-hoc per test. There is latency and wonkiness that can happen since this is not a common Pub/Sub use pattern (topic/subscriptions are generally created once and well in advance). Wrapping these pull tests with retries should reduce test flakiness, but if this doesn't work we might want to consider adding delays after resource creation, and before messages are published.
Note to reviewer: there's a lot of churn here in the diff, but essentially I wrapped / edited 4 tests with `testutil.Retry` and changed instances of `t.Fatalf` to `t.Errorf`. Each test is retried 5 times, with a 5 second delay in between.
Closes #2413 #2685
=> test(pubsub): add retries to pull samples to reduce flakiness

testing/kokoro/trampoline.sh
Recent changes to Kokoro have caused this initial `git` command to error, resulting in no tests being run.
While we're skipping the check here, it is still done in `testing/kokoro/system_test.sh`, so I do not anticipate any cost increase over out previous baseline (prior to the breakage).
=> fix(testing): Work around kokoro image changes

storage/objects/change_file_storage_class.go, storage/objects/change_object_csek_to_cmek.go, storage/objects/copy_file.go, storage/objects/copy_file_archived_generation.go, storage/objects/delete_file.go, storage/objects/move_file.go, storage/objects/release_event_based_hold.go, storage/objects/release_temporary_hold.go, storage/objects/rotate_encryption_key.go, storage/objects/set_event_based_hold.go, storage/objects/set_metadata.go, storage/objects/set_temporary_hold.go
- fix comments that reference "upload" to reflect the correct operation being performed
- fix comments that mention "generation" instead of "metageneration" where applicable
=> docs(storage): fix precondition comments

functions/http/cors.go
Migrate https://cloud.google.com/functions/docs/samples/functions-http-cors#functions_http_cors-go example to gen2 signature using functions framework.
Tested, executes successfully with the command:
```
curl -m 70 -X POST https://garethgeorge-http-function-go-sehddnhvmq-uc.a.run.app \
-H "Authorization: bearer $(gcloud auth print-identity-token)" \
-H "Content-Type: application/json" \
-d '{
"name": "Hello World"
}'
```
=> chore(functions/v2): migrate CORS sample to gen2

asset/quickstart/create-saved-query/main_test.go, asset/quickstart/delete-saved-query/main_test.go, asset/quickstart/export-assets/main_test.go, asset/quickstart/get-saved-query/main_test.go, asset/quickstart/list-saved-queries/main_test.go, asset/quickstart/update-saved-query/main_test.go, batch/create_with_gcs_bucket_test.go, batch/create_with_template_test.go, batch/job_basics_test.go, bigquery/snippets/datatransfer/integration_test.go, iam/deny/deny_policy_test.go, storagetransfer/storagetransfer_test.go, testing/kokoro/system_tests.sh, translate/v3/translate_text_test.go
part of #2811 
This fixes xml log generation. In order to re-enable this, Ive skipped a number of tests that are currently failing.
The linked issue will remain open until these tests are re-enabled or per-test followup bugs are filed.
=> fix(testing): fix test xml output, disable currently-failing tests for investigation

functions/security/go.mod, functions/security/security_system_test.go
=> chore(functions/security): use go 1.18, not 1.13

internal/cloudrunci/testingapp/Dockerfile
vendoring is causing test failures due to direct/indirect dependencies.
=> chore: remove explicit mod=vendor

storagetransfer/storagetransfer_quickstart/main.go
Moves the STS quickstart to its own directory
This is to facilitate a Neos tutorial (it ends with running the quickstart in the command line)
Not deleting the original quickstart.go file yet, will do so after updating the quickstart page to point to this file.
=> docs(storagetransfer): move quickstart to its own directory

datastore/snippets/snippet_test.go
Per [the documentation](https://pkg.go.dev/cloud.google.com/go/datastore#Query.Filter), `Filter()` has been replaced by `FilterField()`.
=> chore(datastore): updates Filter to FilterField

.github/CODEOWNERS, .github/blunderbuss.yml
Please note that I see the following error. Probably @GoogleCloudPlatform/googleapis-dlp needs to be given write access to the repo.
Unknown owner on line 76: make sure the team @GoogleCloudPlatform/googleapis-dlp exists, is publicly visible, and has write access to the repository
…                              @GoogleCloudPlatform/googleapis-dlp
=> chore: add googleapis-dlp team as DLP product codeowners

videointelligence/video_analyze/video_analyze_test.go
this api uses minutely quota, so we need at least one minute delays
between retries.
=> fix(videointelligence): add long-period retries in tests

.github/blunderbuss.yml
also removes outdated contact for cloudiot.
=> fix(blunderbuss): move Run to team alias

testing/kokoro/system_tests.sh
When changing .github, for example, the prior behavor resulted in
CHANGED_DIRS=., which would find all modules below, and run all tests.
this was observed in the presubmit testing of #3002
=> fix(testing): stop running all tests on insignificant changes

videointelligence/video_analyze/video_analyze_test.go
t.Error() fails the test, and does not permit retry. r.Errorf() will trigger a retry instead of a test failure.
=> fix(videointelligence): use retryable Error method

docs/appengine/capabilities/capability.go
making this code runnable for c.g.c; 
Discussion about whether we should include these samples and we should probably revisit as the API docs https://cloud.google.com/appengine/docs/standard/go/reference/services/bundled/latest/capability have almost the exact same detail, so might be better to archive these samples. That's a longer effort, so in the short term, fix this sample so it's runnable in the docs with a little more user friendly comments.
Totally worked with @grayside on this, but all the mistakes are all my fault/misunderstanding (if there are any).
=> fix(appengine): fix missing context initiatilization in capability.go

getting-started/bookshelf/bookshelf.go, getting-started/bookshelf/db_firestore.go, getting-started/bookshelf/main.go, getting-started/bookshelf/template.go
chore(fixit): Go Error Visibility for getting-started/bookshelf. It converts %v to %w whenever it's supported.
=> chore(fixit): Go Error Visibility for getting-started/bookshelf

videointelligence/video_analyze/video_analyze_test.go
see #3049 for longer context. skipping these tests until we fix them.
=> fix(videointelligence): skip failing tests.

videointelligence/video_analyze/video_analyze.go, videointelligence/video_analyze/video_analyze_gcs.go
=> chore(fixit): Go Error Visibility for videointelligence/video_analyze

logging/exportlogs/create_sink.go, logging/exportlogs/delete_sink.go, logging/exportlogs/exportlogs.go, logging/exportlogs/list_sink.go, logging/exportlogs/update_sink.go
To better align with the style guide, these regions have moved to their own
files.
these region tags are currently frozen in the docs, so this change is safe.
=> chore: refactor exportlogs samples to stand alone

privateca/privateca_test.go
Adding t.Helper calls per GoLang testing best practices discussed over in reviewers chat group.
=> chore(privateca): adding t.Helper calls per best practices

run/testing/hello_broken.e2e_test.go
These tests are somewhat flaky, and adding retries here will compensate.
Fixes #3009
=> fix(run/testing): add retries to hello_broken tests

run/custom-metrics/go.mod, run/custom-metrics/main.go
This updates the Cloud Run custom metrics example to automatically detect the service name from Cloud Run. This reflects more clearly in the output metrics:
=> feat(run): Add service name detection to custom metrics example

eventarc/audit_storage/main.go
Fixes #3188.
As noted in the issue triage, the following changes were made:
* Dedicated error handling for non-POST requests
* Do not crash on CloudEvent parsing errors
* Remove logging of potential user data in a web service
=> testing(eventarc): fix TestAuditStorageSinkService failure

internal/aeintegrate/aeintegrate.go, internal/e2e/standard_test.go, internal/testutil/runmain.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
=> chore: remove refs to deprecated io/ioutil

pubsub/subscriptions/subscription_test.go
Missing control flow statement means an error was always occurring. This only catches the case after the resource already exists, which is why previous presubmits didn't catch this.
Fixes #3229
=> fix(pubsub): fix control flow error path

healthcare/hl7v2_store_create.go
=> fix(healthcare): specify V3 parser version when creating HL7v2 store

securitycenter/findings/findings_test.go
This Security Center test runs out of quota regularly, blocking other PRs. Let's skip it and assign an issue to a SC expert to fix.
=> chore(securitycenter): marks flaky test with skip

run/testing/helloworld.e2e_test.go, run/testing/pubsub.e2e_test.go, run/testing/system_package.e2e_test.go
This PR will add a retry method to the following run e2e tests:
- `helloworld.e2e_test.go`
- `pubsub.e2e_test.go`
- 
Fixes #3268, fixes #3253, fixes #3254
=> test(run): Add retries for flaky run tests

errorreporting/errorreporting_quickstart/main.go
align code sample for error reporting with code in other languages (b/275730159). use an explicit error with the "fixed" message. populate the service context with the name of the service (module) and the version.
=> fix: refactor error reporting code sample

securitycenter/notifications/notifications_test.go
Increasing wait time between retries to avoid hitting quota.
Fixes #3275
=> fix(security-center): increase wait time in notification test

functions/helloworld/hello_world.go
This PR will add a different region tag for the Cloud Functions sample. The same region tag is used in [2nd gen version of the sample](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/functions/functionsv2/helloworld/hello_world.go)
**A follow up PR will be submitted removing the old region tag**
=> fix(functions): new region tag for 1st gen functions sample 

spanner/spanner_snippets/spanner/spanner_delete_data.go
Sync comments on the sample to be consistent with other languages https://cloud.google.com/spanner/docs/samples/spanner-delete-data#spanner_delete_data-java
=> fix: refactor spanner delete_data sample

.github/CODEOWNERS
I am no longer associated with the Media CDN project, so I should no longer be a CODEOWNER.
=> chore: remove justin-mp from /mediacdn CODEOWNERS

discoveryengine/search_test.go, testing/kokoro/earliest-version.cfg, testing/kokoro/latest-version.cfg, testing/kokoro/system_tests.sh
that's go 1.19 - go 1.21
This also includes a `system_test.sh` fix for UID mismatches between the namespaces used by each of our nested containers.
=> feat: Update supported go versions to match cloud SDK

run/testing/h2c.e2e_test.go, run/testing/helloworld.e2e_test.go, run/testing/markdown_preview_editor.e2e_test.go, run/testing/markdown_preview_renderer.e2e_test.go
ioutil.NopCloser and ioutil.ReadAll were deprecated in favor of re-homing these functions in the io package.
This happened in go 1.16.
=> testing(run): migrate ioutil to io functions

bigquery/bigquery_migration_quickstart/main_test.go
We've had multiple failures for this snippet running over time budget, but it's not clear that anything has changed.  PR doubles the timeout for running the quickstart, and hoists the timeout up as a variable rather than inline at the callsite.
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/3567
=> testing(bigquery): double test timeout for migration quickstart

bigquery/bigquery_migration_quickstart/main.go
Quickstart testing is failing with no output.  This change adds more status updates, as it's likely we're dealing with the occasional slow workflow and this should yield more concrete details when it recurs.
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/3567
=> docs(bigquery): add more output to migration quickstart

bigquery/bigquery_migration_quickstart/main.go, bigquery/bigquery_migration_quickstart/main_test.go
BQ migration will occasionally have slow workflows, and the test itself isn't valuable enough to warrant testing the entire lifecycle of a workflow.  Extending the limit further hasn't helped, so this PR alters the criteria for success vs failure.
Success is now based on a workflow being created and not erroring within the timeout.
Fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/3567
=> testing(bigquery): relax migration testing

CONTRIBUTING.md
- Reorganizes content under headings, inspired by the CNCF contributing
template.
- removes redundant style guidance that's captured in the official style guide
- merges testing guidance previously scattered in style section.
- mentions `make` commands instead of `go` commands, to promote consistency
across sample language repos.
=> feat(docs): major revision to the contributing docs.

opentelemetry/instrumentation/app/logger.go, opentelemetry/instrumentation/app/main_test.go, opentelemetry/instrumentation/app/setup.go, opentelemetry/instrumentation/docker-compose.yaml, opentelemetry/instrumentation/otel-collector-config.yaml
Update the OTel example to output logs in Cloud Logging structured log format described in https://cloud.google.com/logging/docs/structured-logging#special-payload-fields. This makes the example code compatible with Cloud Logging agents in GKE/GCE/Cloud Run etc.
I also updated the OTel config to mimic Cloud Logging agents for the example.
cc @dashpole
=> feat(otel): use Cloud Logging structured log conventions

appengine/go.mod, appengine/go.sum, appengine/go11x/cloudsql/app.yaml, appengine/go11x/cloudsql/go.mod, appengine/go11x/helloworld/app.yaml, appengine/go11x/helloworld/go.mod, appengine/go11x/pubsub/authenicated_push/app.yaml, appengine/go11x/tasks/handle_task/app.yaml, appengine/go11x/tasks/handle_task/go.mod, appengine/go11x/warmup/app.yaml, appengine/go11x/warmup/go.mod, appengine/go11x/warmup/go.sum
`gcloud` throws deprecation warnings when deploying an app with the  `go115` runtime.
=> chore: Update App Engine samples to the go121 runtime

vertexai/safety-settings-multimodal/safety-settings-multimodal.go, vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
Also make it generally more consistent with the multimodal sample
=> fix(vertexai): use gs:// in safety-settings-multimodal

profiler/export/main.go, profiler/export/main_test.go, profiler/go.mod, profiler/go.sum, testing/kokoro/system_tests.sh
Adds test for the ListProfiles API sample for Google Cloud Profiler.
*Due to a protobuf registration conflict between the profiler agent and profiler client library, currently to run the test successfully,* `GOLANG_PROTOBUF_REGISTRATION_CONFLICT` *environment variable needs to be set.* 
Run tests locally via -  
```
GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn go test -v
```
- This test requires Cloud Profiler API to be enabled to pass.
=> test(profiler): add tests for ListProfiles sample

.github/workflows/go.yaml
diffs are caused by 1.22's introduction of the 'toolchain' directive.
`go get toolchain@none` explicitly removes the toolchain lines, which cause build errors in prior versions.
Part of #3739
=> fix: use go1.21, without a toolchain directive-  avoiding diffs in go.mod

storage/objects/objects_test.go
Adds a retry around the signed URL http calls. Moves code around a bit so that only the necessary bits are retried.
Fixes #3737
=> test(storage): add retry to flaky SignedURL test

storage/service_account/hmac/hmac_test.go
Retry as HMAC key updates can take up to 3 minutes to propagate.
Fixes #3751
=> test(storage): add retry to HMAC key deletion

opentelemetry/instrumentation/app/logger.go, opentelemetry/instrumentation/docker-compose.yaml, opentelemetry/instrumentation/otel-collector-config.yaml
Based on my testing, logging agents will prefix trace ids with the required projects/my-project/traces prefix if it isn't present.  This means we can simplify our logging code to just use the required attributes.
=> chore(opentelemetry): simplify OpenTelemetry instrumentation logging sample

storage/objects/objects_test.go
I realized this bucket name is identical to the one used by TestObjects, and there have been occasional failures with the error "The specified bucket does not exist". There may be some race condition here so switching to use a different name.
Fixes #3310
=> test(storage): use different bucket for KMS test

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/spanner_transaction_timeout.go
Adds a sample for setting a timeout for an entire read/write transaction when using Spanner. This sample is needed for the Spanner documentation pages, as this is a recurring question from Spanner customers.
=> feat(spanner): add transaction timeout sample

storage/service_account/hmac/hmac_test.go
apierror.APIError does not seem to be picking up the reason for the failure, so use googleapi.Error instead.
Fixes #3802
=> test(storage): unflake HMAC test again

pubsub/subscriptions/subscription_test.go
We cleanup stale resources at the start of each test run. Currently, an error message is printed out when a delete operation fails, but often times this is just a `not found` error. Making this fire and forget (not checking returned error) is safe since the stale resources can be deleted in a future test invocation.
Fixes #3970
=> test(pubsub): make resource cleanup fire and forget

opentelemetry/instrumentation/app/logger.go, opentelemetry/instrumentation/app/logger_test.go, opentelemetry/instrumentation/otel-collector-config.yaml
- Updated the slog handler to print levels/severities matching the [LogSeverity enum](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity), which the logging agents can parse. The only changes required were `WARN` -> `WARNING`. The agent [may also parse other common severity strings](https://cloud.google.com/logging/docs/structured-logging#structured_logging_special_fields:~:text=The%20Logging%20agent%20attempts%20to%20match%20a%20variety%20of%20common%20severity%20strings%2C%20which%20includes%20the%20list%20of%20LogSeverity%20strings%20recognized%20by%20the%20Logging%20API.), but those other strings are not documented.
- Updated the OTel collector config to parse the LogSeverity enum values and manually verified that they are mapped correctly to Cloud …
=> fix(otel-instrumentation): fix severity mapping to work with Cloud Logging agent

functions/tips/lazy.go, functions/tips/scope.go, run/authentication/auth.go, run/markdown-preview/editor/render.go, run/system_package/graphviz.go
Removed these tags:
run_tips_global_lazy
run_tips_global_scope
run_service_to_service_auth
run_secure_request
run_secure_request_do
run_system_package_handler
run_system_package_exec
Manually searched docs and confirmed no references remain.
=> chore(fixit): remove redundant region tags

eventarc/generic/Dockerfile, eventarc/pubsub/Dockerfile, run/grpc-ping/Dockerfile, run/grpc-server-streaming/Dockerfile
Removes unused region tags: 
eventarc_generic_dockerfile
eventarc_pubsub_dockerfile
cloudrun_grpc_dockerfile
run_grpc_dockerfile
=> fix(cloudrun): remove unused region tags

videointelligence/annotate/logo_detection.go
Fixes Internal b/345846588
This sample is using the deprecated ioutil package. The functions provided by ioutil were migrated to the io or os packages in Go 1.16. This fix updates to the appropriate os functions by checking the deprecation notices for used functions in https://pkg.go.dev/io/ioutil. See an example of this change at https://github.com/GoogleCloudPlatform/golang-samples/pull/4184.
=> fix(videointelligence): update ioutil reference to os

aiplatform/snippets/import_data_image_classification.go, dlp/snippets/deid/deid_table_fpe.go, dlp/snippets/inspect/inspect_image_all_infotypes.go, media/videostitcher/get_cdn_key.go, profiler/export/main.go, securitycenter/muteconfig/update_mute_rule.go, spanner/spanner_snippets/spanner/spanner_update_database.go, speech/snippets/transcribe_diarization.go, speech/snippets/transcribe_diarization_beta.go, speech/snippets/transcribe_model_selection_gcs.go, speech/snippets/transcribe_streaming_v2.go, speech/snippets/transcribe_streaming_v2_explicit_decoding.go, vertexai/function-calling/functioncalling.go, vertexai/multimodal-multiple/multiple-multimodal.go, vertexai/multimodal-video/multimodalvideo.go, vertexai/safety-settings-multimodal/safety-settings-multimodal.go, vertexai/token-count/tokencount.go
See https://go.dev/wiki/ErrorValueFAQ#i-am-already-using-fmterrorf-with-v-or-s-to-provide-context-for-an-error-when-should-i-switch-to-w
Change applied accross many samples, where the code was returning an `error` by wrapping another `error` using `fmt.Errorf` and the verb `%v`.
Some other uses of `%v` are not in the scope of this PR:
- When using `log.Printf` (because `log.Printf` does not support `%w`)
- When using `*testing.T.Errorf` (because `*testing.T.Errorf` does not support `%w`)
- When using `*testing.T.Fatalf` (because `*testing.T.Fatalf` does not support `%w`)
- When the argument has a non-error type
=> fix: prefer using fmt.Errorf with %w

documentai/documentai_quickstart/main.go
=> fix: update practices from deprecated ioutil to os

compute/address/assign_static_address_to_new_vm.go, compute/compute_test.go, compute/create_instance.go, compute/create_instance_from_template_test.go, compute/create_instance_from_template_with_overrides.go, compute/custom-hostname-instance/create_instance_with_custom_hostname.go, compute/custom-hostname-instance/instance_hostname_test.go, compute/instance-templates/create-instance-templates/create_instance_templates_test.go, compute/instances/create-start-instance/create_instance_from_public_image.go, compute/instances/create-start-instance/create_instance_with_additional_disk.go, compute/instances/create-start-instance/create_instance_with_local_ssd.go, compute/instances/create-start-instance/create_instance_with_snapshotted_data_disk.go, compute/instances/create-start-instance/create_instance_with_subnet.go, compute/instances/custom-machine-type/create_custom_machine_type.go, compute/instances/custom-machine-type/create_shared_with_helper.go, compute/instances/custom-machine-type/create_with_helper.go, compute/instances/custom-machine-type/create_without_helper.go, compute/instances/custom-machine-type/extra_mem_without_helper.go, compute/instances/preventing-accidental-vm-deletion/create_instance.go, compute/start_stop_instances_test.go
This family is no longer available, so all these compute tests are
currently broken.
=> fix(compute): debian-10 image family EoL.

.github/CODEOWNERS
Add [`GoogleCloudPlatform/gcp-security-command-center`](https://github.com/orgs/GoogleCloudPlatform/teams/gcp-security-command-center) team as codeowners for Security Command Center samples.
Kindly provide the team with write permission.
=> chore: update CODEOWNERS to add SCC team

internal/cloudrunci/cloudrunci.go
Reported by staticcheck: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
=> fix(internal): Printf with non-constant format arg

aiplatform/snippets/embeddings.go, aiplatform/text-predict/text.go
Adding `generativeaionvertexai_` region tags to replace old `aiplatform_`
In near future GenAI code samples, will only use `generativeaionvertexai_` region tag prefix.
=> docs(generativeai): add region tags for code samples

firestore/save_test.go, firestore/save_transaction_document_update_conditional.go
=> docs(samples): passing data out of firestore transaction in go

cloudsql/mysql/database-sql/connect_tcp.go, cloudsql/mysql/database-sql/go.mod
Addresses https://github.com/GoogleCloudPlatform/golang-samples/security/code-scanning/5
in order for the sample to work, requires this to be set to true. Not a pattern we'd want to encourage in use so adding a comment to help encourage change when copied.
=> fix: address the use of InsecureSkipVerify in sample

dataflow/flex-templates/wordcount/wordcount.go
Fixes failing [wordcount.go](https://btx.cloud.google.com/invocations/d26822fa-f42d-4e76-b4f1-6afd2854c48e/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fpresubmit%2Flatest-version;config=default/log)
```
failed to decode userfn
caused by:
github.com/GoogleCloudPlatform/golang-samples/dataflow/flex-templates/wordcount.formatFn not found. Register DoFns and functions with the the beam/register package.
2024/08/05 18:32:20 ERROR ProcessBundle failed: 	invalid bundle desc: stage-004
```
=> fix: wordcount.go - register DoFns with the the beam/register package

vertexai/multimodal-pdf/pdf.go, vertexai/multimodal-pdf/pdf_test.go
Removing redundant structure and put the values from the test directly to the sample
=> fix: simpify sample structure

dlp/snippets/inspect/inspect_string_rep.go, dlp/snippets/inspect/inspect_string_rep_test.go
=> feat(dlp): Add code sample for using REP endpoint

pubsub/subscriptions/pull_exactly_once_delivery.go, pubsub/topics/publish_ordering.go, pubsub/topics/publish_resume_ordering.go
Exactly once delivery is best set with a locational endpoint. This adds the `WithEndpoint` option to the exactly once sample, and fixes the comments for ordering samples.
---
When you run your application within Google Cloud, it typically connects to the Pub/Sub endpoint in the same region by default. Therefore, running your application in a single region within Google Cloud generally ensures you are interacting with a single region.
If you are running your publisher application outside of Google Cloud or in multiple regions, you can guarantee you are connecting to a single region using a [locational endpoint](https://cloud.google.com/pubsub/docs/reference/service_apis_overview#pubsub_endpoints) when configuring your Pub/Sub client. All location endpoints for Pub/Sub point to single …
=> fix(pubsub): add locational endpoint for exactly once sample

vertexai/multimodal/multimodal.go, vertexai/multimodal/multimodal_test.go
Moved attributes inside sample function to follow "copy-paste-runnable" principle
=> fix: moved attributes inside sample

run/go.mod, run/go.sum, run/testing/pubsub.e2e_test.go
Beginning with Go 1.21, `go mod tidy` updates `go.mod` with Go version in `x.y.z` format. Our CI builds currently tests with Go 1.20 as the earliest version, which expects `x.y` format. 
This mismatch creates a conflict because our lint/vet action currently uses 1.21 (and thus fail after after detecting a change after running `go mod tidy` if using the `x.y` format) or else fail in the Kokoro build on Go 1.20 if using the `x.y.z` format.
This original version of this PR attempted to remove the mismatch by (temporarily) downgrading the version of go used for linting, but this caused go vet to fail. The latest version of this PR simply cherry picks the last commit that caused this to break with the last working version of main rebased on HEAD (instead of the default merge that GitHub did to …
=> fix: resolve breaking build

batch/create_with_persistent_disk.go, batch/create_with_persistent_disk_test.go
Created a sample to demonstrate how can persistent disk be attached to batch
=> feat: batch_create_persistent_disk_job sample created

compute/reservations/reservations_test.go
Fixes context in tests for reservation snippets
=> fix: moved context inside functions

.github/CODEOWNERS
Fixes b/368475540, parallels https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3870
=> chore(CODEOWNERS): Add cloud-samples-infra team to repo config ownership

.github/CODEOWNERS
Removes teams that are no long in active use. Any rows that would then be limited to inherited rules were removed. This included wiping the "Assisted" section because there was no active CODEOWNER team.
Fixes b/364335594 for golang-samples.
=> chore(CODEOWNERS): Remove unused teams

batch/create_with_local_ssd.go, batch/create_with_persistent_disk.go
Issues with other PRs (e.g. #4408 )
Documentation of these settings:
https://cloud.google.com/go/docs/reference/cloud.google.com/go/batch/latest/apiv1/batchpb#cloud_google_com_go_batch_apiv1_batchpb_ComputeResource
=> fix: changes batch samples to 1000 CPU millis

run/pubsub/main.go, run/pubsub/main_test.go
Fixes b/368461774
* ioutil is deprecated so move to io
* while io.ReadAll closes r.Body internally, recommended practice is to explicitly do resource management and provide clarity.
=> fix(cloudrun): update practices from deprecated ioutil to io

compute/instance-templates/create-instance-templates/create_instance_templates_test.go, compute/instance-templates/create-instance-templates/create_regional_template.go, compute/instance-templates/create-instance-templates/delete_regional_template.go, compute/instance-templates/create-instance-templates/get_regional_template.go
Created basic operations for regional templates
=> feat: regional template operations samples

vertexai/batch-predict/batch_code_predict.go, vertexai/batch-predict/batch_text_predict.go, vertexai/snippets/gemini_translate.go
Two recent PRs -- #4417 and #4413 -- were merged without the `defer client.Close()` line of code. This PR adds those lines to the samples.
=> fix: added defer client.Close() to Vertex samples

compute/reservations/consume_specific_shared_reservation.go, compute/reservations/mock_shared_project.go, compute/reservations/reservations_test.go
Sample for https://cloud.google.com/compute/docs/instances/reservations-consume#consuming_a_specific_shared_reservation
=> feat: consume specific shared reservation sample

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/spanner_create_instance_with_autoscaling_config.go, spanner/spanner_snippets/spanner/spanner_create_instance_with_processing_units.go
Fix spanner tests by introducing suitable Edition parameters in instance
creation.
Editions are a product change that caused test breakage.
=> fix(spanner): add Edition to created databases.

dataproc/dataproc_test.go, dataproc/quickstart/quickstart_test.go
- **chore: skip dataproc for failing tests (tracked in #4350)**
- **chore: skip dataproc quickstart too**
=> fix: skip dataproc tests for #4330

testing/docker/cloudbuild.yaml, testing/kokoro/latest-version.cfg, testing/kokoro/trampoline.sh
Update kokoro image builds, and the latest-version kokoro build to use Artifact
Registry.
The container images exist for go 1.21 and 1.23 already.
Part of #4228
=> feat: AR migration for kokoro, pt 1

testing/kokoro/earliest-version.cfg
Switch kokoro's 'earliest-version' builds to use the 1.21 image from Artifact
Registry instead of container registry, which is in turndown.
Part of #4228
=> feat: migrate earliest-version off of Container Registry

.github/workflows/go.yaml, getting-started/gopher-run/cmd/main.go
the `actions/setup-go` action has a ['stable'
alias](https://github.com/actions/setup-go?tab=readme-ov-file#using-stableoldstable-aliases)
that we can use for this test.
Since the goal of the workflows is fast feedback on PRs, using the most recent
stable version seems reasonable. Kokoro tests will still ensure compatability
with our minimum and maximum versions.
We can also unpin goimports, since we're using go >1.22.
Fixes #4374
=> chore: upgrade GHA workflows to use stable go

securitycenter/clientv2/create_client_with_endpoint.go
I added this sample in #4419. See that PR for the rationale for creating both regional and global clients. However, when I sent a PR for the Java equivalent of this sample, the Java reviewer wouldn't accept a sample that created both regional and non-regional clients.
I still think it would be useful to show the creation of both clients, but I think it's more important to make the samples do approximately the same thing in each language.
=> feat(security-command-center): simplify "create client with endpoint" sample

dlp/snippets/deid/deid_table_fpe.go
It looks like there is some extraneous string in a comment; this PR removes the extraneous stuff.
=> chore: remove extraneous string

cloudsql/mysql/database-sql/connect_tcp.go
=> fix: update practices from deprecated ioutil to io

functions/functionsv2/hellostorage/hello_storage.go
This PR demonstrates a potential approach towards EventArc/Cloud Event code samples that need to unmarshal JSON event data.
Note: unfortunately, the `protojson.Unmarshal()` method throws an unexported error struct. Otherwise, we could use `Errors.Is()` or `Errors.As()` to listen for an unknown field error. [This is a known issue.](https://github.com/golang/protobuf/issues/1412)
=> feat(eventarc): improved error handling

healthcare/dicomweb_instance_store.go
=> fix: update practices from deprecated ioutil to io/os

eventarc/storage_handler/handler.go, eventarc/storage_handler/handler_test.go, functions/functionsv2/firebase/hellofirestore/hellofirestore.go, functions/functionsv2/firebase/upper/upper.go, functions/functionsv2/imagemagick/imagemagick.go, functions/functionsv2/ocr/app/process.go
This PR sets all of the calls to `protojson.Unmarshal()` to `DiscardUnknown` fields. This will reduce the likelihood of customers encountering errors in their deployed functions. This PR also adds a comment explaining the usage of the `DiscardUnknown` field.
=> fix(eventarc): sets protojson to DiscardUnknown

batch/create_with_custom_network.go, batch/create_with_custom_network_test.go
Samples, which demonstrates how to create batch with custom network and subnetwork. Documentation reference [here](https://cloud.google.com/batch/docs/specify-job-network#create-job-specific-network)
=> feat: batch create with custom network sample

batch/create_with_nfs.go, batch/create_with_nfs_test.go
Samples, which demonstrates how to create batch with custom network and subnetwork. Documentation reference [here](https://cloud.google.com/batch/docs/create-run-job-storage#use-nfs)
=> feat: create batch with nfs sample

batch/create_with_labels_runnable.go, batch/create_with_labels_runnable_test.go
Samples, which demonstrates how to create batch with custom network and subnetwork. Documentation reference [here](https://cloud.google.com/batch/docs/organize-resources-using-labels#define-labels-runnables)
=> feat: create batch with custom runnable labels sample

batch/create_with_custom_network.go, batch/create_with_custom_network_test.go, batch/create_with_job_labels.go, batch/create_with_job_labels_test.go
Samples, which demonstrates how to create batch with labels on the job level. Documentation reference [here](https://cloud.google.com/batch/docs/organize-resources-using-labels#define-labels-job)
=> feat: create job with custom labels sample

batch/create_with_allocation_policy_labels.go, batch/create_with_allocation_policy_labels_test.go
Samples, which demonstrates how to create batch with labels on the policy level. Documentation reference [here](https://cloud.google.com/batch/docs/organize-resources-using-labels#define-labels-resources)
=> feat: create batch with custom labels for policy sample

iam/quickstart/quickstart.go
Includes changing "member" to "principal" and linking to principal identifiers page instead of specifying recommended format.
I left "member" when it referred to the field in the role binding, since that field is still called "members."
Please **merge** this PR for me once it is approved
=> docs(iam): Update quickstart.go comments

compute/instances/create-start-instance/create_instance_with_replicated_boot_disk.go
The tag differs from file name. Correcting the region tag to be consistent with the sample.
=> fix: wrong tag correction

run/system_package/Dockerfile
According to the "deleting sample/region decision tree" decided to delete the region "run_system_package_ubuntu" because it was inner nested to the valid region "cloudrun_system_package_ubuntu"
Fixes [b/347348198](https://b.corp.google.com/issues/347348198)
=> fix(cloudrun): delete old region tag run_system_package_ubuntu

speech/snippets/model_selection.go
Delete old region tag "imports"
Fixes [b/347826294](http://b/347826294)
=> fix(speech): delete old region tag "imports"

jobs/v3/howto/histogram_search_sample.go
According to the "deleting sample/region decision tree" decided to delete the region "histogram_search" because it was inner nested to the valid region "job_histogram_search"
Fixes [b/347825492](https://b.corp.google.com/issues/347825492)
=> fix(job): delete old region tag histogram_search

run/hello-broken/Dockerfile
Delete old region tag broken_dockerfile because is inner nested with correct one cloudrun_broken_dockerfile
Fixes [b/347348340](https://b.corp.google.com/issues/347348340)
=> fix(run): delete old region tag broken_dockerfile

language/analyze/analyze.go
Delete old region tag "imports"
Fixes [b/347826215](https://b.corp.google.com/issues/347826215)
=> fix(language): delete old region tag "imports"

testing/kokoro/system_tests.sh
Disable lingering flakybot reporting on periodic builds. Flakybot itself was disabled for this repo several months ago.
=> fix: disable flakybot reporting

CONTRIBUTING.md, appengine/go11x/tasks/handle_task/Dockerfile, appengine_flexible/go115_and_earlier/websockets/static/index.html, appengine_flexible/websockets/static/index.html, bigtable/helloworld/main.go, cloudsql/mysql/database-sql/Dockerfile, cloudsql/postgres/database-sql/Dockerfile, cloudsql/sqlserver/database-sql/Dockerfile, eventarc/audit_storage/Dockerfile, eventarc/generic/Dockerfile, eventarc/pubsub/Dockerfile, getting-started/gopher-run/Dockerfile, memorystore/redis/cloud_run_deployment/Dockerfile, opentelemetry/instrumentation/app/logger.go, run/grpc-ping/Dockerfile, run/grpc-ping/connection.go, run/grpc-server-streaming/Dockerfile, run/hello-broken/Dockerfile, run/helloworld/Dockerfile, run/image-processing/Dockerfile, run/logging-manual/Dockerfile, run/markdown-preview/editor/Dockerfile, run/markdown-preview/renderer/Dockerfile, run/pubsub/Dockerfile, run/sigterm-handler/Dockerfile, run/system_package/Dockerfile, testing/docker/README.md, testing/kokoro/configure_cloudsql.bash
The language's proper name is "Go", not "Golang".
- [x ] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x ] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x ] Please **merge** this PR for me once it is approved
=> chore(many): rename Golang to Go

appengine_flexible/static_files/static/main.css
Migrate region "examples" to "gae_flex_examples_css_go"
Fixes [b/347342869](https://b/347342869)
=> fix(gae): migrate region example to new one

endpoints/getting-started/k8s/esp_echo_http.yaml
Delete old regions
Fixes
[b/347825430](http://b/347825430)
[b/347825408](http://b/347825408)
=> fix(appengine): delete old region tags

docs/appengine/storage/app.go
Migration step 1
Migrate all region tags adding the "gae_storage_" prefix
Fixes [b/387483288](https://b/387483288)
=> fix(gae): add new region tags with "gae_storage_" prefix

run/pubsub/Dockerfile
Remove old region tag pubsub_dockerfile because it is inner nested to the correct one cloudrun_pubsub_dockerfile
Fixes [b/347348576](https://b.corp.google.com/issues/347348576)
=> fix(run): remove old region tag pubsub_dockerfile

secretmanager/create_secret.go, secretmanager/create_secret_ttl.go, secretmanager/go.mod, secretmanager/secretmanager_test.go
chore(secretmanager): add optional argument ttl to createSecret and updated tests with/without ttl
Fixes #[b/384052840](http://b/384052840)
=> chore(secretmanager): add optional argument ttl to createSecret

run/custom-metrics/main.go
Align SchemaURL versions when calling Merge function
=> fix(run): align schemas url versions

go.work
=> fix: update go.work to match minimum 1.22

docs/appengine/datastore/entities/entities.go
Migrate region tags by adding "gae_datastore" prefix in order to associate them with an official GCP product
Fixes
[b/391176362](http://b/391176362)
[b/389106593](http://b/389106593)
[b/391176883](http://b/391176883)
[b/391175192](http://b/391175192)
[b/391176374](http://b/391176374)
[b/391176575](http://b/391176575)
[b/391175195](http://b/391175195)
[b/391176890](http://b/391176890)
=> fix(gae): add "gae_datastore" prefix

cloudsql/mysql/database-sql/go.mod, cloudsql/mysql/database-sql/go.sum, cloudsql/postgres/database-sql/go.mod, cloudsql/postgres/database-sql/go.sum, cloudsql/sqlserver/database-sql/go.mod, cloudsql/sqlserver/database-sql/go.sum
Fixed a couple bugs in the Cloud SQL Go Connector where the user agent and quota project options were not working.
=> chore(deps): bump Cloud SQL Go Connector to v1.14.1

docs/appengine/datastore/indexes/indexes.go
Migrate region tags adding "gae_datastore" prefix in order to associate them with an official GCP product
Fixes
[b/392128463](http://b/392128463)
[b/389106598](http://b/389106598)
=> chore(gae): migrate regions indexes.go

docs/appengine/taskqueue/taskqueue.go
Migrate region tag "taskqueue_host" by adding "gae_" prefix in order to associate it with an official GCP product.
Fixes
[b/392110136](http://b/392110136)
=> chore(gae): migrate region taskqueue_host

docs/appengine/taskqueue/taskqueue.go
Rename old regions by adding a "gae_" prefix to associate them with an official GCP product.
Fixes
[b/389112134](http://b/389112134)
[b/392110330](http://b/392110330)
[b/392110639](http://b/392110639)
=> chore(gae): rename regions taskqueue.go

docs/appengine/taskqueue/taskqueue.go
Delete old region tag "taskqueue_host" at docs/appengine/taskqueue/taskqueue.go
Fixes
[b/392110136](http://b/392110136)
=> fix(gae): delete old region taskqueue_host

spanner/spanner_snippets/spanner/integration_test.go, spanner/spanner_snippets/spanner/spanner_create_instance_with_asymmetric_autoscaling.go
=> feat(spanner): add spanner sample snippet for creating asymmetric autoscaling instance

endpoints/getting-started/openapi-appengine.yaml
Start migrating region "swagger" to new region tag "endpoints_swagger_appengine_yaml_go" in order to associate it with an official GCP product
Fixes
[b/393186351](https://b.corp.google.com/issues/393186351)
=> chore(endpoints): migrate region "swagger" from openapi-appengine.yaml

endpoints/getting-started/openapi.yaml
Start migrating region "swagger" to new region tag "endpoints_swagger_yaml_go" in order to associate it with an official GCP product
Fixes
[b/393185065](https://b.corp.google.com/issues/393185065)
=> chore(endpoints): migrate region "swagger" from openapi.yaml

docs/appengine/datastore/projectionqueries/projectionqueries.go
Migrate regions by adding "gae_datastore" prefix to regions from file docs/appengine/datastore/projectionqueries/projectionqueries.go
Fixes
[b/392146363](http://b/392146363)
[b/392145933](http://b/392145933)
[b/392146306](http://b/392146306)
[b/391185644](http://b/391185644)
[b/391186679](http://b/391186679)
=> chore(gae): migrate region tags from projectionqueries.go

docs/appengine/datastore/projectionqueries/projectionqueries.go
Migrate regions by adding "gae_datastore" prefix to regions from file docs/appengine/datastore/projectionqueries/projectionqueries.go
Fixes
[b/392146363](http://b/392146363)
[b/392145933](http://b/392145933)
[b/392146306](http://b/392146306)
[b/391185644](http://b/391185644)
[b/391186679](http://b/391186679)
=> fix(gae): amend region tag renaming "gae_grouping_grouping"

endpoints/getting-started/deployment.yaml
Remove old region "esp". Seems like it's part of an undone migration
Fixes
[b/393614531](https://buganizer.corp.google.com/issues/393614531)
=> chore(endpoints): remove old region "esp" at endpoints/getting-started/deployment.yaml

run/helloworld/Dockerfile
Delete old region tag 'run_helloworld_dockerfile', it seems like a started migration process didn't finish.
Fixes [b/347348196](https://b.corp.google.com/issues/347348196)
=> fix(cloudrun): delete old region tag run_helloworld_dockerfile

docs/appengine/datastore/indexes/indexes.go
Delete old region tags
- exploding_index_example_3
- unindexed_properties
Fixes
[b/392128463](http://b/392128463)
[b/389106598](http://b/389106598)
=> chore(gae): delete old region tags from indexes.go

run/pubsub/Dockerfile
Delete old region tag "cloudrun_pubsub_dockerfile" from run/pubsub/Dockerfile
Fixes
b/388068402
=> chore(cloudrun): delete old region tag "cloudrun_pubusub_dockerfile"

docs/appengine/datastore/indexes/index.yaml, docs/appengine/datastore/projectionqueries/projectionqueries.go
Migrate region tags from docs/appengine/datastore/indexes/index.yaml in order to align to pattern "product_regiontag_typeoffile_language"
Fixes
b/394594341
b/394594345
=> chore(gae): migrate region tags from docs/appengine/datastore/indexes/index.yaml

profiler/hotmid/main.go
Delete unused region tag "hotapp" at profiler/hotapp/main.go
Internal:
b/347348734
=> chore(profiler): delete unused region tag "hotmid"

appengine/go11x/helloworld/helloworld.go
Migrate region "import" to "gae_go111_import" from appengine/go11x/helloworld/helloworld.go 
Internal b/395128421
=> chore(gae): migrate region "import" from ../helloworld/helloworld.go

endpoints/getting-started/openapi-appengine.yaml
Delete old region "swagger" as the final step for migrating a region tag
Fixes
b/393186351
=> chore(endpoints): delete old region tag "swagger"

appengine/go11x/helloworld/helloworld.go
Delete old region "import" from appengine/go11x/helloworld/helloworld.go 
Internal b/395128421
=> chore(gae): delete old region "import" from ../helloworld/helloworld.go

cloudsql/mysql/database-sql/connect_connector.go, cloudsql/mysql/database-sql/connect_connector_iam_authn.go, cloudsql/postgres/database-sql/connect_connector.go, cloudsql/postgres/database-sql/connect_connector_iam_authn.go, cloudsql/sqlserver/database-sql/connect_connector.go
Enabled lazy refresh for the Go Cloud SQL connector (Postgres, MySQL, and SQL Server).
=> feat(cloud-sql): add lazy refresh for csql: mysql, sql server and postgres

language/analyze/analyze.go, language/go.mod
- Delete unused region tag "language_imports" 
- Update deprecated library "github.com/golang/protobuf/proto"" to recommended "google.golang.org/protobuf/proto"
Fixes Internal b/397199209
=> fix(language): delete unused region tag "language_imports"

vision/label/label.go
Delete unused region tag "init" from vision/label/label.go
Fixes Internal b/397960375
=> chore(vision): delete unused region tag "init"

appengine/go11x/helloworld/helloworld.go
Amend mistaken deleted region tag "gae_go111_import". It appears in documentation
=> fix(gae): add deleted region tags

docs/appengine/taskqueue/app.yaml
- In order to create an association between GCP products and region tags, decided to add "gae_" prefix.
- Add "_yaml_go" suffix for following the pattern "product_regiontag_typeoffile_language" in region tags when dealing with files with different extension than the language's native.
=> chore(gae): rename region "securing_urls"

appengine/go11x/helloworld/helloworld.go
Following the PR #5161, this one deletes the old regions
Fixes Internal:
- b/397700944 
- b/397694570 
- b/397700064 
=> fix(gae): delete old region tags from helloworld

texttospeech/synthesize_speech/audio_profile.go
- End of migration of tag "texttospeech_audio_profile" in order to create consistency between the other langauges and associate it with an official GCP product
Part of PR #5185
Fixes Internal b/399175687
=> chore(tts): delete old region texttospeech_audio_profile

endpoints/getting-started/deployment.yaml
Delete old region tag "endpoints_esp".
Follow-up of #5213
Fixes Internal b/393613845
=> chore(endpoints): delete old region tag "endpoints_esp"

run/hello-broken/Dockerfile
Delete old region "cloudrun_broken_dockerfile", last part of migration from PR #5215
Fixes Internal b/393125543
=> chore(cloudrun): delete old region cloudrun_broken_dockerfile

run/helloworld/Dockerfile
Start migrating region "cloudrun_helloworld_dockerfile" to "cloudrun_helloworld_dockerfile_go" in order to follow pattern "product_regiontag_typeoffile_language" for files whom type is different from the language context
Fixes Internal b/393156999
=> chore(cloudrun): migrate region "cloudrun_helloworld_dockerfile"

run/image-processing/Dockerfile
Start migrating region tag "cloudrun_imageproc_dockerfile_imagemagick" to "cloudrun_imageproc_dockerfile_go" in order to align with pattern "product_regiontag_typeoffile_language" when dealing with file whom type is different from the language's context.
Fixes Internal b/393178651
=> chore(cloudrun): migrate region tag "cloudrun_imageproc_dockerfile_imagemagick"

run/system_package/Dockerfile
Last step of migrating the region tag "cloudrun_system_package_ubuntu" to "cloudrun_system_package_ubuntu_dockerfile_go" to align with the pattern "product_region_typeoffile_language" for files with different types than the language context.
Following PR #5214 
Fixes Internal b/393126836
=> chore(cloudrun): delete old region tag "cloudrun_system_package_ubuntu"

run/helloworld/Dockerfile
Delete old region "cloudrun_helloworld_dockerfile"
Fixes Internal b/393156999
=> chore(cloudrun): delete old region tag "cloudrun_helloworld_dockerfile"

genai/content_cache/contentcache_create_with_txt_gcs_pdf.go, vertexai/batch-predict/gemini_batch_predict_bq.go, vertexai/batch-predict/gemini_batch_predict_gcs.go, vertexai/context-caching/contextcaching_create.go, vertexai/context-caching/contextcaching_test.go, vertexai/controlled-generation/controlledgen_schema6.go, vertexai/controlled-generation/controlledgen_schema_enum.go, vertexai/controlled-generation/controlledgen_schema_test.go, vertexai/function-calling/functioncalling.go, vertexai/function-calling/functioncalling_basic.go, vertexai/function-calling/functioncalling_parallel.go, vertexai/function-calling/functioncalling_test.go, vertexai/multimodal-video-with-audio/multimodalvideoaudio.go, vertexai/multimodal-video-with-audio/multimodalvideoaudio_test.go, vertexai/safety-settings/safety-settings.go, vertexai/safety-settings/safety-settings_test.go, vertexai/snippets/gemini_translate.go, vertexai/snippets/text_input.go, vertexai/snippets/try_gemini.go, vertexai/snippets/try_gemini_test.go, vertexai/stream-multimodality-basic/streammultimodalitybasic_test.go, vertexai/stream-text-basic/streamtextbasic_test.go, vertexai/token-count/tokencount.go, vertexai/token-count/tokencount_multimodal.go, vertexai/token-count/tokencount_test.go
using gemini 2.0 flash instead of gemini 1.5 or older models
Fixes b412651154
=> feat: update gemini mode name

run/pubsub/main.go
Remove the comment line that may confuse the expected payload from a PubSubMessage, and rename the PubSubMessage struct to PubSubPayload to better reflect its purpose.
Fixes b/327536079
=> fix(cloudrun): remove unnecessary comment

run/image-processing/Dockerfile
Rename region tag in order to follow the pattern "product_regiontag_typeoffile_language".
Fixes b/393178651
=> chore(cloudrun): rename new region tag cloudrun_imageproc_imagemagick_dockerfile_go

run/image-processing/Dockerfile
Remove old region "cloudrun_imageproc_dockerfile_imagemagick".
Fixes b/393178651
=> fix(cloudrun): remove old region cloudrun_imageproc_dockerfile_imagemagick

storage/go.mod, storagetransfer/go.mod
Reverts GoogleCloudPlatform/golang-samples#5310
The linter doesn't like this update for some reason?
=> Revert "chore(all): update module github.com/aws/aws-sdk-go to v1.55.7"

pubsub/schemas/commit_avro_schema.go, pubsub/schemas/commit_proto_schema.go, pubsub/schemas/create_avro_schema.go, pubsub/schemas/create_proto_schema.go, pubsub/schemas/create_topic_with_schema.go, pubsub/schemas/create_topic_with_schema_revisions.go, pubsub/schemas/delete_schema.go, pubsub/schemas/delete_schema_revision.go, pubsub/schemas/get_schema.go, pubsub/schemas/get_schema_revision.go, pubsub/schemas/list_schema_revisions.go, pubsub/schemas/list_schemas.go, pubsub/schemas/publish_avro_records.go, pubsub/schemas/publish_proto_messages.go, pubsub/schemas/rollback_schema.go, pubsub/schemas/schemas_test.go, pubsub/schemas/subscribe_avro_records.go, pubsub/schemas/subscribe_proto_messages.go, pubsub/schemas/subscribe_with_avro_schema_revisions.go, pubsub/schemas/update_topic_schema.go
This is part 3 of 3 PRs that will be updating our existing Go Pub/Sub samples to use the new v2 library. This PR focuses on updating schema samples and the tests associated with them.
We are merging these PRs into pubsub-v2-samples-trunk since the v2 library isn't fully released yet.
=> feat(pubsub): rewrite v2 schema samples 

.github/flakybot.yaml
Addresses b/434770885 (Complete flakybot deprecation) for this repo.
=> chore: remove flakybot configuration (long retired)

badfiles_test.go
Needed to allow local test runs when using [Jujutsu VCS](https://jj-vcs.github.io/).
=> chore: allow .jj repos in badfiles check

pubsub/v1samples/subscriptions/subscription_test.go
TestCreateSubscriptionWithSMT has been failing in repo-wide builds with a nil topic error. 
* update getOrCreateTopic test function to avoid race between checking topic existence and creating the topic. (tests are using t.Parallel(), so it can happen across tests)
* in TestCreateSubscriptionWithSMT:
* use shared getOrCreateTopic rather than local code. (local code had a bug which only occured when topic didn't already exist.)
* use test specific topicID
* use only one Retry block in body of the test so new topic both lives long enough to run the test and is cleaned up by defer.
Helps fix tests failing in Renovate PR #5225
=> chore(pubsub): Topic race condition; SMT test failure

storage/acl/acl_test.go, storage/buckets/buckets_test.go, storage/control/folders_test.go, storage/objects/objects_test.go
Fixes storage tests blocking test suite success. Skipping some tests due to permission changes on the Cloud projects. See b/445769988 for details and follow up needed to unskip.
=> chore: skip some storage tests due to permissions changes
