GoogleCloudPlatform/golang-samples

- getting-started/bookshelf/app/app.go
- getting-started/bookshelf/config.go
@adg @shun-fan @okdave @gmlewis
> getting-started/bookshelf: Update use of Storage API.

- .travis.yml
Change-Id: I448af328fd8b8d8c60e7738a475bc113ef651ffc
> travis: don't run system tests for pull requests

- docs/sql/listinstances/listinstances.go
- docs/sql/listinstances/listinstances_test.go
> docs: add sql/listinstances example

- license_test.go
- nothing.go
> golang-samples: add test for license headers

- .travis.yml
> travis: only build master branch

- datastore/tasks/tasks.go
> Fixes comment about fetching entities.

- docs/appengine/articles/memcache_best_practices/app.go
Hi, @broady 
Can you have a look?
> Add code for Best Practices for App Engine Memcache

- docs/error-reporting/fluent/main.go
Moved from [go/errorreportinggosample](https://goto.google.com/errorreportinggosample)
> docs: move error-reporting/fluent sample

- .travis.yml
- testing/travis/configure_gcloud.bash
FORCE_E2E=true in the commit message will trigger e2e tests even if not
triggered nightly by ci-aeon.
(Yes, it's put in this message intentionally!)
> travis: run e2e tests with ci-aeon or with a special commit message

- docs/managed_vms/helloworld/helloworld.go
- getting-started/helloworld/helloworld.go
One of them might go away eventually. Probably the getting-started one.
> helloworld: merge managed_vms and getting-started helloworld

- docs/managed_vms/datastore/app.yaml
- internal/aeintegrate/aeintegrate.go
- internal/e2e/flexible_test.go
> e2e, aeintegrate: fix datastore test, env variable replacement

- .travis.yml
> travis: disable sendgrid tests

- getting-started/README.md
- internal/aeintegrate/aeintegrate.go
- internal/e2e/README.md
> all: "gcloud app" now out of preview

- monitoring/custommetric/custommetric.go
The API client was changed:
https://code-review.googlesource.com/5259
> monitoring: use pointer for typed value

- docs/appengine/config/appconfig.txt
> Adds the example for specifying the redirect_http_response_code param

- speech/transcript/transcript_test.go
travis build will pass hopefully this time.
/cc @broady
> speech/transcript: fix the failing test

- speech/transcript/transcript.go
- speech/transcript/transcript_test.go
Yes, it's weird that v1beta1 is newer than v1.
> speech/transcript: upgrade to v1beta1 API

- internal/aeintegrate/aeintegrate.go
> aeintegrate: update App Engine dependency

- pubsub/topics/main.go
- pubsub/topics/main_test.go
> pubsub: Add topics

- pubsub/subscriptions/main.go
- pubsub/subscriptions/main_test.go
> pubsub: Add subscriptions

- pubsub/subscriptions/main.go
- pubsub/subscriptions/main_test.go
- pubsub/topics/main.go
Broken by https://code-review.googlesource.com/#/c/7310/.
> pubsub: fix the broken build

- pubsub/subscriptions/main_test.go
> pubsub/subscriptions: make list less flaky

- datastore/snippets/snippet_test.go
Copied verbatim from the gocloud/google-cloud-go repository.
Changed package name, added package level comment, changed the
formatting of the license notice to match the rest of this repository.
> datastore: add snippets

- storage/buckets/main.go
- storage/objects/main.go
Change storage.Done to iterator.Done.
Change CopyTo to CopierFrom.Run.
> storage: update to new storage client

- pubsub/subscriptions/main.go
- pubsub/topics/main.go
We'll eventually remove pubsub.Done.
> pubsub: change pubsub.Done to iterator.Done

- bigquery/syncquery/syncquery.go
> Improve spelling of results

- bigquery/simpleapp/simpleapp.go
- bigquery/simpleapp/simpleapp_test.go
This is to get included in the docs here: https://cloud.google.com/bigquery/create-simple-app-api
> bigquery: add simpleapp example

- datastore/snippets/snippet_test.go
- datastore/tasks/tasks.go
- docs/managed_vms/datastore/datastore.go
- getting-started/bookshelf/db_datastore.go
We will remove the old ones soon.
DO NOT SUBMIT before we announce the changes (some time on October 31).
/cc @adams-sarah @zombiezen
> datastore: change examples to use new key functions

- .travis.yml
- getting-started/bookshelf/pubsub_worker/app.yaml
- internal/aeintegrate/aeintegrate.go
- internal/e2e/flexible_test.go
- testing/all.bash
> e2e: add storage test, use "service" instead of "module", use appspot-preview

- translate/snippets/snippet.go
- translate/snippets/snippet_test.go
Add snippets for
* Creating a client with an API key
* Translating text
* Language detection
* Listing supported languages
> translate: add snippets

- bigquery/snippets/snippet.go
- bigquery/snippets/snippet_test.go
> bigquery/snippets: add exportToGCS

- bigquery/simpleapp/simpleapp.go
- bigquery/snippets/snippet.go
- bigquery/syncquery/syncquery.go
ValueList has been removed. []Value is used instead.
> bigquery: update samples to use []Value

- endpoints/getting-started/README.md
> (minor) filename typo in README

- vision/detect/README.md
- vision/detect/detect.go
- vision/detect/detect_test.go
- vision/detect/generated/gen.go
- vision/detect/generated/sample-template.go
- vision/detect/main.go
Adds new features for Vision API:
* Requesting annotations for public URIs (not just GCS)
* Web annotations
* Document text detection
* Crop hints
Also updates the main program to accept a second parameter to limit
detections.
> vision: add new features (public URI, web, full text, crop hints)

- appengine_flexible/pubsub/pubsub.go
- getting-started/bookshelf/app/app.go
- pubsub/subscriptions/main.go
- pubsub/topics/main.go
Related to https://github.com/GoogleCloudPlatform/google-cloud-go/commit/f4eafa8cbb48e8ef5e23b542c3cb51cd1cbce787.
> pubsub: switch to the new API

- spanner/spanner_quickstart/main.go
Update spanner quick start to correctly refer to the full database path as databaseName
> Update spanner quick start 

- docs/appengine/tools/devserver/app.yaml
- docs/appengine/tools/devserver/devserver.go
We don't currently demonstrate in code how to do this type of check in the docs.
> Add a snippet for how to detect if running in the development server

- translate/snippets/snippet_test.go
> translate/snippets: look for translation of "Go" or "Cute"

- .travis.yml
> travis: 10 parallel tests, use go1.7.5

- kms/quickstart/main.go
To be referenced in
https://cloud.google.com/kms/docs/reference/libraries
> Adds a quickstart sample to cloud-kms.

- speech/livecaption/livecaption.go
The stream will hang and stay open if not closed.
Updates #237.
> speech/livecaption: close stream at EOF

- datastore/datastore_quickstart/main.go
> Minor typo fix

- appengine/bigquery/app.go
> Migrate to new BigQuery client

- spanner/spanner_snippets/snippet.go
https://code-review.googlesource.com/#/c/12852/
Fixes #261.
> spanner: add context param to ReadWriteTransaction

- pubsub/subscriptions/main.go
10 messages that are published are zero-indexed.
This sample never runs to completion as is
cc @broady
> fix off-by-one typo

- getting-started/bookshelf/pubsub_worker/worker.go
- pubsub/subscriptions/main.go
Fix CreateSubscription (and ModifyPushConfig) to conform to recent breaking change in the pubsub client.
> pubsub: update CreateSubscription calls

- docs/appengine/storage/README.md
- docs/appengine/storage/app.go
- docs/appengine/storage/app.yaml
> docs/appengine: move storage sample from google-cloud-go

- container/listclusters/listclusters.go
> container: add listclusters sample

- spanner/spanner_snippets/snippet.go
Use parameter binding in the SQL statement.
> spanner: encourage bind parameters in statements

- pubsub/subscriptions/main.go
Build broken due to changes in https://code-review.googlesource.com/c/14311.
> pubsub: Subscription.ModifyPushConfig is now Subscription.Update

- monitoring/custommetric/custommetric.go
> Improve english, remove extra 's'

- getting-started/bookshelf/db_mysql.go
Fixing the error message raising from mysql but stating "memorydb" wrongly.
> Fix error message for mysql transactions

- language/analyze/README.md
- language/analyze/analyze.go
- language/analyze/analyze_test.go
- language/analyze/entity_sentiment.go
For this page:
https://cloud.google.com/natural-language/docs/beta
> language: add entity sentiment sample

- bigquery/bigquery_quickstart/main.go
- bigquery/snippets/snippet.go
The BigQuery Go package changed to require a metadata parameter.
> bigquery: add new parameter for Dataset.Create

- bigquery/snippets/snippet.go
- bigquery/snippets/snippet_test.go
- bigquery/syncquery/syncquery_test.go
The default changed from legacy SQL to standard SQL, so this SELECT
statement must be updated.
> bigquery: fix tests

- .travis.yml
This provides colorized test output.
> .travis.yml: use github.com/rakyll/gotest

- errorreporting/errorreporting_quickstart/main.go
The API changed recently:
https://code-review.googlesource.com/16090
Update this sample accordingly.
> errorreporting: update for new API

- getting-started/bookshelf/app/auth.go
Signed-off-by: Hui Kang <kangh@us.ibm.com>
> Fix error message

- spanner/spanner_snippets/snippet.go
- spanner/spanner_snippets/snippet_test.go
At the request of the spanner team.
> Bump spanner stale read from 10 to 15 seconds.

- endpoints/getting-started/app.yaml
I want to use a docwidget in the docs to display the part of app.yaml that needs to be configured
> Update comment and use region tags

- bigquery/bigquery_datatransfer_quickstart/main.go
A sample showing how to use the BigQuery Data Transfer API to list
possible data sources.
> BQ Data Transfer: Add quickstart sample

- bigquery/bigquery_datatransfer_quickstart/main.go
Follow-up to https://github.com/GoogleCloudPlatform/golang-samples/pull/362#discussion_r160266056
> BigQuery Data Transfer: Remove unnecessary else.

- appengine_flexible/analytics/analytics.go
- getting-started/bookshelf/app/app.go
- getting-started/bookshelf/app/auth.go
The uuid package changed to return an error.
> all: add uuid.Must calls to satori/go.uuid

- opencensus/opencensus_spanner_quickstart/main.go
This sample will be used as a reference for the guide at
https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/OpenCensus.
> Add sample program to demonstrate how to enable debugging tools

- appengine/gophers/gophers-4/main.go
No code changes, just region tags added
> Added region tags

- appengine/gophers/gophers-2/static/style.css
another example for static file
> Create basic style sheet

- vision/detect/detect.go
- vision/detect/generated/gen.go
- vision/detect/generated/sample-template.go
Cloud Vision API has just received an update and some new features have become generally available. This PR shows the new functionality in the Vision API `detect` sample.
Features:
1. Best guess labels for web entity detection
2. Confidence scores in OCR annotations
3. `Racy` axis in safe search.
- - -
To test:
1. `cd vision/detect`
1. `go generate`
1. `go test`
You can also try running on an image that you have available locally by:
```go build && ./detect $PATH_TO_IMAGE```
> New features from latest Vision API update

- iot/manager/manager.go
Related:
* GoogleCloudPlatform/dotnet-docs-samples#451
* GoogleCloudPlatform/ruby-docs-samples#243
* GoogleCloudPlatform/java-docs-samples#1041
> Cleanup Cloud IoT region tags.

- cdn/signedurls/signurl.go
- cdn/signedurls/signurl_test.go
cc: @jadekler
Please hold until I say this is ready to go.
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> cdn: Add URL signing example

- appengine/gophers/gophers-4/index.html
gophers-2 and gophers-3 have the style, but it looks like it was dropped
in gophers-4.
> appengine/gophers: add style to gophers-4

- appengine/gophers/gophers-5/index.html
It's easy to forget to configure Firebase. So, this checks it's been configured and alerts the user if not.
`main.go` also needs to be configured. But, I'm not sure what the right way to alert for that is, if at all.
cc @angelafunk
> appengine/gophers: alert if Firebase JS not setup

- CONTRIBUTING.md
Fixes #426.
Originally from #428 by @brotherhod, but I accidentally overwrote the commit and the PR closed, so I can't update it anymore.
> contributing: clean up testing instructions

- appengine/gophers/gophers-5/static/index.js
as mentioned, account variable shouldn't be created
> appengine/gophers: remove extra JS account variable

- bigquery/snippets/snippet.go
- bigquery/snippets/snippet_test.go
Demonstrates adding an ACE to a dataset ACL
> bigquery: add snippet for bigquery_update_dataset_access

- dialogflow/entity_management/entity_management_test.go
- dialogflow/entity_type_management/entity_type_management_test.go
- dialogflow/intent_management/intent_management_test.go
- dialogflow/session_entity_type_management/session_entity_type_management_test.go
> dialogflow: skip flaky tests

- docs/appengine/taskqueue/taskqueue.go
- testing/kokoro/go110.cfg
- testing/kokoro/go19.cfg
- testing/kokoro/system_tests.sh
- vision/detect/detect_test.go
>  testing/kokoro: add 1.10, remove 1.7, & 25m timeout

- bigquery/snippets/snippet.go
- bigquery/snippets/snippet_test.go
bigquery_extract_table
bigquery_extract_table_json
Additionally, make error reporting in snippet_test.go more informative.
> Add more Go samples for BigQuery:

- testing/kokoro/common.cfg
- testing/kokoro/system_tests.sh
This will allow fine-grained test results (rather than only the top
level pass/fail).
> testing/kokoro: upload XML with test results

- dlp/dlp_snippets/triggers.go
Fields were added and the sample no longer compiles.
> dlp: add field name to struct initializer

- appengine/gophers/gophers-6/static/index.js
> appengine/gophers/6 align w gophers-5 ;)

- pubsub/pubsub_quickstart/main.go
- pubsub/subscriptions/main.go
- pubsub/topics/main.go
Must wait for other language PRs and docs update to be ready before merging
> PubSub: Updates region tags to standard and deletes unused tags

- dlp/dlp_snippets/inspect_test.go
> dlp: re-enable tests

- testing/kokoro/system_tests.sh
> testing: only test modified directories for PRs

- vision/detect/detect.go
- vision/detect/generated/sample-template.go
Add score output to detectWeb and detectWebGeo as requested by #432
> vision: add score to detectWeb and detectWebGeo output

- testing/kokoro/go111.cfg
> testing: test with Go 1.11beta1

- appengine_flexible/pubsub/README.md
- appengine_flexible/pubsub/pubsub.go
> appengine_flexible/pubsub: simplify setup

- memorystore/redis/gce_deployment/deploy.sh
- memorystore/redis/gce_deployment/startup-script.sh
Removing inconsistency in GCS_APP_LOCATION across languages.
https://cloud.google.com/memorystore/docs/redis/connect-redis-instance-gce
> memorystore/redis: make GCE deployment script consistent

- getting-started/bookshelf/db_mongo.go
> Typo in db_mongo.go

- vision/detect/detect.go
- vision/detect/generated/gen.go
- vision/detect/generated/sample-template.go
> Vision region tag update

- appengine_flexible/analytics/analytics.go
- appengine_flexible/analytics/app.yaml
- appengine_flexible/cloudsql/app.yaml
- appengine_flexible/cloudsql/cloudsql.go
- appengine_flexible/cloudsql_postgres/app.yaml
- appengine_flexible/cloudsql_postgres/cloudsql.go
- appengine_flexible/datastore/app.yaml
- appengine_flexible/datastore/datastore.go
- appengine_flexible/mailgun/app.yaml
- appengine_flexible/mailgun/mailgun.go
- appengine_flexible/mailjet/app.yaml
- appengine_flexible/mailjet/mailjet.go
- appengine_flexible/memcache/memcache.go
- appengine_flexible/pubsub/app.yaml
- appengine_flexible/redis/app.yaml
- appengine_flexible/redis/redis.go
- appengine_flexible/sendgrid/app.yaml
- appengine_flexible/sendgrid/sendgrid.go
- appengine_flexible/static_files/staticfiles.go
- appengine_flexible/storage/app.yaml
- appengine_flexible/storage/storage.go
- appengine_flexible/twilio/app.yaml
- appengine_flexible/twilio/twilio.go
- docs/appengine/config/appconfig.txt
- docs/appengine/requests/helloworld.go
- docs/appengine/requests/logging.go
Reverts GoogleCloudPlatform/golang-samples#557
> Revert "update Region tags"

- videointelligence/video_analyze/gen/template.go
- videointelligence/video_analyze/video_analyze.go
Note that I was not able to run `go generate` successfully. Please let me know if this region tag change will work with the template.
> Video Intelligence region tag update

- speech/caption/caption.go
- speech/caption/caption_test.go
- speech/captionasync/captionasync.go
- speech/captionasync/captionasync_test.go
- speech/livecaption/livecaption.go
- speech/livecaption_from_file/livecaption_from_file.go
- speech/wordoffset/wordoffset.go
> Speech region tag update

- appengine_flexible/analytics/analytics.go
- appengine_flexible/analytics/app.yaml
- appengine_flexible/cloudsql/app.yaml
- appengine_flexible/cloudsql/cloudsql.go
- appengine_flexible/cloudsql_postgres/app.yaml
- appengine_flexible/cloudsql_postgres/cloudsql.go
- appengine_flexible/datastore/app.yaml
- appengine_flexible/datastore/datastore.go
- appengine_flexible/mailgun/app.yaml
- appengine_flexible/mailgun/mailgun.go
- appengine_flexible/mailjet/app.yaml
- appengine_flexible/mailjet/mailjet.go
- appengine_flexible/memcache/memcache.go
- appengine_flexible/pubsub/app.yaml
- appengine_flexible/redis/app.yaml
- appengine_flexible/redis/redis.go
- appengine_flexible/sendgrid/app.yaml
- appengine_flexible/sendgrid/sendgrid.go
- appengine_flexible/static_files/staticfiles.go
- appengine_flexible/storage/app.yaml
- appengine_flexible/storage/storage.go
- appengine_flexible/twilio/app.yaml
- appengine_flexible/twilio/twilio.go
- docs/appengine/config/appconfig.txt
- docs/appengine/requests/helloworld.go
- docs/appengine/requests/logging.go
Updating and removing region tags only
undoing revert: https://github.com/GoogleCloudPlatform/golang-samples/pull/566
> appengine: update region tags

- language/analyze/analyze.go
- language/analyze/entity_sentiment.go
- language/snippets/snippet.go
>  Natural Language region tag update

- speech/wordoffset/wordoffset.go
Updates region tag per feedback
> Updates word time offsets region tag

- language/snippets/snippet.go
Updates region tags from _file_gcs to _gcs
> Update NL region tags

- texttospeech/list_voices/list_voices.go
- texttospeech/quickstart/quickstart.go
- texttospeech/synthesize_file/synthesize_file.go
- texttospeech/synthesize_text/synthesize_text.go
> Updates TTS region tags to standard

- container_registry/container_analysis/src/sample/samples.go
- container_registry/container_analysis/src/sample/samples_test.go
Added samples for the Container Analysis beta release.
> Container Analysis Beta

- memorystore/redis/gce_deployment/deploy.sh
- memorystore/redis/gce_deployment/startup-script.sh
Replacing GCS_APP_LOCATION with GCS_BUCKET_NAME to minimize user error
> Memorystore GCE : Replace GCS_APP_LOCATION with GCS_BUCKET_NAME

- testing/kokoro/go16.cfg
- testing/kokoro/go18.cfg
> testing: remove Go 1.6 and 1.8 builds

- container_registry/container_analysis/src/sample/samples_test.go
Attempts to fix https://github.com/GoogleCloudPlatform/golang-samples/issues/603 by wrapping flaky tests in a retry block
> container_registry: retry PubSub test

- appengine_flexible/pubsub/pubsub.go
> appengine_flexible/pubsub: create topic if needed

- endpoints/getting-started/k8s/esp_echo_http.yaml
Copied the k8s config file used in the Endpoints Kubernetes tutorial from the endpoints-samples repo. This way the sample code and the config files are all in the same repo.
> Copied k8s config file from endpoints-samples/k8s

- appengine/go11x/helloworld/helloworld.go
> Add region tag

- monitoring/custommetric/custommetric_test.go
> monitoring/custommetric: use testutil.Retry

- kms/asymmetric/samples.go
- kms/asymmetric/samples_test.go
implements changes suggested in b/113025362 and b/113025156
> KMS changes

- spanner/spanner_snippets/snippet_test.go
fixes: https://github.com/GoogleCloudPlatform/golang-samples/issues/551
> spanner: replace time with the projectID when creating a DB for tests

- kms/asymmetric/samples.go
removed region tag for imports. See https://github.com/GoogleCloudPlatform/golang-samples/pull/654 for discussion
> kms: remove import region tag

- profiler/hotmid/Dockerfile
- profiler/hotmid/main.go
See the code comments for details.
> profiler: add a sample simulating multiple calls to an expensive library function.

- appengine/go11x/tasks/create_task.go
- appengine/go11x/tasks/create_task_test.go
- appengine/go11x/tasks/handler/app.yaml
- appengine/go11x/tasks/handler/task_handler.go
- appengine/go11x/tasks/handler/task_handler_test.go
Replacement PR for #662 to fix git cruft.
> appengine/tasks: cloud tasks appengine queue samples

- appengine/go11x/static/app.yaml
Thanks to @fatih for finding this.
> appengine/go11x: Correct faulty app.yaml

- appengine_flexible/pubsub/app.yaml
- appengine_flexible/pubsub/pubsub.go
- appengine_flexible/pubsub/sample_message.json
> appengine_flexible/pubsub: verify token and log startup

- errorreporting/errorreporting_quickstart/main.go
> errorreporting: return early after error

- iot/manager/manager.go
- iot/manager/manager_test.go
will add tests in separate pull request
> iot: add sample for iot core commands 

- monitoring/snippets/channel_delete.go
- monitoring/snippets/channel_delete_test.go
- monitoring/snippets/channel_enable.go
- monitoring/snippets/channel_enable_test.go
- monitoring/snippets/metric_get.go
- monitoring/snippets/metric_get_test.go
- monitoring/snippets/metric_list.go
- monitoring/snippets/metric_list_test.go
- monitoring/snippets/monitored_resource_get.go
- monitoring/snippets/monitored_resource_get_test.go
- monitoring/snippets/monitored_resource_list.go
- monitoring/snippets/monitored_resource_list_test.go
Some of these overlap with existing samples, but I'm adding entirely new
ones with the new sample style. I'll clean up the old ones once they are
no longer referenced.
> monitoring: add channel, metric, resource samples

- iot/manager/manager_test.go
> iot: use retry and fail with t.Fatalf

- iot/manager/README.md
fix links in iot manager readme (previously missing)
> update iot manager readme

- vision/product_search/import_product_sets.go
for this page: https://cloud.google.com/vision/product-search/docs/tutorial-search-merged
> vision: add region tag vision_product_search_tutorial_import

- CONTRIBUTING.md
> contributing: update formatting and testing sections

- kms/snippets.go
Add tags for kms_remove_member_from_keyring_policy and kms_get_cryptokey_policy.
> kms: add 2 region tags

- speech/snippets/multichannel_test.go
Small change in the detected transcript broke the test.
> speech: relax multichannel test

- bigtable/helloworld/main.go
Adding region tags for Cloud Bigtable samples
> bigtable: add region tags

- functions/console_snippets/firebase_rtdb/firebase_rtdb.go
- functions/console_snippets/firestore/firestore.go
- functions/firebase/hello/firestore.go
- functions/helloworld/hello_cloud_storage.go
- functions/helloworld/hello_http.go
- functions/helloworld/hello_logging.go
- functions/helloworld/hello_pubsub.go
- functions/helloworld/hello_world.go
- functions/helloworld/remote_config.go
- functions/helloworld/storage_generic/hello_storage_generic.go
- functions/http/cors.go
- functions/http/cors_auth.go
- functions/http/form.go
- functions/http/http_content_type.go
- functions/http/http_request_method.go
- functions/http/request.go
- functions/http/stateless.go
- functions/http/xml.go
> functions: update package comments

- datastore/snippets/snippet_test.go
> datastore: fix tx.Put call

- vision/detect/detect.go
- vision/label/label.go
- vision/product_search/add_product_to_product_set.go
- vision/product_search/create_product.go
- vision/product_search/create_product_set.go
- vision/product_search/create_reference_image.go
- vision/product_search/delete_product.go
- vision/product_search/delete_product_set.go
- vision/product_search/delete_reference_image.go
- vision/product_search/get_product.go
- vision/product_search/get_product_set.go
- vision/product_search/get_reference_image.go
- vision/product_search/get_similar_products.go
- vision/product_search/get_similar_products_uri.go
- vision/product_search/import_product_sets.go
- vision/product_search/list_product_sets.go
- vision/product_search/list_products.go
- vision/product_search/list_products_in_product_set.go
- vision/product_search/list_reference_images.go
- vision/product_search/remove_product_from_product_set.go
- vision/product_search/update_product_labels.go
- vision/vision_quickstart/main.go
Close connections when client is no longer required
> vision: close client connection to the API service

- container_registry/container_analysis/src/sample/samples_test.go
> container_registry/container_analysis: skip TestUpdateOccurrence

- speech/snippets/multichannel.go
> speech: update lib version

- jobs/v3/howto/location_based_search_sample_test.go
- jobs/v4/howto/auto_complete_sample.go
- jobs/v4/howto/auto_complete_sample_test.go
- jobs/v4/howto/custom_attribute_sample.go
- update auto-complete sample to search PUBLIC jobs
- update create-job-with-custom-atttributes sample with explicit employment type
> jobs: v4 patch

- container_registry/container_analysis/src/sample/samples_test.go
> container_registry/container_analysis: disable broken PubSub test

- monitoring/uptime/uptime_test.go
The path now has a leading slash.
> monitoring/uptime: fix update test

- jobs/v4/howto/auto_complete_sample.go
- jobs/v4/howto/basic_client_event.go
- jobs/v4/howto/batch_delete_jobs.go
- jobs/v4/howto/commute_search_sample.go
- jobs/v4/howto/create_company_sample.go
- jobs/v4/howto/create_job_sample.go
- jobs/v4/howto/custom_attribute_sample.go
- jobs/v4/howto/custom_ranking_search.go
- jobs/v4/howto/delete_company_sample.go
- jobs/v4/howto/delete_job_sample.go
- jobs/v4/howto/get_company_sample.go
- jobs/v4/howto/get_job_sample.go
- jobs/v4/howto/histogram_search_sample.go
- jobs/v4/howto/list_company_sample.go
- jobs/v4/howto/list_job_sample.go
This is breaking the build right now.
> jobs/v4: return error info and fix broken structs

- jobs/v4/howto/histogram_search_sample_test.go
> jobs/v4: disable TestHistogramSearch

- testing/kokoro/system_tests.sh
> testing/kokoro: always go get top-level deps

- CONTRIBUTING.md
> CONTRIBUTING: add style guide

- healthcare/dataset_deidentify.go
> healthcare: wait for de-id operation to finish

- firestore/firestore_snippets/collection_group_query.go
- firestore/firestore_snippets/collection_group_setup.go
- firestore/firestore_snippets/collection_group_test.go
> firebase: add collection group samples

- iot/mqttsnippets/gateway_send_data_test.go
> iot: skip TestSendDataFromBoundDevice

- endpoints/getting-started-grpc/README.md
> endpoints/gettings-started-grpc: update docker credential command

- iot/manager/manager_test.go
- iot/mqttsnippets/attach_detach_device.go
- iot/mqttsnippets/gateway_send_data.go
- iot/mqttsnippets/gateway_send_data_test.go
- iot/mqttsnippets/subscribe_gateway_device_topic.go
- iot/mqttsnippets/subscribe_gateway_device_topic_test.go
> iot: check test env vars, increase retries, and skip TestSubscribeGatewayToDeviceTopic

- vision/product_search/delete_product_set_test.go
Currently breaking tests. See https://source.cloud.google.com/results/invocations/242cbbec-ecde-4164-b926-9bb2808eefac/targets/gopath%2Fsrc%2Fgithub.com%2FGoogleCloudPlatform%2Fgolang-samples/tests.
cc @dizcology
> vision/product_search: retry TestDeleteProductSet

- appengine/go11x/helloworld/helloworld_test.go
> appengine/go11x: update helloworld_test.go

- container_registry/container_analysis/create_note.go
- container_registry/container_analysis/create_occurrence.go
- container_registry/container_analysis/delete_note.go
- container_registry/container_analysis/delete_occurrence.go
- container_registry/container_analysis/filter_vulnerability_occurrences.go
- container_registry/container_analysis/get_discovery_info.go
- container_registry/container_analysis/get_note.go
- container_registry/container_analysis/get_occurrence.go
- container_registry/container_analysis/occurrences_for_image.go
- container_registry/container_analysis/occurrences_for_note.go
- container_registry/container_analysis/poll_discovery_finished.go
- container_registry/container_analysis/samples_test.go
- container_registry/container_analysis/vulnerability_occurrences_for_image.go
Updated Container analysis samples to use new v1 libraries
> container_registry: Container Analysis v1

- speech/livecaption/livecaption.go
- speech/livecaption_from_file/livecaption_from_file.go
Adding region tags to the Text-to-Speech streaming from file code snippet
> speech: add/move region tags

- container_registry/container_analysis/create_note.go
- container_registry/container_analysis/create_occurrence.go
- container_registry/container_analysis/delete_note.go
- container_registry/container_analysis/delete_occurrence.go
- container_registry/container_analysis/filter_vulnerability_occurrences.go
- container_registry/container_analysis/get_discovery_info.go
- container_registry/container_analysis/get_note.go
- container_registry/container_analysis/get_occurrence.go
- container_registry/container_analysis/occurrences_for_image.go
- container_registry/container_analysis/occurrences_for_note.go
- container_registry/container_analysis/poll_discovery_finished.go
- container_registry/container_analysis/samples_test.go
- container_registry/container_analysis/vulnerability_occurrences_for_image.go
The v1 Container Analysis samples had error messages that still references the beta library. Fixed the string
> container_registry/container_analysis: error message fix

- container_registry/container_analysis/samples_test.go
- container_registry/container_analysis/subscriptions.go
updated the pub/sub topic to use the v1 topic id
> container_registry/container_analysis: update topic id

- testing/kokoro/system_tests.sh
25m is leading to timeouts. Hopefully 45m is enough.
> testing: increase timeout to 45m

- bigtable/garbagecollection/garbagecollection_test.go
Filed #914 to track re-enabling it.
> bigtable: skip flaky garbage collection test

- functions/imagemagick/imagemagick_test.go
I installed convert in the test images.
Fixes #877.
> functions/imagemagick: enable test

- videointelligence/video_analyze/video_analyze_test.go
This reduces the test time from ~400 seconds to ~90 seconds.
> videointelligence/video_analyze: use parallel subtests

- jobs/v4/howto/commute_search_sample_test.go
- jobs/v4/howto/howto_test.go
- testing/docker/go113/Dockerfile
- testing/kokoro/go113.cfg
> testing: add Go 1.13

- getting-started/gopher-run/app.yaml
- getting-started/gopher-run/cmd/main.go
- getting-started/gopher-run/cmd/training.sh
- getting-started/gopher-run/generator/generator.go
- getting-started/gopher-run/leaderboard/leaderboard.go
> getting-started/gopher-run: final changes

- logging/simplelog/simplelog_test.go
> logging: skip TestSimpleLog

- kms/add_member_cryptokey.go
- kms/add_member_keyring.go
- kms/create_cryptokey.go
- kms/create_key.go
- kms/create_keyring.go
- kms/decrypt_rsa.go
- kms/destroy_cryptokey_version.go
- kms/disable_cryptokey_version.go
- kms/enable_cryptokey_version.go
- kms/encrypt_rsa.go
- kms/get_cryptokey_policy.go
- kms/get_key.go
- kms/get_keyring_policy.go
- kms/kms_decrypt.go
- kms/remove_member_cryptokey.go
- kms/remove_member_keyring.go
- kms/restore_cryptokey_version.go
- kms/sign.go
- kms/verify_ec.go
- kms/verify_rsa.go
Include imports in regions and remove newlines after START for consistency
> kms: fix a couple region tags which didn't include imports

- monitoring/irm/annotate_incident.go
- monitoring/irm/irm_test.go
Causing tests to fail.
I also added a little more to the output of test failures to make them easier to debug.
> monitoring/irm: specify ContentType

- profiler/hotapp/main.go
> profiler/hotapp: remove unused function, add flags to configure the project ID and service name

- iam/snippets/service_accounts_disable.go
- iam/snippets/service_accounts_enable.go
- iam/snippets/service_accounts_test.go
Adding service account enable/disable snippets to go along with this doc addition: https://critique.corp.google.com/#review/267282634
> iam: add service account enable/disable snippets

- testing/docker/Dockerfile.go111
- testing/docker/Dockerfile.go112
- testing/docker/Dockerfile.go113
- testing/docker/README.md
- testing/docker/bootstrap.sh
- testing/docker/go111/Dockerfile
- testing/docker/go112/Dockerfile
- testing/docker/go113/Dockerfile
- testing/kokoro/configure_gcloud.bash
- testing/kokoro/system_tests.sh
> testing: preinstall tools, add bootstrap script

- getting-started/bookshelf/gke_deployment/Dockerfile
> getting-started/bookshelf: update GKE Dockerfile

- datastore/snippets/snippet_test.go
Not exactly an idiomatic sample, but I changed it a bit to be able to
write the test. We can move it into its own file if/when we rewrite
these samples.
Fixes #204.
> datastore: fix __namesapce__ metadata query

- .github/renovate.json
- badfiles_test.go
Removed the schedule to get the initial batch of changes done.
> badfiles_test.go,.github: update renovate

- asset/quickstart/create-feed/main_test.go
- asset/quickstart/delete-feed/main_test.go
- asset/quickstart/get-feed/main_test.go
- asset/quickstart/list-feeds/main_test.go
- asset/quickstart/update-feed/main_test.go
There has been some flake with only 30 seconds.
> asset/quickstart: increase test timeout to 2 minutes

- dlp/snippets/inspect/inspect_test.go
> dlp: check errors and skip flaky tests

- healthcare/dicom_test.go
- healthcare/fhir_test.go
- healthcare/internal/dicomweb-instance-search/dicomweb_instance_search.go
- healthcare/internal/fhir-resource-conditional-delete/fhir_resource_conditional_delete.go
- healthcare/internal/fhir-resource-conditional-patch/fhir_resource_conditional_patch.go
- healthcare/internal/fhir-resource-conditional-update/fhir_resource_conditional_update.go
~Conditional patch is not working right now, but the sample looks correct
to me. So, I left out the region tag and test for it.~ Fixed.
cc @noerog
> healthcare: conditional samples

- firestore/firestore_snippets/main.go
- firestore/firestore_snippets/query.go
- go.mod
- go.sum
- run/image-processing/go.sum
Add samples for these two query operators.
I compiled and ran locally to test.
> firestore: add samples for in and array-contains-any

- functions/ci_cd/cloudbuild.yaml
Will be used on https://cloud.google.com/functions/docs/testing/test-cicd#functions-testing-frameworks-go.
> functions: add cloudbuild.yaml example

- automl/dataset_import_data.go
Fix region tag discussed on #1089
> automl: fix region tag automl_import_data

- internal/cloudrunci/cloudrunci.go
Fixing a botch in URL path concatenation.
> run/e2e: fix URL path concatenation

- internal/testutil/testutil.go
> internal/testutil: get absolute filepath

- testing/kokoro/system_tests.sh
> testing: run all tests when the root go.mod changes

- monitoring/snippets/time_series_reduce.go
> monitoring: check slice bounds

- jobs/README.md
> jobs: broken quickstart link

- dataproc/quickstart/quickstart.go
Added 'usage' text to explain how to run quickstart from the command line
> dataproc: add usage text to sample comment

- storage/s3_sdk/list_gcs_buckets_test.go
Updates https://github.com/GoogleCloudPlatform/golang-samples/issues/1213.
> storage: skip HMAC S3 test

- spanner/spanner_snippets/snippet_test.go
> spanner: skip flaky TestSample test

- speech/snippets/context_classes.go
> speech: fix syntax errors

- securitycenter/notifications/create_notification_config.go
- securitycenter/notifications/delete_notification_config.go
- securitycenter/notifications/list_notification_configs.go
- speech/snippets/context_classes.go
Fixes #1245.
#1247 will prevent this in the future.
> securitycenter, speech: gofmt

- speech/snippets/context_classes.go
> speech: run goimports

- testing/docker/Dockerfile.go114
- testing/docker/README.md
- testing/kokoro/go114.cfg
> testing: add Go 1.14

- iam/quickstart/quickstart.go
- iam/snippets/permissions_query_testable.go
- iam/snippets/roles_create.go
- iam/snippets/roles_delete.go
- iam/snippets/roles_edit.go
- iam/snippets/roles_get.go
- iam/snippets/roles_list.go
- iam/snippets/roles_undelete.go
- iam/snippets/roles_view_grantable.go
- iam/snippets/service_account_keys_create.go
- iam/snippets/service_account_keys_delete.go
- iam/snippets/service_account_keys_list.go
- iam/snippets/service_accounts_create.go
- iam/snippets/service_accounts_delete.go
- iam/snippets/service_accounts_disable.go
- iam/snippets/service_accounts_enable.go
- iam/snippets/service_accounts_list.go
- iam/snippets/service_accounts_rename.go
Fixes a documentation issue reported by multiple customers.
> iam: replace deprecated iam.New() with iam.NewService()

- appengine/go11x/tasks/create_task/create_task_test.go
- bigquery/snippets/job/integration_test.go
- bigquery/snippets/querying/bigquery_query_clustered_table.go
- bigtable/filters/filters_test.go
- bigtable/reads/reads_test.go
- docs/appengine/mail/mailjet/mailjet.go
- docs/appengine/memcache/memcache.go
- docs/appengine/modules/module.go
- docs/sql/listinstances/listinstances.go
- endpoints/getting-started-grpc/helloworld/helloworld.pb.go
- functions/log/list.go
- getting-started/devflowapp/services/config.go
- run/grpc-ping/pkg/api/v1/message.pb.go
- storage/acl/acl_test.go
- storage/service_account/hmac/activate.go
- storage/service_account/hmac/create.go
- storage/service_account/hmac/deactivate.go
- storage/service_account/hmac/delete.go
- storage/service_account/hmac/get.go
- storage/service_account/hmac/hmac_test.go
- storage/service_account/hmac/list.go
- tasks/create_http_task_test.go
Fixes #1260 
Fixes #1258 
Updates #1247
> all: goimports and fix storage test

- storage/acl/acl_test.go
- storage/objects/acl.go
- storage/objects/main.go
- storage/objects/objects_test.go
- storage/service_account/hmac/hmac_test.go
- testing/kokoro/system_tests.sh
`goimports` also formats.
Updates #1247.
> testing: use goimports instead of gofmt

- dataproc/instantiate_inline_workflow_template.go
- dataproc/instantiate_inline_workflow_template_test.go
Adding a sample showing how to instantiate an inline workflow template with the client library.
> feat: adding dataproc instantiate inline workflows sample

- pubsub/topics/publish_settings.go
- pubsub/topics/topics_test.go
They were accidentally removed in
d9097fd487f91798f4d203a89456adafbfbc890b.
> pubsub: re-add publish_settings.go and topics_test.go

- vision/detect/set_endpoint_test.go
> vision: use t.SystemTest for endpoint test

- securitycenter/assets/assets_test.go
Possibly related to recent org policy changes.
Updates #1375.
cc @emkornfield
> securitycenter/asset: skip broken test, small style fixes

- dlp/snippets/inspect/inspect_bigquery.go
- dlp/snippets/inspect/inspect_datastore.go
- dlp/snippets/inspect/inspect_gcs.go
- dlp/snippets/inspect/inspect_test.go
> dlp: enable inspect tests and only test jobs were created

- run/grpc-ping/main.go
Need a START tag to go along with existing END tag. for docs purposes.
> run: update main.go with missing region tag

- healthcare/hl7v2_test.go
> healthcare: more retries

- pubsub/subscriptions/async_pull.go
- pubsub/subscriptions/subscription_test.go
- pubsub/subscriptions/sync_pull.go
- Add missing test for pullAsync (StreamingPull)
- Refactor samples so that `topic` is not a required argument for running samples
> pubsub: refactor pull samples

- translate/v3/translate_text_with_glossary.go
- translate/v3/translate_text_with_glossary_and_model.go
> translate: correct wrong glossary method

- CONTRIBUTING.md
> CONTRIBUTING.md: add a few more points

- testing/kokoro/system_tests.sh
I created the project and added all of the test service accounts to it.
Fixes #559.
> testing/kokoro: add Firestore project

- healthcare/dicom_test.go
> healthcare: fix retries

- monitoring/uptime/uptime_test.go
> monitorying/uptime: add retries to TestCreate

- functions/helloworld/README.md
- functions/helloworld/hello_logging.go
> functions/helloworld: expand logging sample, update README

- .github/workflows/go.yaml
I used the same `if` condition as the existing Build and Lint job.
> .github: add Action to run root tests

- spanner/spanner_snippets/spanner/spanner_delete_data.go
Update `spanner_delete_data` to be consistent with the latest spec.
> spanner: update spanner_delete_data sample

- dataproc/quickstart/quickstart_test.go
> dataproc/quickstart: add test retries

- spanner/spanner_snippets/spanner/integration_test.go
- spanner/spanner_snippets/spanner/spanner_create_instance.go
Add a new code sample `spanner_create_instance` and be consistent with other languages.
> spanner: add spanner_create_instance sample.

- functions/tips/infinite_retries/infinite_retries.go
> Clarify infinite retries example

- pubsub/subscriptions/sync_pull.go
Switches to new message handling style as #1455 
Fixes #1464
> pubsub: unflake sync pull test

- monitoring/uptime/uptime.go
- monitoring/uptime/uptime_test.go
These samples are pulled into https://cloud.google.com/monitoring/uptime-checks#create.
> monitoring: demonstrate creation of a POST uptime check to go along with the GET uptime check

- healthcare/hl7v2_iam_get.go
- healthcare/hl7v2_iam_set.go
- healthcare/hl7v2_store_get.go
- healthcare/hl7v2_store_patch.go
Fixes:
b/158298319
b/158299712
> healthcare API: fix some instances where hl7V2Stores was incorrectly capitalized in URL path

- pubsub/subscriptions/subscription_test.go
Tests were flaky because sometimes resources aren't cleaned up properly, and is fixed by switching `DeadLetterDeliveryAttempts` test to use "getOrCreateSub" method.
This PR also refactors "getOrCreateSub" to take in a subscription config, rather than a topic.
Fixes #1476
> pubsub: unflake dead letter delivery attempt test

- healthcare/dicomweb_rendered_retrieve.go
> healthcare: add "rendered" suffix to dicomWebPath comment

- vision/product_search/remove_product_from_product_set_test.go
> vision/product_set: add retries to remove test

- healthcare/fhir_resource_update.go
> healthcare: add clarifying comment for FHIR update resource

- dlp/snippets/inspect/inspect_bigquery.go
- dlp/snippets/inspect/inspect_datastore.go
- dlp/snippets/inspect/inspect_gcs.go
- dlp/snippets/inspect/inspect_test.go
- dlp/snippets/risk/categorical.go
- dlp/snippets/risk/k_anonymity.go
- dlp/snippets/risk/k_map.go
- dlp/snippets/risk/l_diversity.go
- dlp/snippets/risk/numerical.go
- dlp/snippets/risk/risk_test.go
> dlp: increase timeout, use unique topic/sub names for tests

- healthcare/fhir_resource_patch.go
> healthcare: add comment clarifying payload body when patching FHIR resource

- storage/objects/objects_test.go
I think a retry may help with this flake.
Fixes #1551
> storage: unflake TestKMSObjects

- internal/e2e/standard_test.go
> internal/e2e: skip Go11xStatic

- gaming/servers/update_rollout_remove_override.go
Remove the rollout default field from sample for removing override
> gaming: remove empty DefaultGameServerConfig initialization

- go.mod
- go.sum
- spanner/spanner_snippets/spanner/integration_test.go
- spanner/spanner_snippets/spanner/spanner_set_custom_timeout_and_retry.go
Two changes: 
- Upgrade to spanner/v1.8.0
- Add a new sample `spanner_set_custom_timeout_and_retry`
> spanner: add a sample to set custom timeout and retry

- dataproc/create_cluster_test.go
Added retries to flaky test.
Fixes https://github.com/GoogleCloudPlatform/golang-samples/issues/1569
> dataproc: add retries to flaky cluster_create test

- run/grpc-server-streaming/e2e_test.go
> test(run): skip broken test

- functions/ci_cd/cloudbuild.yaml
Align yaml like other yaml files: https://cloud.google.com/functions/docs/testing/test-cicd#setting_up
No functional change.
> refactor(functions): yaml indentation

- asset/quickstart/create-feed/main_test.go
- asset/quickstart/delete-feed/main_test.go
> test(asset): add retries and use UUIDs

- functions/firebase/upper/go.mod
- functions/firebase/upper/go.sum
- functions/firebase/upper/upper.go
I tested this by deploying the function, creating a document, and seeing the value be converted to upper case.
> chore(functions/firebase): upgrade firebase.google.com/go to v4

- securitycenter/notifications/notifications_test.go
> test(securitycenter/notifications): add retry

- functions/tips/contexttip/context_tip.go
> chore(functions/pubsub): fix region tags + rename env var

- .github/CODEOWNERS
- .github/blunderbuss.yml
@tbpg is it possible to add me and obs team as codeowners to the logging samples? 
Thanks!
> chore(.github): add logging code owner: observability dpe

- eventarc/audit_storage/main.go
- eventarc/audit_storage/main_test.go
Slightly modifies output of Eventarc Audit sample to be consistent.
> fix: fix eventarc audit output

- videointelligence/annotate/object_tracking.go
- videointelligence/annotate/object_tracking_gcs.go
- videointelligence/annotate/text_detection.go
- videointelligence/annotate/text_detection_gcs.go
- videointelligence/video_analyze/video_analyze.go
- videointelligence/video_analyze/video_analyze_gcs.go
Aligns with other languages to use `video_speech_transcription_gcs`
> chore: updates region tags

- endpoints/getting-started-grpc/server/main.go
Testing:
* Verified that the Docker image can now be built.
* This solution appears to be the preferred solution from what I have read.
* Had another user verify that this fix works for them as well.
> fix: #1795 endpoints sample mustEmbedUnimplemented

- storage/buckets/buckets_test.go
> fix(storage): add retry to TestBucketWebsiteInfo

- eventarc/audit_storage/go.mod
- eventarc/audit_storage/main.go
- eventarc/generic/go.mod
- eventarc/generic/main.go
- eventarc/generic/main_test.go
- eventarc/pubsub/go.mod
- eventarc/pubsub/main.go
Slightly improves Eventarc samples.
Addresses many comments from: https://github.com/GoogleCloudPlatform/golang-samples/pull/1767 (Thanks for the suggestions)
Feel free to add more suggestions, or 👍  if all good.
> refactor: improve eventarc go samples

- logging/advancedlog/main.go
- logging/advancedlog/main_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/3074
It will show up here:
https://cloud.google.com/logging/docs/samples/logging-write-log-entry-advanced
Rubric: go/cdpe-snippet-rubric
> feat(logging): advanced log write sample

- .github/workflows/go.yaml
> chore(.github): use setup-go@v2

- CONTRIBUTING.md
> docs: add more contributing guidance

- getting-started/background/translate_test.go
> test(getting-started): update test translation terms

- servicedirectory/create_endpoint.go
- servicedirectory/create_namespace.go
- servicedirectory/create_service.go
- servicedirectory/delete_endpoint.go
- servicedirectory/delete_namespace.go
- servicedirectory/delete_service.go
- servicedirectory/quickstart/quickstart.go
- servicedirectory/resolve_service.go
As our GA launch is approaching, we want to change our samples that populate our documentation to use our v1 api.
> feat: update service directory samples to v1

- servicedirectory/resolve_service.go
> chore(servicedirectory): fix error text

- run/h2c/README.md
Add full command.
Fixes #1912
cc: @tbpg
> fix(run/h2c): instructions

- monitoring/snippets/channel_delete_test.go
> test(monitoring): add retries

- media/transcoder/transcoder_test.go
The test is still failing because the job is still RUNNING.
Fixes #1880.
> test(media): even more retries

- eventarc/testing/go.sum
- go.mod
- go.sum
- run/testing/go.sum
- spanner/spanner_snippets/spanner/integration_test.go
- spanner/spanner_snippets/spanner/spanner_commit_stats.go
Adds sample for requesting `CommitStats` for a read/write transaction.
> docs(spanner): add CommitStats sample

- .github/blunderbuss.yml
> chore(.github): reassign DB issues

- dlp/snippets/inspect/inspect_test.go
> test(dlp): add retries

- dialogflow/detect_intent/detect_intent_test.go
> test(dialogflow): add retries

- language/analyze/analyze_test.go
> test(language): add retries

- appengine/go11x/tasks/create_task/create_task_test.go
- spanner/spanner_snippets/spanner/integration_test.go
See https://github.com/GoogleCloudPlatform/golang-samples/issues/1900.
Fixes https://github.com/GoogleCloudPlatform/golang-samples/issues/2062 (I ran this 50 times locally and it passed all of them).
> tests: more AE retries, skip Spanner Backup test

- secretmanager/consume_event_notification.go
- secretmanager/secretmanager_test.go
> feat(secretmanager): add example code for receiving a Pub/Sub notification from Secret Manager

- functions/ci_cd/cloudbuild.yaml
> fix(functions): use golang image for CI/CD example

- eventarc/testing/go.sum
- functions/security/go.mod
- functions/security/go.sum
- go.mod
- go.sum
- monitoring/go.mod
- monitoring/go.sum
- run/grpc-ping/go.mod
- run/grpc-ping/go.sum
- run/markdown-preview/editor/go.mod
- run/markdown-preview/editor/go.sum
- run/testing/go.sum
Only updated modules that used idtoken and could have experienced this issue.
Fixes: #2125
> fix: update google.golang.org/api to v0.50.0

- spanner/spanner_snippets/spanner/integration_test.go
Retries `CreateInstance` requests if it fails with a `RESOURCE_EXHAUSTED` error because the request exceeded the quota for the number of create instance requests per minute for the project.
Updates #2111
> fix(spanner): retry CreateInstance requests on RESOURCE_EXHAUSTED

- spanner/spanner_snippets/spanner/integration_test.go
Also apply the retry strategy for creating an instance to the CreateInstance samples.
Fixes #2136
> test(spanner): retry CreateInstance sample

- spanner/spanner_snippets/spanner/integration_test.go
> test(spanner): fix backup sample tests

- asset/quickstart/export-assets-bigquery/main.go
- asset/quickstart/export-assets-bigquery/main_test.go
Double the amount of reties and add the force flag to overwrite
values if present.
Fixes: #2142
> chore(asset): try to reduce flakiness

- pubsublite/admin/pubsublite_admin_test.go
After creating resources, it make take some time before resources are available in a `Get` or `List`. Add retry to prevent test flakiness after resource creation.
Closes #2088
> test(pubsublite): add retries to admin test

- kms/destroy_key_version.go
- kms/disable_key_version.go
- kms/enable_key_version.go
- kms/get_public_key.go
> fix(kms): align parameter names properly

- spanner/spanner_snippets/spanner/integration_test.go
> chore(spanner): skip TestBackupSample

- run/testing/h2c.e2e_test.go
> fix(run): Add retries to tests

- eventarc/testing/go.sum
- getting-started/authenticating-users/go.mod
- getting-started/authenticating-users/go.sum
- getting-started/authenticating-users/main.go
- go.mod
- go.sum
- iot/mqttsnippets/create_jwt.go
- monitoring/go.sum
- run/testing/go.sum
See README of https://github.com/golang-jwt/jwt for details. This
fork has some import security fixes.
Fixes: b/194518417
> feat: migrate to community maintained JWT lib

- bigquery/snippets/dataset/bigquery_revoke_dataset_access.go
- bigquery/snippets/dataset/integration_test.go
Based on the initial sample in progress in python https://github.com/googleapis/python-bigquery/pull/778
Addresses b/179811354
> feat:  add snippet for bigquery_revoke_dataset_access

- dlp/snippets/inspect/inspect_test.go
> chore(dlp): skip failing test

- eventarc/testing/go.sum
- go.mod
- go.sum
- monitoring/go.mod
- monitoring/go.sum
- pubsublite/admin/pubsublite_admin_test.go
- pubsublite/admin/seek_subscription.go
- run/testing/go.sum
Adds a new sample for the `SeekSubscription` feature:
https://pkg.go.dev/cloud.google.com/go/pubsublite#AdminClient.SeekSubscription
> feat(pubsublite): add seek subscription sample

- healthcare/fhir_execute_bundle.go
- healthcare/fhir_store_create.go
Adds "request" field to bundle body and updates the FHIR store to use the latest version (R4).
Fixes https://github.com/GoogleCloudPlatform/golang-samples/issues/2218
> fix(healthcare): add request field to bundle

- spanner/spanner_snippets/spanner/integration_test.go
This is being tracked in #2143
> test(spanner): skip failing test

- gaming/servers/get_cluster.go
- gaming/servers/list_clusters.go
- gaming/servers/realm_test.go
- go.mod
> feat(gaming): show cluster installation state details for get and list methods

- badfiles_test.go
- cloudsql/mysql/database-sql/Dockerfile
- cloudsql/mysql/database-sql/cloudsql.go
- cloudsql/postgres/database-sql/Dockerfile
- cloudsql/postgres/database-sql/cloudsql.go
This commit adds support for configuring SSL certificates for Postgres
and MySQL.
> feat(cloudsql): add support for SSL certificates

- cloudsql/mysql/database-sql/cloudsql.go
- cloudsql/postgres/database-sql/cloudsql.go
- cloudsql/sqlserver/database-sql/cloudsql.go
Follow up from https://github.com/GoogleCloudPlatform/golang-samples/pull/2219#discussion_r711112356.
> chore(cloudsql): declare and assign with :=

- dlp/snippets/inspect/inspect_test.go
> test(dlp): reenable TestInspectGCS

- spanner/spanner_snippets/spanner/integration_test.go
> test(spanner): skip TestCustomerManagedEncryptionKeys

- storage/buckets/buckets_test.go
Fixes #2247 while changes for https://github.com/googleapis/google-cloud-go/issues/4890 are merged in
> test(storage): skip PAP test for now

- .github/CODEOWNERS
- .github/blunderbuss.yml
> chore(.github): add owners for storagetransfer

- internal/cloudrunci/gcloud_test.go
Verbiage on the message changed slightly.
Closes #2300
> test(cloudrunci): fix gcloud test

- storage/objects/generate_v4_get_object_signed_url.go
- storage/objects/generate_v4_put_object_signed_url.go
- storage/objects/objects_test.go
Fixes #2079
Similar change to PostPolicy samples should be made once Storage 19.0 is released.
> feat(storage): update SignedURL samples to handle auth for user 

- storage/objects/download_file.go
- storage/objects/download_file_into_memory.go
- storage/objects/objects_test.go
- storage/objects/stream_file_upload.go
Includes a fix for the existing download sample. It now downloads to a file instead of downloading to memory.
> samples(storage): Upload file download file into memory

- speech/caption/caption_test.go
- speech/captionasync/captionasync_test.go
- speech/wordoffset/wordoffset_test.go
- videointelligence/annotate/text_detection_gcs_test.go
- videointelligence/video_analyze/video_analyze_test.go
- vision/detect/detect_test.go
Issues due to
https://github.com/GoogleCloudPlatform/golang-samples/issues/2349
> testing: skip impacted GCS tests

- compute/instance-templates/create-instance-templates/create_instance_templates_test.go
> chore(compute): skip TestCreateInstanceTemplatesSnippets

- pubsub/topics/publish_flow_control.go
Region tag used was incorrect, update to the correct one.
> refactor(pubsub): rename region tags

- logging/taillogs/taillogs.go
> fix(logging): count real streamed entries instead of iterations

- healthcare/dicomweb_study_search.go
> fix(healthcare api): add if/else clause for DICOMweb search studies

- kms/create_key_rotation_schedule.go
- kms/go.mod
- kms/update_key_add_rotation.go
Updating the obsolete protobuf packages with newer ones.
Fixes b/201533150.
> chore: update protobuf dependency for kms

- functions/security/idtoken.go
- functions/security/idtoken_cloudfunction.go
- functions/security/security_system_test.go
~**DO NOT MERGE** until tests pass.~
The system tests are failing on `main` on my local machine, so we should confirm they're working before merging this.
> fix(serverless): clean up ID token example

- functions/ci_cd/cloudbuild.yaml
Updates CI/CD GCF Go Runtime version to 1.16
> chore(functions/ci_cd): update Go version to 1.16

- docs/appengine/mail/mail.go
- docs/appengine/mail/mailgun/mailgun.go
- docs/appengine/mail/mailjet/app.yaml
- docs/appengine/mail/mailjet/mailjet.go
- docs/appengine/mail/sendgrid/sendgrid.go
- docs/go.mod
- docs/go.sum
> fix(docs): update mail example to use appengine/v2

- healthcare/fhir_test.go
- healthcare/hl7v2_test.go
Fixes https://github.com/GoogleCloudPlatform/golang-samples/issues/2417.
> fix(healthcare): increase FHIR store create test retry

- bigquery/bigquery_storage_quickstart/main.go
* Adds special handling for retryable RESOURCE_EXHAUSTED errors returned from bigquery storage api, so they aren't treated as regular errors.
* Fixes retries being reset every time an error is observed, so at most 3 back-to-back errors are retried.
> fix(bigquery/storage): handle retryable RESOURCE_EXHAUSTED errors in bigquery storage sample

- cloudsql/mysql/database-sql/README.md
- cloudsql/mysql/database-sql/cloudsql.go
- cloudsql/mysql/database-sql/cloudsql_test.go
- cloudsql/postgres/database-sql/README.md
- cloudsql/postgres/database-sql/cloudsql.go
- cloudsql/postgres/database-sql/cloudsql_test.go
- cloudsql/sqlserver/database-sql/cloudsql_test.go
Updating READMEs with proper variable name that aligns with samples.
> chore(cloudsql): update variable name in READMEs

- pubsub/topics/publish.go
- pubsub/topics/publish_flow_control.go
> fix(pubsub): prevent race condition in sample

- compute/instances/custom-machine-type/helper_class.go
- compute/instances/custom-machine-type/helper_class_test.go
- media/go.mod
- media/go.sum
- media/livestream/README.md
- media/livestream/create_channel.go
- media/livestream/create_channel_event.go
- media/livestream/create_input.go
- media/livestream/delete_channel.go
- media/livestream/delete_channel_event.go
- media/livestream/delete_input.go
- media/livestream/get_channel.go
- media/livestream/get_channel_event.go
- media/livestream/get_input.go
- media/livestream/list_channel_events.go
- media/livestream/list_channels.go
- media/livestream/list_inputs.go
- media/livestream/livestream_test.go
- media/livestream/start_channel.go
- media/livestream/stop_channel.go
- media/livestream/update_channel.go
- media/livestream/update_input.go
> feat: add code samples and tests for Live Stream

- healthcare/fhir_test.go
Fixes https://github.com/GoogleCloudPlatform/golang-samples/issues/2535.
> fix(healthcare): increase FHIR store create test timeout

- getting-started/gce/startup-script.sh
- memorystore/redis/gce_deployment/startup-script.sh
We need to remove the use of curl bash from our snippets.
internal bugs: b/210458605 b/214987051
> fix: remove direct use of curl bash

- healthcare/dataset_create.go
- healthcare/dataset_test.go
- healthcare/dicom_test.go
- healthcare/fhir_test.go
- healthcare/hl7v2_test.go
This is basically the same as the fix in the Python tests GoogleCloudPlatform/python-docs-samples#7501
> fix(healthcare): Wait for dataset operation to complete before continuing with tests

- media/videostitcher/README.md
- media/videostitcher/create_slate.go
- media/videostitcher/delete_slate.go
- media/videostitcher/get_slate.go
- media/videostitcher/list_slates.go
- media/videostitcher/stitcher_test.go
- media/videostitcher/update_slate.go
b: 202972969
Enable the following API on the test project:
*   Video Stitcher API (test project must be allowlisted - contact nickcook@)
*   Cloud Resource Manager API (needed for project number translation)
> feat: add code samples and tests for Video Stitcher

- media/videostitcher/create_cdn_key.go
- media/videostitcher/delete_cdn_key.go
- media/videostitcher/get_cdn_key.go
- media/videostitcher/list_cdn_keys.go
- media/videostitcher/stitcher_test.go
- media/videostitcher/update_cdn_key.go
> feat: add Video Stitcher CDN key samples and tests

- media/videostitcher/create_live_session.go
- media/videostitcher/create_vod_session.go
- media/videostitcher/get_live_ad_tag_detail.go
- media/videostitcher/get_live_session.go
- media/videostitcher/list_live_ad_tag_details.go
- media/videostitcher/stitcher_test.go
> feat: add Video Stitcher live session samples and tests

- storagetransfer/transfer_between_posix.go
- storagetransfer/transfer_using_manifest.go
I mixed up some region tags in my last PR, sorry!
> fix: fix STS region tags

- storagetransfer/storagetransfer_test.go
Previously this would panic if the reponse was nil.
Fixes #2654
> test(storagetransfer): fix test cleanup panic

- go.mod
- go.sum
- internal/mtls_smoketest/smoketest_test.go
- run/testing/go.sum
Did as the doc comment said :) This was missed in the last gaming
cleanup
Fixes: #2662
> chore: remove failing test

- translate/v3/get_supported_languages_test.go
This will be fixed, but this is causing CI to fail for everything
right now.
Updates: #2652
> chore(translate): skip TestGetSupportedLanguages for now

- media/videostitcher/create_cdn_key.go
- media/videostitcher/create_live_session.go
- media/videostitcher/create_slate.go
- media/videostitcher/create_vod_session.go
- media/videostitcher/delete_cdn_key.go
- media/videostitcher/delete_slate.go
- media/videostitcher/get_cdn_key.go
- media/videostitcher/get_live_ad_tag_detail.go
- media/videostitcher/get_live_session.go
- media/videostitcher/get_slate.go
- media/videostitcher/get_vod_ad_tag_detail.go
- media/videostitcher/get_vod_session.go
- media/videostitcher/get_vod_stitch_detail.go
- media/videostitcher/list_cdn_keys.go
- media/videostitcher/list_live_ad_tag_details.go
- media/videostitcher/list_slates.go
- media/videostitcher/list_vod_ad_tag_details.go
- media/videostitcher/list_vod_stitch_details.go
- media/videostitcher/update_cdn_key.go
- media/videostitcher/update_slate.go
> docs(videostitcher): fix region tag prefix

- bigquery/snippets/job/bigquery_extract_model.go
- bigquery/snippets/job/integration_test.go
> feat(bigquery): add extract ml model sample

- bigquery/go.mod
- bigquery/snippets/table/bigquery_inserting_data_types.go
- bigquery/snippets/table/integration_test.go
> feat(bigquery): add sample to insert data with complex data types

- jobs/v3/howto/general_search_sample.go
Submitted cl/491438545 to remove obsolete region tags; this is a follow-up to https://github.com/GoogleCloudPlatform/golang-samples/pull/2767
Note: snippet-bot will report errors until the CL changes are indexed; please do not merge until snippet-bot is happy.
> chore(jobs): removing obsolete region tags

- batch/read_job_logs.go
Use the appropriate error message in the sample
> fix(batch): Use the appropriate error message

- functions/http/xml.go
Updated xml sample using gen2 signature.
Tested:
- go test
- deploy + curl
> chore(functions/http): Update xml sample to use gen2 signature

- functions/http/request.go
Tested by: 
* Deploying function. Got expected message
* Running local tests
> chore(functions/http/request): Update sample to use declarative signature

- functions/tips/lazy.go
Tested by:
* Deploying and executing function
* Running local tests
> chore(functions/tips/lazy): Update sample to use declarative signature

- cloudsql/postgres/database-sql/cloudsql.go
- cloudsql/postgres/database-sql/connect_connector.go
- cloudsql/postgres/database-sql/connect_connector_iam_authn.go
Splitting out Auto IAM AuthN sample for Go Connector into its own file.
> chore(cloudsql): split out Postgres Auto IAM AuthN sample

- run/grpc-ping/connection.go
This addresses user feedback in b/236035316
> docs: add comment about SystemCertPool() on windows

- cloudsql/mysql/database-sql/cloudsql.go
- cloudsql/mysql/database-sql/connect_connector.go
- cloudsql/mysql/database-sql/connect_connector_iam_authn.go
- cloudsql/mysql/database-sql/connect_tcp.go
- cloudsql/mysql/database-sql/connect_unix.go
- cloudsql/mysql/database-sql/deployment.yaml
- cloudsql/postgres/database-sql/cloudsql.go
- cloudsql/postgres/database-sql/connect_connector.go
- cloudsql/postgres/database-sql/connect_connector_iam_authn.go
- cloudsql/postgres/database-sql/connect_tcp.go
- cloudsql/postgres/database-sql/connect_unix.go
- cloudsql/postgres/database-sql/deployment.yaml
- cloudsql/sqlserver/database-sql/connect_connector.go
- cloudsql/sqlserver/database-sql/connect_tcp.go
Creating a new Pull Request based on conversation in: https://github.com/GoogleCloudPlatform/golang-samples/pull/2809
This PR adds clearer descriptions around the impact of environment variable in `deployment.yaml` and how that determines how the code will run.
> docs: add comments to explain environment variables

- translate/v3/get_supported_languages_test.go
> fix(translate): improve test for get languages

- vision/detect/detect_test.go
> fix(vision): changes assert for crop sample test

- securitycenter/findings/findings_test.go
this should alleviate the quota exhaustion happening in these tests.
fixes #2932
> fix(testing): extend wait time between attempts

- appengine_flexible/redis/go.mod
- appengine_flexible/redis/go.sum
- appengine_flexible/static_files/go.mod
- appengine_flexible/static_files/go.sum
Resolves several open dependabot alerts.
> chore(deps): golang.org/x/net -> 0.7.0 for AE Flex

- compute/disks/disks_test.go
- compute/disks/set_disk_autodelete.go
Fixes b/274416742 - User feedback.
> docs(samples): DiskAutoDelete accepts value for the auto_delete flag

- .github/CODEOWNERS
- .github/blunderbuss.yml
Update CODEOWNERs and Blunderbuss configuration for the asset team.
> chore: update ownership for asset team

- dlp/snippets/deid/date_shift.go
- dlp/snippets/deid/deid_fpe.go
- dlp/snippets/deid/deid_with_exception_list.go
- dlp/snippets/deid/deid_with_redact.go
- dlp/snippets/deid/mask.go
- dlp/snippets/deid/reid_fpe.go
- dlp/snippets/inspect/inspect_bigquery.go
- dlp/snippets/inspect/inspect_datastore.go
- dlp/snippets/inspect/inspect_gcs.go
- dlp/snippets/inspect/inspect_text_file.go
- dlp/snippets/jobs/delete.go
- dlp/snippets/jobs/jobs_test.go
- dlp/snippets/jobs/list.go
- dlp/snippets/metadata/info_types.go
- dlp/snippets/redact/redact.go
- dlp/snippets/risk/categorical.go
- dlp/snippets/risk/k_anonymity.go
- dlp/snippets/risk/k_map.go
- dlp/snippets/risk/l_diversity.go
- dlp/snippets/risk/numerical.go
- dlp/snippets/risk/risk.go
- dlp/snippets/template/create.go
- dlp/snippets/template/delete.go
- dlp/snippets/template/list.go
- dlp/snippets/trigger/create.go
- dlp/snippets/trigger/delete.go
- dlp/snippets/trigger/list.go
Fixit: Go Error Visibility for dlp
> chore(fixit): Go Error Visibility for dlp

- iam/deny/create_deny_policy.go
- iam/deny/delete_deny_policy.go
- iam/deny/get_deny_policy.go
- iam/deny/list_deny_policies.go
- iam/deny/update_deny_policy.go
- iam/snippets/permissions_query_testable.go
- iam/snippets/roles_create.go
- iam/snippets/roles_delete.go
- iam/snippets/roles_edit.go
- iam/snippets/roles_get.go
- iam/snippets/roles_list.go
- iam/snippets/roles_undelete.go
- iam/snippets/roles_view_grantable.go
- iam/snippets/service_account_keys_create.go
- iam/snippets/service_account_keys_delete.go
- iam/snippets/service_account_keys_list.go
- iam/snippets/service_accounts_create.go
- iam/snippets/service_accounts_delete.go
- iam/snippets/service_accounts_disable.go
- iam/snippets/service_accounts_enable.go
- iam/snippets/service_accounts_list.go
- iam/snippets/service_accounts_rename.go
Fixit: Go Error Visibility for iam
> chore(fixit): Go Error Visibility for iam

- functions/console_snippets/firebase_auth/firebase_auth.go
- functions/console_snippets/firebase_rtdb/firebase_rtdb.go
- functions/console_snippets/firestore/firestore.go
- functions/console_snippets/google_analytics/google_analytics.go
- functions/firebase/hello/firestore.go
- functions/firebase/upper/upper.go
- functions/functionsv2/hellopubsub/hello_pubsub.go
- functions/functionsv2/imagemagick/imagemagick.go
- functions/functionsv2/log/process_log_entry.go
- functions/functionsv2/ocr/app/detect.go
- functions/functionsv2/ocr/app/process.go
- functions/functionsv2/ocr/app/save.go
- functions/functionsv2/ocr/app/setup.go
- functions/functionsv2/ocr/app/translate.go
- functions/functionsv2/slack/format.go
- functions/functionsv2/slack/search.go
- functions/functionsv2/tips/infinite_retries/infinite_retries.go
- functions/functionsv2/tips/retry.go
- functions/helloworld/hello_cloud_storage.go
- functions/imagemagick/imagemagick.go
- functions/memorystore/redis/visitcount.go
- functions/ocr/app/detect.go
- functions/ocr/app/process.go
- functions/ocr/app/save.go
- functions/ocr/app/setup.go
- functions/ocr/app/translate.go
- functions/security/idtoken.go
- functions/slack/search.go
- functions/tips/infinite_retries/infinite_retries.go
Fixit: Go Error Visibility for functions
> chore(fixit): Go Error Visibility for functions

- run/system_package/graphviz.go
Update Cloud Run system-package sample for wrapped errors
> chore(fixit): Errors update for Cloud Run system-package

- batch/create_with_container_no_mounting.go
- batch/create_with_gcs_bucket.go
- batch/create_with_gcs_bucket_test.go
- batch/create_with_script_no_mounting.go
- batch/create_with_template.go
- batch/create_with_template_test.go
- batch/delete_job.go
- batch/get_job.go
- batch/get_task.go
- batch/list_jobs.go
- batch/list_tasks.go
- batch/read_job_logs.go
- batch/testutils.go
Fixit: Go Error Visibility for batch
> chore(fixit): Go Error Visibility for batch

- tasks/token/create_http_task_with_token.go
Go error updates for Cloud Tasks token directory.
> chore(fixit): Go Error Visibility for tasks/token

- tasks/create_http_task.go
Go Error Visibility: Cloud Tasks create task.
> chore(fixit): Go Error Visibility for Cloud Tasks

- run/grpc-ping/request_auth.go
- run/testing/grpc_ping.e2e_test.go
Update Cloud Run grpc-ping sample for wrapped errors
> chore(fixit): Errors update for Cloud Run grpc-ping

- run/image-processing/imagemagick/imagemagick.go
Update Cloud Run image-processing sample for wrapped errors
> chore(fixit): Errors update for Cloud Run image-processing

- cloudsql/postgres/database-sql/cloudsql.go
- cloudsql/postgres/database-sql/connect_connector.go
- cloudsql/postgres/database-sql/connect_connector_iam_authn.go
- cloudsql/postgres/database-sql/connect_tcp.go
- cloudsql/postgres/database-sql/connect_unix.go
Fixes [b/281110007](http://b/281110007)
> chore(fixit): Errors update for Cloud SQL Postgres

- bigtable/writes/write_batch.go
- bigtable/writes/write_conditionally.go
- bigtable/writes/write_increment.go
- bigtable/writes/write_simple.go
> chore(fixit): Go Error Visibility for bigtables/writes

- translate/detect.go
- translate/list.go
- translate/model.go
- translate/text.go
> chore(fixit): Go Error Visibility for translate

- cloudsql/mysql/database-sql/cloudsql.go
- cloudsql/mysql/database-sql/connect_connector.go
- cloudsql/mysql/database-sql/connect_connector_iam_authn.go
- cloudsql/mysql/database-sql/connect_tcp.go
- cloudsql/mysql/database-sql/connect_unix.go
> chore(fixit): Go Error Visibility for cloudsql/mysql/database-sql

- vision/detect/set_endpoint.go
> chore(fixit): Go Error Visibility for vision/detect

- bigtable/connectionpool/configure_connection_pool.go
> chore(fixit): Go Error Visibility for bigtables/connectionpool

- bigtable/reads/reads.go
> chore(fixit): Go Error Visibility for bigtables/reads

- monitoring/uptime/uptime.go
chore(fixit): Go Error Visibility for monitoring/uptime
> chore(fixit): Go Error Visibility for monitoring/uptime

- endpoints/getting-started/client/main.go
chore(fixit): Go Error Visibility for endpoints/getting-started/client
> chore(fixit): Go Error Visibility for endpoints/getting-started/client

- monitoring/snippets/channel_delete.go
- monitoring/snippets/channel_delete_test.go
- monitoring/snippets/channel_enable.go
- monitoring/snippets/metric_create.go
- monitoring/snippets/metric_delete.go
- monitoring/snippets/metric_get.go
- monitoring/snippets/metric_list.go
- monitoring/snippets/monitored_resource_get.go
- monitoring/snippets/monitored_resource_get_test.go
- monitoring/snippets/monitored_resource_list.go
- monitoring/snippets/time_series_align.go
- monitoring/snippets/time_series_fields.go
- monitoring/snippets/time_series_reduce.go
chore(fixit): Go Error Visibility for monitoring/snippets
> chore(fixit): Go Error Visibility for monitoring/snippets

- monitoring/custommetric/custommetric.go
chore(fixit): Go Error Visibility for monitoring/custommetric
> chore(fixit): Go Error Visibility for monitoring/custommetric

- getting-started/authenticating-users/main.go
- getting-started/background/index/main.go
- getting-started/background/translate.go
FixIt: Go error visibility for getting-started.
> chore(fixit): Go error visibility for getting-started

- firestore/collection_group_query.go
- firestore/collection_group_setup.go
- firestore/increment.go
- firestore/listen_changes.go
- firestore/listen_document.go
- firestore/listen_errors.go
- firestore/listen_multiple.go
- firestore/solution_counters.go
FixIt: Go error visibility for Firestore.
> chore(fixit): Go error visibility for firestore

- documentai/documentai_quickstart/main.go
FixIt: Go error visibility for DocAI.
> chore(fixit): Go error visibility for DocAI

- datastore/admin/datastore_admin_client_create.go
- datastore/admin/datastore_admin_entities_export.go
- datastore/admin/datastore_admin_entities_import.go
- datastore/admin/datastore_admin_index_get.go
- datastore/admin/datastore_admin_index_list.go
- datastore/snippets/snippet_test.go
FixIt: Go error format identifier changes for Datastore.
> chore(fixit): Go error visibility for Datastore

- media/transcoder/create_job_from_ad_hoc.go
- media/transcoder/create_job_from_preset.go
- media/transcoder/create_job_from_template.go
- media/transcoder/create_job_template.go
- media/transcoder/create_job_with_animated_overlay.go
- media/transcoder/create_job_with_concatenated_inputs.go
- media/transcoder/create_job_with_embedded_captions.go
- media/transcoder/create_job_with_periodic_images_spritesheet.go
- media/transcoder/create_job_with_set_number_images_spritesheet.go
- media/transcoder/create_job_with_standalone_captions.go
- media/transcoder/create_job_with_static_overlay.go
- media/transcoder/delete_job.go
- media/transcoder/delete_job_template.go
- media/transcoder/get_job.go
- media/transcoder/get_job_state.go
- media/transcoder/get_job_template.go
- media/transcoder/list_job_templates.go
- media/transcoder/list_jobs.go
chore(fixit): Go Error Visibility for media/transcoder
> chore(fixit): Go Error Visibility for media/transcoder

- profiler/shakesapp/shakesapp/server.go
chore(fixit): Go Error Visibility for profiler/shakesapp/shakesapp
> chore(fixit): Go Error Visibility for profiler/shakesapp/shakesapp

- testing/kokoro/system_tests.sh
> chore(securitycenter): adds SCC org and project

- privateca/create_certificate.go
- privateca/list_certificates.go
- privateca/privateca_test.go
- privateca/revoke_certificate.go
Fixes b/281691743, b/281691653, b/281691543
> feat(fixit): create, list and revoke certificate samples

- bigquery/snippets/table/bigquery_table_exists.go
> docs(bigquery): fix typo

- storage/notifications/notifications_test.go
Add notification is not idempotent so does not retry automatically. This adds retries where it is called from the test client and from the sample itself.
Fixes #3164
> test(storage): add retry for Notifications test

- .github/CODEOWNERS
> fix: Update CODEOWNERS with tiers for functions/appengine

- securitycenter/assets/add_delete_security_marks.go
- securitycenter/assets/add_security_marks.go
- securitycenter/assets/delete_security_marks.go
- securitycenter/assets/list_all_assets.go
- securitycenter/assets/list_all_project_assets.go
- securitycenter/assets/list_assets_with_security_marks.go
- securitycenter/assets/list_project_assets_and_state_changes.go
- securitycenter/assets/list_project_assets_at_time.go
- securitycenter/findings/add_security_marks.go
- securitycenter/findings/list_all_findings.go
- securitycenter/findings/list_filtered_findings.go
- securitycenter/findings/list_findings_at_time.go
- securitycenter/findings/list_findings_with_security_mark.go
- securitycenter/findings/list_sources.go
- securitycenter/notifications/create_notification_config.go
- securitycenter/notifications/delete_notification_config.go
- securitycenter/notifications/get_notification_config.go
- securitycenter/notifications/list_notification_configs.go
- securitycenter/notifications/update_notification_config.go
Contains only comment updates to allow new parent types (b/263299056)
> docs(scc-samples): update comments to include new parent resource types

- badfiles_test.go
> chore: add DLP data ignore to bad_files_test

- compute/instances/create-manage-windows-instances/create_windows_instances_test.go
- compute/instances/create-manage-windows-instances/create_windows_server_external_ip.go
- compute/instances/create-manage-windows-instances/create_windows_server_internal_ip.go
> chore(update): Updating Windows to version 2022

- .github/blunderbuss.yml
Update sample repo code owners to infra-db-sdk
> chore: update code owners to infra-db-sdk

- aiplatform/snippets/create_dataset.go
- aiplatform/snippets/create_dataset_test.go
This PR adds the region tag `aiplatform_create_dataset`.
> feat(aiplatform): adds create dataset sample for Vertex

- pubsub/subscriptions/create_cloud_storage_subscription.go
> fix(pubsub): fix cloud storage subscription region tag

- profiler/export/main.go
Minor updates to the profile export sample.
> refactor(profiler): update package name and profile format

- opentelemetry/instrumentation/app/logger.go
- opentelemetry/instrumentation/app/setup.go
> chore(opentelemetry): fix typo of "hander" -> "handler"

- vertexai/chat/chat.go
- vertexai/chat/chat_test.go
- vertexai/function-calling/functioncalling_test.go
- vertexai/multimodal-multiple/multiple-multimodal.go
- vertexai/multimodal-multiple/multiple-multimodal_test.go
- vertexai/multimodal/multimodal.go
- vertexai/multimodal/multimodal_test.go
- vertexai/safety-settings-multimodal/safety-settings-multimodal.go
- vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
- vertexai/safety-settings/safety-settings.go
- vertexai/safety-settings/safety-settings_test.go
- vertexai/snippets/try_gemini.go
- vertexai/snippets/try_gemini_test.go
`"gemini-vision"` -> `"gemini-1.0-vision"`
`"gemini-pro-vision"` -> `"gemini-1.0-pro-vision"`
I tested the new names and confirm they work.
> feat(vertexai): model names gemini 1.0

- vertexai/chat/chat.go
- vertexai/snippets/try_gemini.go
> chore(vertexai): consistent usage of context.Background

- storage/service_account/hmac/hmac_test.go
With retries, the delete operation can return a 400 error.
Fixes #3802
> test(storage): fix error case for HMAC test

- speech/speech_quickstart_v2/README.md
> fix(speech): updated README.md to update apiv1 to apiv2

- compute/address/address_test.go
- compute/address/reserve_new_external.go
> feat(compute): compute_ip_address_reserve_new_external sample

- compute/address/address_test.go
- compute/address/get_external.go
> feat(compute): compute_ip_address_get_static_address sample

- videointelligence/video_analyze/video_analyze.go
> fix: update practices from deprecated ioutil to os

- compute/disk-images/disk_image_test.go
- compute/disk-images/get_disk_image_from_family.go
> feat: compute images get family sample

- compute/address/address_test.go
- compute/address/assign_static_address_to_existing_vm.go
> feat(compute): compute_ip_address_assign_static_existing_vm sample

- jobs/v3/howto/basic_job_sample.go
> chore: add job prefix to job sample

- jobs/v3/howto/commute_search_sample.go
> fix(jobs): add valid region tag job_discovery_commute_search

- jobs/v3/quickstart/main.go
> fix(jobs): update region tag job_search_quick_start]

- dataproc/quickstart/quickstart.go
> fix: update quickstart.go to remove ioutil

- aiplatform/snippets/create_dataset.go
> fix: Update Practices (fmt.Errorf from %v to %w)

- docs/appengine/runtime/app.yaml
> fixit: remove unused region tag

- jobs/v3/howto/auto_complete_sample.go
See Google-internal link: [b/347825843](http://b/347825843)
> chore: Add job_ prefix to auto_complete_sample.go

- functions/functionsv2/slack/search.go
> fix: update practices from deprecated ioutil to io

- jobs/v3/howto/auto_complete_sample.go
See Google-internal link: [b/347825843](http://b/347825843).
The relevant cloud.google.com docs have been updated: [cl/647103691](http://cl/647103691).
> chore: Remove unused region tags in auto_complete_sample.go

- jobs/v3/howto/commute_search_sample.go
> fix: removed old region tag 

- discoveryengine/search.go
> samples(discoveryengine): Update Vertex AI Search sample to use regional endpoint if needed

- jobs/v3/howto/basic_job_sample.go
> chore: remove get_job region tag from basic_job_sample.go

- jobs/v3/howto/basic_company_sample.go
- jobs/v3/howto/custom_attribute_sample.go
- jobs/v3/howto/histogram_search_sample.go
- internal
b/347825848, b/347825862, b/347825867, b/347825868, b/347825922, b/347825933, b/347825940, b/347825950, b/347825958
> fixit: migrate to new region tag in jobs

- jobs/v3/howto/basic_company_sample.go
- jobs/v3/howto/basic_job_sample.go
- jobs/v3/howto/custom_attribute_sample.go
- jobs/v3/howto/location_based_search_sample.go
- Internal: b/347825844
- Internal: b/347825952
- Internal: b/347825964
- Internal: b/347825934
> fixit: migrate to new region tag with prefix 'job_'

- vertexai/multimodal-all/multimodalall.go
- vertexai/multimodal-all/multimodalall_test.go
> fix: simplifying gemini all modalities sample

- speech/snippets/auto_punctuation.go
- speech/snippets/auto_punctuation_test.go
removed the incorrect import regions tag and adjusted the speech_transcribe_auto_punctuation START tag.
Internal: b/347826274
> fix: update incorrect region tags

- batch/create_with_gpu.go
- batch/create_with_gpu_test.go
> feat: create batch with GPU accelerator sample

- batch/create_with_custom_events.go
- batch/job_basics_test.go
> feat: create batch custom events sample

- testing/kokoro/earliest-version.cfg
- testing/kokoro/latest-version.cfg
Please merge PR once we have a 1.22 image and this is approved.
> chore: update kokoro go versions

- endpoints/getting-started/deployment.yaml
> fix: step 1 of adding region tag

- compute/reservations/create_reservation.go
- compute/reservations/delete_reservation.go
- compute/reservations/get_reservation.go
- compute/reservations/list_reservations.go
- compute/reservations/reservations_test.go
Created 4 new samples with basic operations:
- create
- delete
- get
- list
> feat: reservations create/get/list/delete samples

- .github/workflows/go.yaml
> chore: fix linter issue

- bigquery/bigquery_analyticshub_quickstart/main.go
- bigquery/go.mod
- bigquery/go.sum
> docs: update analyticshub sample to use v1 analyticshub client

- vertexai/snippets/gemini_translate.go
- vertexai/snippets/gemini_translate_test.go
- vertexai/snippets/go.mod
Shows how to us gemini as a translator
> feat: gemini translate sample

- README.md
> fix: update sample acceptance policy

- firestore/vector_search_basic.go
- firestore/vector_search_distance_threshold.go
- firestore/vector_search_prefilter.go
- firestore/vector_search_result_field_masked.go
- Correcting the region tags
- Addressing the comments from https://github.com/GoogleCloudPlatform/golang-samples/pull/4358#pullrequestreview-2286669426
> docs(firestore): Correcting the region tags

- aiplatform/snippets/embeddings.go
- aiplatform/snippets/embeddings_preview.go
Fixes: b/366507572: Getting embeddings using text-embedding-005
> feat: Getting embeddings using text-embedding-005.

- testing/kokoro/system_tests.sh
> chore: clean builds

- managedkafka/clusters/create_cluster.go
> Fix: managedkafka subnet comment format

- managedkafka/consumergroups/update_consumergroup.go
> Fix: update_consumergroup partitionOffsets

- managedkafka/topics/create_topic.go
- managedkafka/topics/update_topic.go
> Fix: managedkafka create_topic and update_topic samples

- vertexai/embeddings/generate_for_image_and_text.go
- vertexai/embeddings/generate_for_image_text_and_video.go
- vertexai/embeddings/generate_for_video.go
- vertexai/embeddings/generate_with_lower_dimension.go
Fix small typos and repetitive punctuation errors in vertexai/multimodal embeddings samples.
> fix(vertexai): typos and punctuation

- speech/snippets/model_selection.go
Add new region tag for old tag "imports" to associate it with an official product and function. Migration Step 1
Fixes [b/347826294](http://b/347826294)
> fix(speech): migrate imports region from file model_selection.go step 1

- language/analyze/analyze.go
Migration step 1
- Add new region tag "language_imports"
The region tag was choosen to be a general tag because all the language samples imports the package the same way this sample.
Fixes [b/347826215](http://b/347826215)
> fix(language): migrate imports region tag step 1

- endpoints/getting-started/k8s/esp_echo_http.yaml
Add _go suffix to regions
Fixes
[b/347825430](http://b/347825430)
[b/347825408](http://b/347825408)
> fix(endpoints): add _go suffix to regions

- jobs/v3/howto/basic_job_sample.go
Delete old region tag "create_job"
Fixes [b/389074887](https://b.corp.google.com/issues/389074887)
> fix(job): delete old region "create_job"

- jobs/v3/howto/location_based_search_sample.go
Remove old region tags
Fixes [b/386373912](https://b.corp.google.com/issues/386373912)
> fix(job): remove old region tags

- docs/appengine/storage/app.go
Migration step 2
Delete old region tags
Fixes [b/387483288](https://b/387483288)
> fix(gae): delete old region tags

- docs/appengine/taskqueue/push/defer.go
As a frozen sample only main repo will be modified, not documentation
Fixes [b/389115039](https://b.corp.google.com/issues/389115039)
> fix(gae): migrate region "deferred_tasks"

- appengine_flexible/go115_and_earlier/static_files/static/main.css
- appengine_flexible/static_files/static/main.css
Delete unused region tags from static_files .css
Fixes 
[b/392662654](https://b.corp.google.com/issues/392662654)
> chore(gae): delete unused region tags from static_files .css

- docs/appengine/modules/module.go
Migrate the region tags "communication_between_modules_1" and "communication_between_modules_2" to associate them with an official GCP product.
Fixes
[b/394576408](http://b/394576408)
[b/394576846](http://b/394576846)
> chore(gae): migrate region tags from docs/appengine/modules/module.go

- docs/appengine/datastore/indexes/index.yaml
- docs/appengine/datastore/projectionqueries/projectionqueries.go
Delete region tags from docs/appengine/datastore/indexes/index.yaml
Fixes
b/394594341
b/394594345
> chore(gae): delete old regions from "../indexes/index.yaml"

- vision/detect/detect.go
Delete unused region tag "imports".
Fixes Internal: b/397204807
> fix(vision): delete unused region tag "imports"

- speech/snippets/enhanced_model.go
Delete unused region "imports"
Fixes Internal b/397531444
> chore(speech): delete unused region "imports"

- appengine/go11x/helloworld/app.yaml
- appengine_flexible/helloworld/app.yaml
update go version in app.yaml for helloworld apps
> feat(go): update go version in app.yaml for helloworld apps

- docs/appengine/storage/app.go
Update deprecated library ioutil from file docs/appengine/storage/app.go
Fixes Internal b/391154946
> fix(gae): update deprecated package ioutil

- .github/CODEOWNERS
update storage codeowners team to the current owner
> fix(storage): update storage codeowners team

- docs/appengine/datastore/entities/overview.go
removes last invalid region tag in Go
> chore: remove old region tag

- genai/content_cache/contentcache_delete.go
> docs(genai): update region tag

- translate/v3/translate_text.go
> chore(translate): rename and remove unused region tags.

- genai/content_cache/contentcache_create_with_txt_gcs_pdf.go
- genai/content_cache/contentcache_delete.go
- genai/content_cache/contentcache_update.go
- genai/content_cache/contentcache_use_with_txt.go
> feat(genaisdk): update contentcache to v1 from v1beta
